common/tests/test_bit_utils.cpp, include/common/core/bit_utils.hpp, include/firmware/common/uart_comms.hpp, include/pipettes/core/communication.hpp
bit_utils didn't have a way to check that its inputs and outputs matched
in size, and had some other safety stuff around appropriate inputs that
wasn't there.
Now, we check the sizes of the available containers (in the for loops);
check the appropriateness of the contained int with an (annoying)
template requirement; and have an overload of bytes_to_int for iterator
pairs as well as a generic container that fulfills range, which should
work with any listlike container or view.
=> fix(common): bit_utils: handle size checking

gantry/firmware/uart.c, pipettes/firmware/uart.c
The higher clock speed was too large for the given baudrate we were using for uart. Updating it to 115200 from 9600 fixes this issue.
=> fix(uart): modify UART baudrate to match higher clock speed

common/firmware/STM32G491RETx/clocking.c, common/firmware/errors/errors.c, common/firmware/spi/spi.c, common/firmware/uart/uart.c, gantry/firmware/CMakeLists.txt, gantry/firmware/clocking.c, gantry/firmware/main.cpp, include/common/firmware/clocking.h, include/common/firmware/errors.h, include/common/firmware/spi.h, include/common/firmware/uart.h, pipettes/firmware/CMakeLists.txt, pipettes/firmware/clocking.c, pipettes/firmware/main.cpp
We shouldn't have the RCC clock select function be dependent on UART. This PR separates that function, and also error handler functions into their own C files that can be used as needed.
Are we OK with the file locations/naming/functionality as is? Anything you'd like changed?
=> refactor(common): pull RCC clock select into the common directory

.github/workflows/run_emulation.yaml
Create Github Action that spins up OT-3 Emulator with latest version of firmware. 
Using an ubuntu 20.04 system, setup SocketCan driver, checkout the firmware repo, spin up the emulator with pushed/pull requested version of the firmware.
Currently the emulator just runs a simple script where it receives some CAN commands, echos them back, and exits. 
Down the line it will be updated with tests
=> chore(ci): Integrate Github Action

common/firmware/i2c/i2c_comms.cpp, include/can/core/ids.hpp, include/can/core/messages.hpp, include/pipettes/core/eeprom.hpp, pipettes/firmware/can_task.cpp, pipettes/tests/test_eeprom.cpp
Closes ticket RET-110 in jira. With this PR you should be able to read and write to the eeprom via CAN messaging. I randomly picked the arbitration IDs, if you don't like them I'm very open to changing it.
Is the size of messages OK, or will it be a problem in CANBus? Anything else I didn't account for?
=> feat(eeprom): add eeprom messages to CANBus

can/tests/test_messages.cpp, include/can/core/device_info.hpp, include/can/core/messages.hpp, pipettes/firmware/can_task.cpp
- Fill out `DeviceInfoRequest` and `DeviceInfoResponse` messages
- Add `DeviceInfoHandler` to handle device info messages. 
- Pipette sub-project handles `DeviceInfoRequest` messages.
closes RET-164 in Jira.
=> feat(can): Can device id message

common/firmware/errors/errors.c, include/can/core/freertos_can_dispatch.hpp, include/can/core/message_writer.hpp, include/common/core/freertos_synchronization.hpp, include/common/core/freertos_task.hpp, include/common/firmware/clocking.h, include/common/firmware/errors.h, pipettes/firmware/can_task.cpp, pipettes/firmware/clocking.c, pipettes/firmware/main.cpp, pipettes/firmware/system_stm32g4xx.c
There are quite a lot of warnings, related to different things. I have tried to reduce warnings that
were unrelated to the HAL layer of things. Some of these files were touched in the FreeRTOS PR, but
I plan to open a separate PR for that once the motor controller task stuff is in a good place. There
were a few CAN related warnings that I did not know how to resolve.
RET-191
=> refactor(pipettes): reduce some of the warnings generated in the pipettes project

can/simulator/rtos_main.cpp, can/tests/test_dispatch.cpp, can/tests/test_messages.cpp, include/can/core/arbitration_id.hpp, include/can/core/can_bus.hpp, include/can/core/device_info.hpp, include/can/core/dispatch.hpp, include/can/core/ids.hpp, include/can/core/message_writer.hpp, include/can/core/messages.hpp, pipettes/firmware/can_task.cpp
- Move arbitration id data structures to their own file.
- Reduce the verbosity of messages.hpp by defining some base classes.
- Separate CanBus concept into two. There was no reason to mix `send` with `add_filter`.
- Fix a data race in MessageWriter.
=> refactor(can): refactor day!

common/firmware/spi/spi.c, common/firmware/spi/spi_comms.cpp, gantry/firmware/main.cpp, include/common/firmware/spi.h, include/common/firmware/spi_comms.hpp
To reduce warnings emitted from macros in the st bsp files, we should try to ensure that we are not
importing hal files unnecessarily in our SPI comms module.
RET-193
=> refactor(spi): remove HAL includes where possible

can/simulator/socket_can.cpp
@DerekMaggio was integrating our python hardware with our firmware emulation and found that our use of FD in python caused the C++ side to ignore messages.
This PR remedies that.
=> fix(simulation): Can sim uses fd

can/README.md, can/simulator/rtos_main.cpp, can/simulator/socket_can.cpp
We had been hard coding the channel to `vcan0`. This allows changing it using an environment variable.
=> fix(cansim): add CAN_CHANNEL environment variable.

include/can/core/message_writer.hpp, include/motor-control/core/move_message.hpp, include/pipettes/core/message_handlers/eeprom.hpp, include/pipettes/core/message_handlers/motor.hpp, pipettes/firmware/can_task.cpp
- move eeprom and motor handlers out of can_task.cpp and into `include/pipette/core/message_handlers`. 
- fix a race condition in `MessageWriter`
- add a minimal Move command structure.
This PR is part of a pairing with @Laura-Danielle to address comments in https://github.com/Opentrons/ot3-firmware/pull/78.
More to come in a future PR.
=> refactor(pipettes): Can pipettes handlers

can/tests/test_messages.cpp, gantry/firmware/can_task.cpp, include/can/core/messages.hpp, include/pipettes/core/message_handlers/motor.hpp, pipettes/firmware/can_task.cpp
With this PR, you should be able to send CAN messages to execute actual motor control. As noted with the TODO message, there is definitely some refactors we can do around templating the motor control stuff.
@amitlissack whenever you make it to the office next, I would appreciate us trying to test this together.
=> refactor(can): make motor message handler execute actual motor control functions

.gitignore, README.md, gantry/CMakeLists.txt, gantry/core/CMakeLists.txt, gantry/core/axis_type.cpp.in, gantry/firmware/CMakeLists.txt, gantry/firmware/can_task.cpp, gantry/tests/CMakeLists.txt, include/can/core/ids.hpp, include/gantry/core/axis_type.hpp
This PR creates the executables for `gantry_x` and `gantry_y` separately through defining the variable `GANTRY_AXIS_TYPE`.
Default is `gantry_x`. Running `cmake --preset=cross -DGANTRY_AXIS_TYPE=gantry_y .` would allow the subsequent executable built for the Y gantry.
=> refactor(gantry): create separate executables for gantry_x and gantry_y

can/core/can_bus.cpp, gantry/core/axis_type.cpp.in, gantry/firmware/CMakeLists.txt, gantry/firmware/can_task.cpp, head/firmware/can_task.cpp, include/can/core/can_bus.hpp, include/gantry/core/axis_type.hpp, pipettes/firmware/can_task.cpp
gantry and pipette projects only accept broadcast and messages for their own node ids
=> feat(can): filter can messages based on node id

can/tests/test_messages.cpp, common/tests/test_move_group.cpp, include/can/core/message_handlers/move_group.hpp, include/can/core/messages.hpp, include/motor-control/core/motion_group.hpp, pipettes/firmware/can_task.cpp
We can use C++-20 default comparison operators for these messages just
fine, we just have to have one in the base class as well.
=> chore(can): make message structs comparable

can/tests/test_messages.cpp, gantry/firmware/can_task.cpp, head/firmware/can_task.cpp, include/can/core/message_handlers/move_group_executor.hpp, include/can/core/messages.hpp, include/motor-control/core/motion_controller.hpp, include/motor-control/core/motor.hpp, include/motor-control/core/motor_driver.hpp, include/motor-control/core/motor_interrupt_handler.hpp, include/motor-control/core/motor_messages.hpp, include/motor-control/core/step_motor.hpp, pipettes/firmware/can_task.cpp, pipettes/tests/test_motor_interrupt_queue.cpp, pipettes/tests/test_motor_pulse.cpp
We're now passing in `duration` (number of ticks) instead of `target position` (number of steps) in the move request. Velocity and acceleration in the move request are now also getting passed down to the motor interrupt handler.
=> refactor(motor-control): update move request

can/tests/test_messages.cpp, include/can/core/messages.hpp
This PR updates the parameters `duration`, `velocity` and `acceleration` in CAN move messages to 32 bits.
=> refactor(can): use 32 bits for move message parameters

pipettes/firmware/CMakeLists.txt, pipettes/firmware/can_task.cpp, pipettes/firmware/i2c.c, pipettes/firmware/spi.c, pipettes/firmware/tim7.c
We want to start using the pipette main board for firmware development since it has the new MCU
embedded in it already.
closes RET-232
=> refactor(pipettes): port all GPIO pins to match the pipette main board

gantry/firmware/can_task.cpp, include/can/core/ids.hpp, include/can/core/message_handlers/move_group.hpp, include/can/core/messages.hpp, pipettes/firmware/can_task.cpp
Add `ClearAllMoveGroupsRequest` to empty all move groups. 
Should consider just removing the message that clears them one at a time. Not clear what the use case is for that.
=> feat(can): add clear all move groups request.

gantry/firmware/main.cpp, gantry/firmware/utility_gpio.c
This PR makes sure the D11 LED is not turned on when the gantry axis board starts up
=> refactor(gantry): turn off LED during GPIO initialization

can/simulator/main.cpp, can/tests/test_dispatch.cpp, can/tests/test_messages.cpp, gantry/firmware/can_task.cpp, head/firmware/can_task.cpp, include/can/core/ids.hpp, include/can/core/message_handlers/motor.hpp, include/can/core/messages.hpp, include/motor-control/core/motion_controller.hpp, include/motor-control/core/motor.hpp, include/motor-control/core/motor_messages.hpp, pipettes/firmware/can_task.cpp
This PR does the following:
1. allows the ability to set and retrieve min&max velocity and acceleration for each subsystem via CAN
2. sets the initial values for min&max velocity and acceleration for each subsystem (values are arbitrary and should be modified in the future)
3. remove GetSpeedRequest&Response
Note: The firmware will only store, update and send over the motion constraints via CAN and not use them to evaluate or reject any moves. That should be handled on the Python side instead. 
closes RET-41 and closes RET-78
Corresponding changes on the Python side: https://github.com/Opentrons/opentrons/pull/8772
=> feat(motion-controller): set and get motion constraints

can/simulator/main.cpp, can/tests/test_messages.cpp, gantry/firmware/can_task.cpp, head/firmware/can_task.cpp, include/can/core/device_info.hpp, include/can/core/ids.hpp, include/can/core/message_core.hpp, include/can/core/message_handlers/motor.hpp, include/can/core/message_handlers/move_group.hpp, include/can/core/message_handlers/move_group_executor.hpp, include/can/core/message_writer.hpp, include/can/core/messages.hpp, pipettes/firmware/can_task.cpp
As a followup on https://github.com/Opentrons/opentrons/pull/8772, this PR adds a NodeId to all of the CAN responses from firmware.
=> refactor(can): add Node ID to all CAN responses

gantry/firmware/can_task.cpp, head/firmware/can_task.cpp, include/can/core/device_info.hpp, include/can/core/message_handlers/motor.hpp, include/can/core/message_handlers/move_group_executor.hpp, pipettes/firmware/can_task.cpp
Now that we have the CAN message writer to handle adding the Node ID to the responses, we no longer need to pass the Node ID to the CAN message handlers.
=> refactor(can): remove NodeID from CAN message handlers

CMakeLists.txt, can/firmware/hal_can_message_buffer.cpp, can/firmware/utils.cpp, common/firmware/i2c/i2c_comms.cpp, gantry/CMakeLists.txt, gantry/firmware/CMakeLists.txt, gantry/firmware/can_task.cpp, gantry/firmware/main.cpp, gantry/firmware/motor_hardware.c, gantry/firmware/motor_hardware.h, head/CMakeLists.txt, head/firmware/CMakeLists.txt, head/firmware/can_task.cpp, head/firmware/main.cpp, head/firmware/motor_hardware.c, head/firmware/motor_hardware.h, include/can/firmware/hal_can_bus.hpp, include/common/firmware/spi_comms.hpp, pipettes/CMakeLists.txt, pipettes/firmware/CMakeLists.txt, pipettes/firmware/can_task.cpp, pipettes/firmware/motor_hardware.c, pipettes/firmware/motor_hardware.h, pipettes/firmware/step_motor.cpp
```
_,-'|
,-'._  |
.||,      |####\ |
\.`',/     \####| |
= ,. =      |###| | i cast -Werror
/ || \    ,-'\#/,'`.
||     ,'   `,,. `.
,|____,' , ,;' \| |
(3|\    _/|/'   _| |
||/,-''  | >-'' _,\\
||'      ==\ ,-'  ,'
||       |  V \ ,|
||       |    |` |
||       |    |   \
||       |    \    \
||       |     |    \
||       |      \_,-'
||       |___,,--")_\
||         |_|   ccc/
||        ccc/
||                hjm
```
You have been visited by the -Werror -Wizard, who has fixed all the compiler warnings and enabled `-Werror` so that they are now compiler errors instead. No more shall we tolerate these warnings! Remove them with extreme prejudice.
=> chore: enable werror on all firmware targets

gantry/firmware/can_task.cpp, head/firmware/can_task.cpp, include/motor-control/core/motor.hpp, include/motor-control/core/motor_driver.hpp, include/motor-control/core/motor_driver_config.hpp, pipettes/firmware/can_task.cpp
Driver setup configurations are now in each subsystem's `can_task.cpp`, probably should do a followup refactor PR to pull all subsystem config out of the task file.
=> refactor(motion-control): allow different driver configurations for subsystems

gantry/firmware/can_task.cpp, head/firmware/can_task.cpp, include/can/core/ids.hpp, include/can/core/message_handlers/motor.hpp, include/can/core/messages.hpp, include/motor-control/core/motor.hpp, include/motor-control/core/motor_driver.hpp, include/motor-control/core/motor_driver_config.hpp, pipettes/firmware/can_task.cpp
This PR adds CAN messages to allow us to read and write to motor driver registers via SPI. Mainly for debug purposes.
I've created a pretty terribly useless concept `RegisterAddress` in case we want to touch any undefined motor register addresses via CAN. Should I be doing this? Let me know your thoughts.
=> feat(motion-control): add CAN messages to read/write to motor driver registers

.github/workflows/gantry.yaml, CMakePresets.json, README.md, gantry/core/CMakeLists.txt, gantry/core/axis_type_x.cpp, gantry/core/axis_type_y.cpp, gantry/firmware/CMakeLists.txt, gantry/tests/CMakeLists.txt
Having the gantry type defined as a combination of cmake variable and
automatically generated file is good, but the downside is that it
requires a cmake reconfigure in between switching gantry types, which is
kind of annoying when it's a frequent task to want to build and use both
gantry types in sequence. Another way to do it is just to have two side
by side targets. They share all the same code except for the gantry type
cpp files, and each target uses a different one.
=> chore(gantry): separate gantry targets

head/firmware/can_task.cpp, head/firmware/motor_hardware.c, head/firmware/tim7.c
Add dispatch handlers for a and z motors. Make a and z motors move with the same move group and task. Follow up PR to add unique IDs to both motors, and dedicated tasks.
=> Head motor handlers

include/can/core/ids.hpp
Remove the CAN messages IDs that were deleted by #163
=> refactor(CAN): remove message ids

pipettes/firmware/tim7.c
The timer interrupt for motor control in the pipettes subproject was going too fast. The result is
that the CAN task could never finish its initialization process, and thus, the timer interrupt for
FDCAN would never get called when a message was sent from python.
For now, we are setting the interrupt in pipettes to be 100KHz -- and we will do the same in a follow-up PR for the gantry/head subprojects. At some point in the future, we may want to change the interrupt to match the minimum frequency requirement for the motors.
=> fix(pipettes): make timer interrupt 100KHz

head/firmware/can_task.cpp
Noticed while resolving merge conflicts. Looks like the commit that
separated the left and right motors on head did not correctly give the
left and right motor interrupt handlers their own separate queues, so
moves would go identically to both motors.
=> fix(head): separate motor queues for left and right

CMakeLists.txt, head/firmware/motor_hardware.c
We were using the Debug build type in cmake with forces `-O0 -g`. Using `RelWithDebInfo` issues `-O2 -g`, which speeds up code by about an order of magnitude, making the execution time of motor interrupts ~750ns instead of ~5us.
While we're at it, speed the head interrupt frequency back up to 100 kHz.
You may have to do a cmake reconfigure with the correct build type to get the benefits of this: `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo --preset=cross` and `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo --preset=cross-pipettes`. New checkouts (or deleting your cmake cache) will use `RelWithDebInfo` by default.
=> fix: use release build type

pipettes/firmware/can_task.cpp
Change the pipette configuration to match the correct pitch of the leadscrew. For now, we will set
the microstepping value to be at 32 μsteps but this could be subject to change.
=> refactor(pipettes): modify pipette motion configurations to match the physical hardware

include/can/simlib/filter.hpp, include/can/simlib/sim_canbus.hpp
`SimCANBus` needs to implement `add_filter` to support the HAL can message filtering.
=> feat(can): simulate hardware filtering

gantry/core/can_task.cpp, head/firmware/can_task.cpp, include/can/core/message_handlers/device_info.hpp, pipettes/firmware/can_task.cpp
move device_info handler to the proper directory.
use DispatchTarget type aliases for cleanerness.
=> refactor(can): a little clean up

pipettes/firmware/can_task.cpp, pipettes/firmware/motor_hardware.c
- make sure the correct GPIO clocks are getting called
- make sure SPI is using the correct GPIO pins when sending configuration settings over to the driver
- cleaned up a few other things.
=> fix(pipettes): clean-up pipette GPIO configurations

can/CMakeLists.txt, can/simlib/CMakeLists.txt, can/simlib/transport.cpp, can/simulator/CMakeLists.txt, can/simulator/main.cpp, gantry/simulator/CMakeLists.txt, gantry/simulator/interfaces.cpp, include/can/firmware/hal_can_bus.hpp, include/can/simlib/sim_canbus.hpp, include/can/simlib/socket_transport.hpp, include/can/simlib/transport.hpp, python/opentrons_ot3_firmware/messages/payloads.py
Create a `create` method to build the socket transport for `SimCanBus`. 
- Can simulator app (FMA loopback) uses the new create method. Can use plain old sockets.
- Gantry simulator uses new create method.
=> refactor(can-sim): can simulation transport create method

pipettes/firmware/can_task.cpp
The microstepping value of chopconf sets the _number of native 1/256th
microsteps_ to move when the driver sees a step pulse. So setting this
to 4 means it takes 2^4=16 1/256 microsteps every pulse, which is 1/16th
microstepping conveniently enough, but for 1/32nd microstepping this
needs to be set to 3 not 5 - 2^3 (8) steps per pulse is 256/8=32
microsteps per quarter cycle.
=> fix(pipettes): use 1/32 microstepping

.github/workflows/run_emulation.yaml
Fixed `OT-3 Emulator` test failing due to issue with opentrons-emulation
- Bumped version to 1.3
- Note that [v1.3](https://github.com/Opentrons/opentrons-emulation/releases/tag/v1.3) is a temporary fix and source code for it will be removed with v2.0 
None
Low as long as the Github Actions work, which they do
=> fix: Fix poetry errors

head/core/can_task.cpp, head/core/tasks.cpp, include/head/core/tasks.hpp
The head FW has three node ids: HEAD, HEAD_LEFT, and HEAD_RIGHT.  This PR adds ability for HEAD FW to respond as node id HEAD rather than either HEAD_LEFT or HEAD_RIGHT.
The presence sensing driver should not be addressable as LEFT or RIGHT. 
Create a new task and queue collection for head that is independent of motor.
=> feat(HEAD): head task refactor to support presence sensing

common/simulation/spi.cpp, common/tests/test_spi.cpp, include/common/simulation/spi.hpp, include/motor-control/core/motor_driver.hpp
As @fsinapi pointed out a read command to the TMC2130 will return the data in the register specified in the previous command.
This PR simulates that behavior in the simulator and fixes the driver.
=> fix(spi): read requires two transmissions.

python/opentrons_ot3_firmware/constants.py, python/opentrons_ot3_firmware/messages/message_definitions.py, python/opentrons_ot3_firmware/messages/messages.py, python/opentrons_ot3_firmware/messages/payloads.py, python/opentrons_ot3_firmware/utils/binary_serializable.py
This adds python message definitions to support FW update over CANFD.
There's a preliminary doc on the FW update plan. 
These messages assume that each data message sent will require an acknowledgement from the FW. That is not the ideal as it might be too slow. I'd rather have some flow control from the FW side based on the CAN FIFO level.
But it gets us to where we can download data to FW.
=> feat(python): add fw update message definitions.

bootloader/CMakeLists.txt, bootloader/core/CMakeLists.txt, bootloader/core/can.c, bootloader/firmware/stm32G4/CMakeLists.txt, bootloader/firmware/stm32L5/CMakeLists.txt, python/opentrons_ot3_firmware/arbitration_id.py, python/opentrons_ot3_firmware/constants.py, python/opentrons_ot3_firmware/messages/message_definitions.py, python/opentrons_ot3_firmware/messages/payloads.py, python/opentrons_ot3_firmware/scripts/generate_header.py, python/tests/opentrons_ot3_firmware/test_constants.py
The bootloader will be written in C and will need to know about CAN arbitration ids. 
This PR adds ability to specify which language to target in the `generate_header` script. Additionally, the `generate_header` script spits out a bit field for C implementation.
The C++ generation is unchanged.
The generated C is like so 
```
/********************************************
* This is a generated file. Do not modify.  *
********************************************/
#pragma once
/** Can bus arbitration id function code. */
enum FunctionCode {
can_functioncode_network_management = 0x0,
can_functioncode_sync = 0x1,
can_functioncode_error = 0x2,
can_functioncode_command = 0x3,
can_functioncode_status = 0x4,
can_functioncode_parameters = 0x5,
can_functioncode_bootloader = 0x6, …
```
=> feat(python,bootloader): expand code generation to support c

gantry/firmware/interfaces.cpp
X homes to the physical right of the robot, and since we want to keep
its positions positive and home to 0, that means that positive motion is
right to left. That means we need to invert the sense of the direction
pin, which is now different from Y, so we need separate settings.
=> fix(gantry): x direction inversion

gantry/core/tasks.cpp, head/core/tasks.cpp, pipettes/core/tasks.cpp
The motor interrupt handlers inform the rest of the system that they
have completed a move using a queue, which they write to using some
methods implemented in each application's core. Those methods need to
use try_send_isr rather than try_send, because the interrupt handler is
calling them from an ISR.
=> fix(*): use send_isr from interrupt handler

bootloader/core/message_handler.c, bootloader/core/messages.c, bootloader/firmware/main.c, bootloader/firmware/node_id.c, bootloader/tests/test_message_handler.cpp, include/bootloader/core/message_handler.h, include/bootloader/core/messages.h, include/bootloader/core/node_id.h, python/opentrons_ot3_firmware/scripts/generate_header.py
Prefix generated C enums with CAN to avoid clashes with C++. More consistent with C-style.
This is an issue for bootloader simulator as it uses both C++ and C generated types.
=> fix(codegen): "Namespace" C enums.

head/firmware/main.cpp, head/firmware/motor_hardware.c
A couple other things that were missed - flip the Z motor activation
setting and initialize the direction pin.
=> fix(head): Missing motor configs

bootloader/firmware/node_id.c, bootloader/firmware/stm32L5/CMakeLists.txt, bootloader/tests/test_message_handler.cpp, can/tests/test_arbitration_id.cpp, include/can/core/message_writer.hpp, include/pipettes/core/can_task.hpp, include/pipettes/core/tasks.hpp, pipettes/core/can_task.cpp, pipettes/core/tasks.cpp, pipettes/firmware/main.cpp, pipettes/simulator/main.cpp, python/opentrons_ot3_firmware/constants.py, python/opentrons_ot3_firmware/messages/message_definitions.py, python/opentrons_ot3_firmware/scripts/generate_header.py
When there are two pipettes attached, they need to have different node
IDs so they can both talk on the bus. The thing that makes them
different from each other is which mount they're on. We therefore can
use a different node id depending on the mount, which can be sensed from
a voltage expressed by a resistor net split between pipette and head
boards.
This commit only creates the new IDs and switches to using them. The pipette
application firmware and bootloader listen to left, arbitrarily.
The next step is to bring up the ADC to sense the voltage on the
resistor net and store its value so we know who we are.
=> feat(can): Node IDs for left and right pipette

bootloader/firmware/main.c, bootloader/firmware/stm32G4/can.c, bootloader/firmware/stm32G4/stm32g4xx_it.c, bootloader/firmware/stm32L5/can.c, bootloader/firmware/stm32L5/stm32l5xx_it.c, include/bootloader/firmware/system.h
- Start the HAL
- Add interrupt handlers typically handled by FreeRTOS
- Fix CAN filters.
=> fix(bootloader): can messaging related fixes

bootloader/simulator/CMakeLists.txt, can/simulator/CMakeLists.txt, gantry/simulator/CMakeLists.txt, head/simulator/CMakeLists.txt, pipettes/simulator/CMakeLists.txt
simulators will use SocketCAN only if building on linux and USE_SOCKETCAN is defined in an env variable.
=> chore(sim): USE_SOCKETCAN env var

bootloader/firmware/stm32L5/node_id_stm32l5xx.c, include/common/firmware/i2c_comms.hpp, include/pipettes/core/i2c_writer.hpp, pipettes/firmware/main.cpp
A couple sneaky things.
One was causing `pipettes` executable to be gigantic.
=> fix: small fixes

include/sensors/core/hdc2080.hpp, include/sensors/core/tasks/environmental_sensor_task.hpp
Actually read from the `DEVICE_ID` register in the initialization function of the environment sensor
=> fix(sensors): specify the correct register to read from in initalization

README.md, can/simlib/transport.cpp, include/can/simlib/socket_transport.hpp
Very stubbornly not using boost for some reason.
=> feat(sim): socket simulators use hostname instead of ip

include/can/core/messages.hpp, include/sensors/core/message_handlers/sensors.hpp, include/sensors/core/tasks/environmental_sensor_task.hpp, include/sensors/core/utils.hpp, pipettes/core/can_task.cpp, python/opentrons_ot3_firmware/constants.py, python/opentrons_ot3_firmware/messages/message_definitions.py, python/opentrons_ot3_firmware/messages/messages.py, python/opentrons_ot3_firmware/messages/payloads.py
Add CAN messages to set and receive the threshold value for a given sensor.
=> feat(sensors): add threshold configuration messages to CAN

head/firmware/adc/adc.c, head/firmware/adc/adc_comms.cpp, include/head/firmware/adc.h
`adc_setup` was not being called which led to `adc_set_chan` to enter the error handler because the handle's `Instance` member was `NULL`.
I've tested this on my nucleo board and nothing breaks.
=> fix(head): presence sensing fix(?) 

bootloader/firmware/main.c, common/firmware/system/iwdg.c, common/firmware/system/iwdg.cpp, gantry/firmware/CMakeLists.txt, gantry/firmware/interfaces.cpp, gantry/firmware/main.cpp, gantry/firmware/utility_gpio.c, head/firmware/CMakeLists.txt, head/firmware/main.cpp, include/common/firmware/iwdg.h, include/common/firmware/iwdg.hpp, include/common/firmware/utility_gpio.h, pipettes/firmware/CMakeLists.txt, pipettes/firmware/main.cpp, pipettes/firmware/utility_gpio.c
This PR enables the IWDG. It expires after 1 second. When the watchdog expires the system will be reset.
A task is introduced that will refresh the watchdog timer every 950ms.
The bootloader detects when a restart occurred because of IWDG and does not automatically jump to the main application.
=> feat: enable IWDG in all applications

bootloader/core/message_handler.c, bootloader/core/messages.c, bootloader/firmware/CMakeLists.txt, bootloader/firmware/crc32.c, bootloader/firmware/main.c, bootloader/firmware/stm32G4/system_stm32g4xx.c, bootloader/firmware/stm32L5/system_stm32l5xx.c, bootloader/firmware/updater.c, bootloader/tests/test_messages.cpp, include/bootloader/core/messages.h, include/bootloader/firmware/crc32.h
The download complete message now includes a crc32 of the entire application data.  We are using the HAL crc module to compute the crc. 
The crc is generated by python's `binascii.crc32`. There was a bit of monkeying around to get the HAL CRC to match the python generated.  This makes me a little nervous and I'm kind of wondering whether we should use a plain old checksum.
Anyway. It works. Tested on G4.
=> feat(can): crc 32 checksum of entire fw update

common/firmware/spi/spi.c, common/firmware/spi/spi.h, common/firmware/spi/spi_comms.cpp, common/simulation/spi.cpp, common/tests/test_spi.cpp, gantry/core/utils.cpp, gantry/firmware/interfaces.cpp, gantry/simulator/interfaces.cpp, head/firmware/main.cpp, head/simulator/main.cpp, include/common/core/spi.hpp, include/common/firmware/spi_comms.hpp, include/common/simulation/spi.hpp, include/gantry/core/interfaces.hpp, include/gantry/core/utils.hpp, include/motor-control/core/motor.hpp, include/motor-control/core/motor_driver.hpp, include/motor-control/core/tasks/motor_driver_task.hpp, include/motor-control/core/tmc2130.hpp, include/motor-control/core/tmc2130_registers.hpp, include/pipettes/tests/test_motor_control.hpp, motor-control/tests/test_motor_driver.cpp, pipettes/firmware/main.cpp, pipettes/simulator/main.cpp
This copies @fsinapi's TMC2130 implementation in [opentrons-modules](https://github.com/Opentrons/opentrons-modules/pull/232) for the OT3. We now have a nice `TMC2130RegisterMap` so the driver configuration is more readable and can be modified easily. We're keeping the way SPI works in the OT3 for now, and we should think about doing refactor there and make SPI its own task.
=> refactor(motor-driver): update tmc2130 communications

head/core/can_task.cpp, include/bootloader/core/ids.h, include/can/core/ids.hpp, include/can/core/message_handlers/system.hpp, include/can/core/messages.hpp, include/gantry/core/can_task.hpp, pipettes/core/can_task.cpp
Add request to read FreeRTOS task info. The request results in a sequence of responses; one for each running task.
Using the https://freertos.org/uxTaskGetSystemState.html function we return each tasks:
- name
- current priority
- run time counter
- stack high water mark
- current state
This could be useful in fine tuning stack sizes, balancing priorites, etc.
=> feat(can): add freertos task info request/response

common/simulation/i2c_sim.cpp, include/can/core/messages.hpp, include/common/tests/mock_queue_client.hpp, include/motor-control/core/utils.hpp, include/pipettes/core/i2c_writer.hpp, include/pipettes/core/messages.hpp, include/pipettes/core/tasks.hpp, include/pipettes/core/tasks/eeprom_task.hpp, include/pipettes/core/tasks/i2c_task.hpp, include/sensors/core/callback_types.hpp, include/sensors/core/fdc1004.hpp, include/sensors/core/hdc2080.hpp, include/sensors/core/message_handlers/sensors.hpp, include/sensors/core/tasks/capacitive_sensor_callbacks.hpp, include/sensors/core/tasks/capacitive_sensor_task.hpp, include/sensors/core/tasks/capacitive_sensor_task_starter.hpp, include/sensors/core/tasks/environment_sensor_callbacks.hpp, include/sensors/core/tasks/environmental_sensor_task.hpp, include/sensors/core/tasks/environmental_sensor_task_starter.hpp, include/sensors/core/utils.hpp, include/sensors/simulation/fdc1004.hpp, include/sensors/tests/callbacks.hpp, motor-control/core/utils.cpp, pipettes/core/tasks.cpp, pipettes/simulator/main.cpp, pipettes/tests/CMakeLists.txt, pipettes/tests/test_capacitive_sensor.cpp, pipettes/tests/test_environment_sensor.cpp, pipettes/tests/test_i2c_task.cpp, pipettes/tests/test_i2c_writer.cpp
Apologies for the PR being all over the place. I tried to split up the commits, at least, to make it more readable.
Overall, this PR adds support for the fdc1004 capacitive sensor. There is an ability to set an offset -- depending on the environment the sensor is in. The idea here for the offset specifically is that you would be able to get the new offset by sending a `BaselineSensorRequest`, and then you would send over a `WriteToSensor` request to update the current sensor offset on the capacitive sensor itself.
- Added in an `offset` parameter to the `Read/Baseline` requests which will determine whether you are taking a sensor read or an offset read (this is used for both the pressure and capacitive sensor)
- Added the ability to poll from multiple registers
- Modified polling so that …
=> feat(pipettes): add capacitive sensor support

bootloader/core/update_state.c, bootloader/firmware/main.c, bootloader/firmware/stm32G4/stm32g4xx_it.c, bootloader/firmware/stm32L5/stm32l5xx_it.c, bootloader/firmware/updater.c, include/bootloader/core/update_state.h
Instead of using `HAL_FLASHEx_Erase` we are now using `HAL_FLASHEx_Erase_IT` to erase flash. 
`HAL_FLASHEx_Erase` was taking about 5 seconds which didn't give us an opportunity to reset the watchdog resulting in reset.
This PR enables flash interrupt and implements the complete and error callbacks called from the HAL Flash IRQ handler.
This has been tested on G4, but not L5.
=> refactor(bootloader):  use interrupt version of flash erase

gantry/core/utils.cpp, head/firmware/main.cpp
Updating the gantry & head's irun value to `0x18` which sets the motor current to be roughly 1.4 A.
=> refactor(motor-current): change ihold irun values for gantrys and heads

common/core/tool_detection.cpp, head/firmware/adc/adc.c, head/firmware/adc/adc_comms.cpp, head/firmware/main.cpp, head/tests/test_presence_sensing_driver.cpp, head/tests/test_voltage_conversion.cpp, include/can/core/message_writer.hpp, include/common/tests/mock_adc_channel.hpp, include/common/tests/mock_message_writer.hpp, include/head/core/attached_tools.hpp, include/head/core/presence_sensing_driver.hpp, include/head/core/tasks/presence_sensing_driver_task.hpp, include/head/firmware/adc.h, include/head/tests/mock_adc.hpp, include/sensors/core/tasks/capacitive_sensor_task.hpp
The tool identification voltage ranges will sometimes not quite be
right, and the values coming out of the ADC can bounce around slightly.
This can combine to have the head spam the canbus with tool detection
notification change messages bouncing between some normal value and
undefined_tool. In practice, if these values bounce around like this,
it's not reflecting anything physical - so let's filter it out by
latching away undefined_tool, and not allowing the state to go from
valid->invalid since undefined_tool is just an artifact of the way we
categorize things.
We also weren't reading the ADC quite correctly; we need to handle some busy states and also set the right channel.
Put this on a head and monitor on can_mon; you should now see correct notifications when attaching and removing …
=> feat(head): tolerate unknown tool ids

gantry/core/utils.cpp, gantry/firmware/interfaces.cpp, gantry/simulator/interfaces.cpp, gantry/tests/test_linear_motion_config.cpp, include/gantry/core/utils.hpp, include/motor-control/core/linear_motion_system.hpp
Updating the numbers for steps/mm for Gantry X and Gantry Y based on the following values from HW:
> For X:
12.7mm pulley diameter
200 steps / revolution
1/32 microstepping
0.006234097922 mm per microstep
>For Y:
12.7254mm pulley diameter
200 steps / revolution
1/32 microstepping
0.006246566118 mm per microstep
This requires us to update the linear motion system belt config to take in `pulley diameter` instead of pulley tooth pitch. We also need to update the MRES value for the chopconf register from 0x4 to 0x3 to set microstep resolution at 32.
=> refactor(gantry): update motion system config

gantry/firmware/FreeRTOSConfig.h, gantry/firmware/stm32g4xx_it.c, head/firmware/FreeRTOSConfig.h, head/firmware/stm32g4xx_it.c
This fixes HAL_Delay hanging issues by updating `SysTick_Handler` to (1) increment tick and (2) call the freeRTOS xPortSysTickHandler.
=> fix(FreeRTOS): use Freertos systick

bootloader/simulator/main.cpp, common/simulation/app_update.cpp, common/simulation/logging.cpp, common/simulation/spi.cpp, gantry/core/can_task.cpp, gantry/simulator/main.cpp, gripper/core/can_tasks.cpp, gripper/simulator/main.cpp, head/simulator/main.cpp, include/can/simlib/sim_canbus.hpp, include/can/simlib/socket_transport.hpp, include/can/simlib/socketcan_transport.hpp, include/common/core/freertos_task.hpp, include/common/core/logging.h, include/motor-control/core/tasks/brushed_motor_driver_task.hpp, include/motor-control/core/tasks/motion_controller_task.hpp, include/motor-control/core/tasks/motor_driver_task.hpp, include/motor-control/core/tasks/move_group_task.hpp, include/motor-control/simulation/motor_interrupt_driver.hpp, include/pipettes/core/tasks/eeprom_task.hpp, include/sensors/core/tasks/capacitive_sensor_callbacks.hpp, include/sensors/core/tasks/capacitive_sensor_task.hpp, include/sensors/core/tasks/environmental_sensor_task.hpp, pipettes/simulator/main.cpp
Add timestamp, subsystem, and freertos task to logging. 
I tried using Boost but it was brutal. There were some weird cmake hacks I had to make just to get it to (almost) build. I cursed and gave up.
```
[2022-03-14T14:53:27.642285] [GANTRY-Y] [motor-driver] transmit_receive: control=144, data=464898
[2022-03-14T14:53:27.642289] [GANTRY-Y] [motor-driver] transmit_receive: control=145, data=0
[2022-03-14T14:53:27.642293] [GANTRY-Y] [motor-driver] transmit_receive: control=148, data=0
[2022-03-14T14:53:27.642297] [GANTRY-Y] [motor-driver] transmit_receive: control=149, data=1048575
[2022-03-14T14:53:27.642302] [GANTRY-Y] [motor-driver] transmit_receive: control=236, data=50397653
[2022-03-14T14:53:27.642306] [GANTRY-Y] [motor-driver] transmit_receive: control=237, data=393216 …
```
=> feat(logging): better logging in simulation

gantry/firmware/CMakeLists.txt, gripper/firmware/CMakeLists.txt, head/firmware/CMakeLists.txt, pipettes/firmware/CMakeLists.txt
Now that we have bootloaders, the thing we flash when we run a
`project-flash` target is a hex file created by a python script
combining an application hex file and a bootloader hex file.
This was done in cmake by having custom commands+targets for the
application and hex files, and then a custom command+target for the
combined hex called `target-hex-image`.
The custom command for `target-hex-image` had a DEPENDS for the custom
target portion of the application and bootloader hexes. Unfortunately,
per https://cmake.org/cmake/help/v3.21/command/add_custom_command.html,
a DEPENDS argument that is a custom target creates a target level
dependency "to make sure the target is built before any target using
this custom command"; but because the DEPENDS arg is a custom target and
_not_ a library …
=> fix(build): proper deps for combined hex files

include/head/core/tasks/messages.hpp, include/head/core/tasks/presence_sensing_driver_task.hpp, include/motor-control/core/tasks/brushed_motor_driver_task.hpp
`AttatchToolRequest` should always respond with attached tools. Regardless of whether there's a change from the last poll.
=> fix(head): Head detect bug

include/motor-control/core/motor_interrupt_handler.hpp, include/motor-control/core/tmc2130.hpp, motor-control/tests/test_limit_switch.cpp
- Set position to 0 after homing concludes
- Initialize the position tracker to a large positive value before homing starts, since homing will move negative and if we start the position at 0 and move negative we'll run into trouble
This is hardware tested and works great but we should probably have some unit testing
=> fix(motor-control): homing fixups

include/can/core/messages.hpp, include/sensors/core/tasks/capacitive_sensor_callbacks.hpp, include/sensors/core/tasks/capacitive_sensor_task.hpp, include/sensors/core/tasks/environment_sensor_callbacks.hpp
Can message typo was causing the message to not send over all of the expected data. Also changed the
type of the data to support positive or negative values.
=> fix(pipettes): fix typo in sensor CAN messages and change data type

generate_header.py
Generate c and c++ header definitions so they won't be touched by format
=> fix: generate_header is now format compliant

gripper/firmware/CMakeLists.txt, gripper/firmware/interfaces.cpp, gripper/firmware/motor_hardware.c, gripper/firmware/motor_hardware.h, gripper/firmware/motor_timer_hardware.c, gripper/firmware/stm32g4xx_it.c, gripper/firmware/stm32g4xx_it.h, include/motor-control/firmware/brushed_motor_hardware.hpp, motor-control/firmware/brushed_motor_hardware.cpp, motor-control/firmware/motor_control_hardware.c, motor-control/firmware/motor_control_hardware.h
We're using two separate timers to generate two PWM signals to drive the brushed motor. One line is connected to the PC0 pin (TIM1) and the other PA6 (TIM3). 
Next steps are to implement these features in the motor control module and allow to adjust the Vref, duty cycle and test for and use the optimum PWM frequency.
=> feat(gripper): generate pwm signals

include/bootloader/core/ids.h, include/can/core/ids.hpp, include/can/core/messages.hpp, include/pipettes/core/pipette_info.hpp, pipettes/core/can_task.cpp, pipettes/core/pipette_type_384.cpp, pipettes/core/pipette_type_96.cpp, pipettes/core/pipette_type_multi.cpp, pipettes/core/pipette_type_single.cpp, pipettes/firmware/CMakeLists.txt
The host needs to be able to query what kind of pipette is attached so
it can display this information to the user, load appropriate settings,
and similar. This information doesn't really belong in the device info
because it's only present on pipettes.
This PR carves out messages and enums for the information and hooks up a
basic message handler that hardcodes a response. In the future, this
information will be either compiled in or stored on the EEPROM.
=> feat(pipettes): add pipette info messages

.github/workflows/run_emulation.yaml
Add `workflow_dispatch` remove `push` from `run_emulation` workflow
=> chore: Add workflow dispatch, remove push to run_emulation workflow

gantry/firmware/interfaces.cpp, gantry/firmware/utility_gpio.c, head/firmware/main.cpp, head/firmware/utility_hardware.c, head/firmware/utility_hardware.h, include/common/firmware/utility_gpio.h, include/motor-control/core/motion_controller.hpp, include/motor-control/core/motor_hardware_interface.hpp, include/motor-control/firmware/brushed_motor_hardware.hpp, include/motor-control/firmware/motor_hardware.hpp, include/motor-control/simulation/sim_motor_hardware_iface.hpp, include/motor-control/tests/mock_motor_hardware.hpp, motor-control/firmware/brushed_motor_hardware.cpp, motor-control/firmware/motor_hardware.cpp, pipettes/firmware/utility_gpio.c
- Added basic GPIO initialization for reading the sync in line on pipettes, gantry, and head.
- Added commands for reading in the `MotorHardwareInterface`
- Still need to add pin configurations for multi and 96 channel pipettes
=> added GPIO initialization, read commands for checking sync line

.github/workflows/pipettes.yaml, pipettes/firmware/CMakeLists.txt, pipettes/firmware/utility_gpio.c
The commit that added the different pipette build types also removed the
`pipette` CMake target, so now cmake silently does nothing in the
pipette build workflows, which means we didn't notice accidentally
breaking the pipette build.
Add the target back to cmake, fix the build issure, and update the
workflow to use presets.
=> fix(pipettes): Fix builds and workflows

pipettes/firmware/CMakeLists.txt, pipettes/firmware/main.cpp, pipettes/firmware/main_multi_i2c.cpp, pipettes/firmware/motor_encoder_hardware.c, pipettes/firmware/motor_encoder_hardware.h, pipettes/firmware/motor_hardware.c, pipettes/firmware/stm32l5xx_it.c, pipettes/firmware/stm32l5xx_it.h
This PR enables the encoder for each Pipette type. The encoder index pin is a different pin configuration based on the low throughput pipettes vs the high throughput pipettes. I have made a condition to compensate the encoder index pin configuration based on pipette_type. This firmware is functional on the pipette by just reading the count register when rotating the pipette. This should bring up encoder pulse count to the CANbus messages that was enable on PR [#317](https://github.com/Opentrons/ot3-firmware/pull/317).
=> Feat(Encoders): Add pipette encoder functionality

gantry/core/can_task.cpp, gripper/core/can_tasks.cpp, head/core/can_task.cpp, include/can/simlib/sim_canbus.hpp, include/common/core/freertos_task.hpp, include/head/core/tasks/presence_sensing_driver_task_starter.hpp, include/i2c/core/tasks/i2c_poller_task_starter.hpp, include/i2c/core/tasks/i2c_task_starter.hpp, include/motor-control/core/tasks/brushed_motion_controller_task_starter.hpp, include/motor-control/core/tasks/brushed_motor_driver_task_starter.hpp, include/motor-control/core/tasks/motion_controller_task_starter.hpp, include/motor-control/core/tasks/motor_driver_task_starter.hpp, include/motor-control/core/tasks/move_group_task_starter.hpp, include/motor-control/core/tasks/move_status_reporter_task_starter.hpp, include/pipettes/core/tasks/eeprom_task_starter.hpp, include/sensors/core/tasks/capacitive_sensor_task_starter.hpp, include/sensors/core/tasks/environmental_sensor_task_starter.hpp, include/sensors/core/tasks/pressure_sensor_task_starter.hpp, pipettes/core/can_task.cpp
The types of the arguments that you use to start a task aren't actually
relevant to the FreeRTOSTask _class_ template, just its start() method.
If that start method becomes templated instead of the class, then its
argument types can be inferred from the call.
This requires a minor refactor to curry the argument holding tuples
through a lambda so that the task starter data doesn't need a
class-level type definition.
=> refactor(*): remove start args from task template

.github/workflows/bootloader.yaml, .github/workflows/can.yaml, .github/workflows/common.yaml, .github/workflows/gantry.yaml, .github/workflows/gripper.yaml, .github/workflows/head.yaml, .github/workflows/i2c.yaml, .github/workflows/pipettes.yaml, .github/workflows/sensors.yaml, .github/workflows/spi.yaml
For some reason, certain things get optimized out of the code using _RelWithDebInfo_ that causes compilation to be successful when it shouldn't be. There isn't a good way to switch between D flags in CMAKE, so for now we should just run CI using the debug flag to try and catch any things that compiling locally did not catch.
=> feat(actions): run CI actions with the debug flag

can/tests/test_messages.cpp, include/can/core/messages.hpp, include/common/core/eeprom.hpp, include/pipettes/core/tasks/eeprom_task.hpp
Modify eeprom can message payloads. These can specify a target address, data length, and buffer.
The messages don't do anything yet. That's for a future PR.
=> feat(eeprom): eeprom can messages generalized

include/bootloader/core/ids.h, include/can/core/ids.hpp, include/can/core/messages.hpp
Add the firmware side of the tip handling commands. Implementation of these commands will happen in
a separate PR.
=> feat(pipettes): add tip handling CAN messages

can/tests/test_messages.cpp, i2c/tests/test_i2c_poll_task.cpp, i2c/tests/test_i2c_poller.cpp, i2c/tests/test_i2c_task.cpp, i2c/tests/test_i2c_writer.cpp, include/eeprom/core/types.hpp, include/eeprom/simulation/eeprom.hpp, include/i2c/core/messages.hpp, include/i2c/core/writer.hpp, include/i2c/tests/mock_response_queue.hpp, sensors/tests/test_capacitive_sensor.cpp, sensors/tests/test_environment_sensor.cpp, sensors/tests/test_pressure_sensor.cpp
- eeprom word address is 8-bits not 16.
- increase i2c max message size to 9 from 5. (eeprom can write 9 byte messages)
- clean up tests to not hard code max message size. so if we have to change the max again we won't have to go through this kind of refactor again.
=> refactor: i2c and eeprom refactor stuff

i2c/tests/test_i2c_writer.cpp, include/i2c/core/writer.hpp
`i2c::writer::Writer` has a `write` method that accepts a register address. This is a nice convenience for writing a buffer to a device that expects the first byte of a transaction to be a memory or register address.
This PR adds the `read` equivalent. When using this method, a transaction is created that initially writes a single byte address followed by a read.
=> refactor(i2c): I2c read register

gantry/core/utils.cpp
We should avoid using std::abort, see [this pr comment](https://github.com/Opentrons/ot3-firmware/pull/335#pullrequestreview-954827637) for further details. The gist is that we do not have proper tooling to do a backtrace on the abort and actually see what caused it.
=> refactor(gantry): do not use std::abort for pin configurations

include/motor-control/core/stepper_motor/tmc2160.hpp, include/motor-control/core/stepper_motor/tmc2160_driver.hpp, include/motor-control/core/tasks/tmc2160_motor_driver_task.hpp, motor-control/tests/test_motor_driver.cpp
Closes RET-915. Adds in a basic setup for the `tmc2160` driver. For now it follows the `tmc2130` driver very closely. Both files should probably be refactored at some point to reduce the amount of functions in each driver.
These tasks will be used in a follow-up PR implementing [Handle multiple motors for pick up tip](https://opentrons.atlassian.net/browse/RET-916)
=> feat(motor-control): add tmc2160 motor control

pipettes/firmware/CMakeLists.txt, pipettes/firmware/main.cpp, pipettes/firmware/motor_hardware.c, pipettes/firmware/motor_hardware.h, pipettes/firmware/motor_timer_hardware.c, pipettes/firmware/motor_timer_hardware.h, pipettes/firmware/stm32l5xx_it.c
Closes RET-915 and is related to RET-916. First small step in enabled 3 motors on the 96 channel.
I chose to use the other basic timer for now. We might want to re-evaluate the types of timers we use more closely depending on each timers individual application.
=> feat(pipettes): add additional basic timer for the gear motors

include/i2c/core/writer.hpp, include/spi/core/writer.hpp
for clients keeping track of transactions, it's nice to know whether the transaction made it to the i2c queue.
=> chore(i2c): Writer returns try_write result

.clang-tidy, bootloader/firmware/main.c, bootloader/firmware/stm32G4/can.c, bootloader/firmware/stm32L5/can.c, can/firmware/hal_can.c, can/tests/CMakeLists.txt, can/tests/test_bit_timings.cpp, gantry/firmware/can.c, gantry/firmware/interfaces.cpp, gripper/firmware/can.c, gripper/firmware/main.cpp, head/firmware/can.c, head/firmware/main.cpp, include/bootloader/firmware/can.h, include/can/core/bit_timings.hpp, include/can/firmware/hal_can.h, include/common/firmware/can.h, pipettes/firmware/can.c, pipettes/firmware/main.cpp
CANbus bit timings are a complicated thing. They depend on four different parameters. All four of the parameters we were using in the firmware were different from what the host system uses in linux, and were all just written down in a way that made it really non-obvious what they meant.
This makes the non-obviousness different by calculating those values from named parameters with units and with compile-time range and correctness checks.
After this PR, the bit timings used by the controllers will be identical to what they were before, but they'll now be generated and tied in with actual canbus canonical parameters. The next step is to change them to more useful values.
This supercedes #346
=> chore(can): generate can timings

i2c/tests/CMakeLists.txt, i2c/tests/test_transaction.cpp, include/i2c/core/transaction.hpp
A class that makes maps transaction id to some arbitrary data.
Will be useful for correlating transaction responses in Eeprom task and perhaps others. 
i2c writer transactions contain a `token` field. This is a `uint32_t` that is meant to connect the `TransactionResponse` to the sent `Transaction`. Some users of the i2c write may want to store some arbitrary data about a transaction when it's sent and use it when processing the response.
For example, the Eeprom task will store the eeprom memory address read from and some pointers for returning responses to the reader. This data will be associated with the `token` sent in the Transaction and  looked up when the TransactionResponse message arrives.
Not used anywhere but tests, yet.
=> chore(i2c): add i2c::transaction::IdMap

can/tests/test_messages.cpp, gripper/firmware/i2c_setup.c, gripper/firmware/main.cpp, include/can/core/messages.hpp, include/i2c/firmware/i2c.h, pipettes/firmware/i2c_setup.c, pipettes/firmware/main.cpp
Results from debugging eeprom on pipette and gripper.
- pin settings weren't right
- write protect is active high
- read response was needlessly large
=> fix(eeprom): eeprom debugging

pipettes/simulator/main.cpp
Pipettes simulator was not starting up.
The eeprom and one of the sensors share the same device address.
This separates i2c sensor map for i2c 1 and 3.
@Laura-Danielle and @caila-marashaj , do I have the mappings correct?
=> fix(pipettes): separate i2c maps for i2c 1 and 3.

gripper/firmware/interfaces_grip_motor.cpp, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, motor-control/firmware/brushed_motor/brushed_motor_hardware.cpp
The pins for the brushed motor direction were incorrect. This PR also fixes the logic in the motor interrupt handler so it actually behaves correctly (only monitor the limit switch when the axis is homing).
=> fix(gripper): fix motor interrupt handler & switch dir pins

can/firmware/hal_can.c, can/firmware/hal_can_bus.cpp, gantry/firmware/interfaces.cpp, gripper/firmware/interfaces_z_motor.cpp, gripper/firmware/main.cpp, head/firmware/main.cpp, include/can/core/bit_timings.hpp, include/can/firmware/hal_can.h, include/can/firmware/hal_can_bus.hpp, include/common/core/freertos_timer.hpp, pipettes/firmware/main.cpp
By adding interrupt handling that queries the protocol status of the FDCAN peripheral and adding LEDs to the firmware c++ hal can bus, we can add (or, well, steal from the motors) LEDs that blink when the canbus changes state. For now,
- Slow blink (~2Hz) when the bus is in ERROR_ACTIVE, which it should be all the time
- Fast blink (~10Hz) when the bus is in ERROR_PASSIVE, when it's gotten a lot of errors but can still transmit
- On solid when the bus is off because it saw too many errors.
We can merge this whenever (doesn't have to wait for the canbus timings to get merged) but we'll need to rebase on main first.
=> feat(can): blink leds when there is a canbus error

include/motor-control/core/tasks/brushed_motor_driver_task.hpp, motor-control/firmware/brushed_motor/brushed_motor_driver_hardware.cpp, motor-control/firmware/brushed_motor/brushed_motor_hardware.cpp
Some small fixes to enable the gripper motor to grip correctly on the OT3: I was wrong about the directions and used the wrong fixed point index for calculating the brushed motor VREF.
=> fix(gripper): direction & v ref calculations

pipettes/firmware/main.cpp
This just got straight up missed in previous commits. The bitrate should be 500kHz and that's the only thing that's not changed.
=> fix(pipette): fix can bitrate

eeprom/tests/CMakeLists.txt, eeprom/tests/test_serial_number.cpp, gripper/core/can_tasks.cpp, include/can/core/messages.hpp, include/eeprom/core/addresses.hpp, include/eeprom/core/serial_number.hpp, include/gripper/core/can_task.hpp, include/gripper/core/gripper_info.hpp, include/pipettes/core/dispatch_builder.hpp, include/pipettes/core/pipette_info.hpp, pipettes/core/can_task_high_throughput.cpp, pipettes/core/can_task_low_throughput.cpp
We read the serial number from the eeprom.
The eeprom on these boards is can only read 8 bytes at a time. Rather than supporting a 12-byte serial number by doing two reads, we'll just use 8 bytes. No need to write throwaway code.
=> feat(gripper,pipettes): read serial number from eeprom

include/sensors/core/tasks/capacitive_sensor_callbacks.hpp, include/sensors/core/tasks/capacitive_sensor_task.hpp, include/sensors/core/utils.hpp, sensors/tests/test_capacitive_sensor.cpp
The capacitive sensor on the pipette is extremely sensitive to its immediate environment. We probably want to zero out the ambient capacitance when it is close to, but not yet touching, whatever it's going to sense.
We could do that today by commanding a reading via can from python; getting the reading back; and then commanding a threshold based on that reading via can. We could also send a command that tells the pipette to take a reading and then use that reading as a new threshold, and we'll save some back-and-forth.
Todo: tests, better use of the message including specifying an offset amount. Required for https://github.com/Opentrons/opentrons/pull/10067
=> feat(sensors): add autothreshold

generate_header.py, include/can/core/ids.hpp, include/can/core/messages.hpp, include/sensors/core/tasks/capacitive_sensor_callbacks.hpp, include/sensors/core/tasks/capacitive_sensor_task.hpp, sensors/tests/test_capacitive_sensor.cpp
We shouldn't hardcode the offset we set when we do an autothreshold; we should allow it to be specified from canbus. This adds a new field to the threshold messages that specifies the mode of the threshold.
=> feat(sensors): Allow setting an offset to autothreshold

include/eeprom/core/serial_number.hpp, include/eeprom/core/task.hpp, include/eeprom/core/types.hpp
FW companion to https://github.com/Opentrons/opentrons/pull/10540
New revs have eeprom that supports 16-bit address. This allows sending 16-bit addresses over CAN, but still uses 8-bit addressing. There's a TODO for how to change.
=> refactor(eeprom): CAN messages support 16-bit messaging.

CMakeLists.txt, include/pipettes/core/interfaces.hpp, include/sensors/core/sensor_hardware_interface.hpp, include/sensors/core/tasks/pressure_driver.hpp, include/sensors/core/tasks/pressure_sensor_task.hpp, include/sensors/firmware/sensor_hardware.hpp, include/sensors/simulation/hardware.hpp, include/sensors/tests/mock_hardware.hpp, pipettes/core/sensor_tasks.cpp, pipettes/firmware/hardware_config.c, pipettes/firmware/hardware_config.h, pipettes/firmware/interfaces.cpp, pipettes/firmware/main.cpp, pipettes/firmware/utility_gpio.c, sensors/tests/test_pressure_sensor.cpp
This pr adds hardware support for the data ready pins on the pipette main boards, but does not check that pin's value or incorporate it into the pressure sensor reads. That will be done in a follow-up pr.
=> Enable data ready fix

include/motor-control/core/stepper_motor/tmc2160.hpp, include/motor-control/core/stepper_motor/tmc2160_driver.hpp, include/motor-control/core/tasks/tmc2160_motor_driver_task.hpp, motor-control/tests/test_motor_driver.cpp, pipettes/firmware/motor_configurations.cpp
The datasheet for the 2160 driver suggests that current be scaled based on the global scalar as
opposed to calculated the value of IRUN Or IHOLD directly. I think we probably need to dig a bit
deeper into stealthchop, whenever we want to actually configure it properly, because there were some
warnings around changing the global scalar while using this feature.
=> refactor(tmc2160): modify how we scale current on the tmc2160 motor driver

include/motor-control/core/tasks/move_group_task.hpp
Some cleanup found while testing the 96 channel
=> refactor(motor-control): Cleanup tip action messages from default motion controller

.github/workflows/bootloader.yaml, .github/workflows/can.yaml, .github/workflows/common.yaml, .github/workflows/eeprom.yaml, .github/workflows/gantry.yaml, .github/workflows/gripper.yaml, .github/workflows/head.yaml, .github/workflows/i2c.yaml, .github/workflows/motorcontrol.yaml, .github/workflows/pipettes.yaml, .github/workflows/sensors.yaml, .github/workflows/spi.yaml, gantry/firmware/CMakeLists.txt, gripper/firmware/CMakeLists.txt, head/firmware/CMakeLists.txt, pipettes/firmware/CMakeLists.txt
Refactor cmake targets to provide default-named outputs for all projects as well as revision and variant outputs. We can then store those outputs in github actions storage so we can distribute and store controlled outputs rather than dev builds.
=> chore: store firmware artifacts from actions

common/core/tool_detection.cpp
They're like the A bounds (though this only matters on the low side).
WIth this pr in place we now properly detect the gripper.
=> fix(head): wider gripper detection bounds

include/motor-control/core/brushed_motor/brushed_motion_controller.hpp, include/motor-control/core/stepper_motor/motion_controller.hpp
When the motors are about to move, they should get enabled without
requiring a previous enable request. This moves the enable motors
message into something used only for turning on motors and holding, as
in the OT-2, rather than a necessary step before turning motors -
removes the possibility for programmer error.
=> refactor(motor-control): Enable automatically

i2c/simulation/i2c_sim.cpp, include/can/tests/mock_message_buffer.hpp, include/motor-control/core/stepper_motor/tmc2130.hpp, include/motor-control/core/stepper_motor/tmc2160.hpp, include/sensors/core/mmr920C04.hpp
While Onboarding there were several errors on my new system that required some minor tweaks to get the "cmake --build ./build-host --target build-and-test" to run on my system.
=> Fix broken compilation on Fedora 36 and G++ 12.1.1

gripper/firmware/motor_hardware.h, gripper/firmware/motor_timer_hardware.c, include/can/core/messages.hpp, include/motor-control/core/brushed_motor/brushed_motion_controller.hpp, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, include/motor-control/core/brushed_motor/driver_interface.hpp, include/motor-control/core/motor_messages.hpp, include/motor-control/core/tasks/brushed_motor_driver_task.hpp, include/motor-control/firmware/brushed_motor/driver_hardware.hpp, include/motor-control/simulation/sim_motor_driver_hardware_iface.hpp
This isn't necessary for gripper workflows.
In addition, we can derive the clock dividers for the pwm driver using
the global from the system file that contains the system clock frequency.
Needs https://github.com/Opentrons/opentrons/pull/10987
=> refactor(gripper): remove pwm freq via can

include/pipettes/firmware/i2c_setup.h, pipettes/firmware/hardware_config.c, pipettes/firmware/i2c_setup.c, pipettes/firmware/main.cpp, pipettes/firmware/motor_configurations.cpp, pipettes/firmware/motor_encoder_hardware.c, pipettes/firmware/mount_detect_hardware.c, pipettes/firmware/utility_gpio.c
Related to #RET-848. For now, we only have the pin configurations available for single/eight channel pipettes. This PR only addresses pin changes, and no functionality change around timers or EXTI callbacks that may need to change.
=> refactor(pipettes): update the G4 pin values for low throughput pipettes

gantry/core/can_task.cpp, gantry/firmware/interfaces_rev1.cpp, gripper/core/can_tasks.cpp, head/core/can_task.cpp, include/can/core/dispatch.hpp
This avoids inadvertently entering the bootloader when the entry message
is directed at another node.
Without this fix, all nodes will enter bootloader when one is commanded
to on a shared bus.
=> fix: filter all incoming messages

eeprom/tests/test_eeprom_task.cpp, eeprom/tests/test_hardware_iface.cpp, include/eeprom/core/hardware_iface.hpp, include/eeprom/core/task.hpp, include/eeprom/simulation/eeprom.hpp
refactor the eeprom hardware interface so that it can be configured to use 16 bit memory addresses. still defaults to the old 8 bit addresses so it doesn't require changes in any of the current code outside of the eeprom library
=> Refactor(eeprom): refactor the hardware interface and task to support 16bit and 8bit memory addresses

include/eeprom/simulation/eeprom.hpp
I was unable to figure out why the eeprom on the python side cannot handle 16 bit addresses even
though [Amit added support](https://github.com/Opentrons/opentrons/pull/10540/files) before leaving. This is a temporary fix as obviously the simulator should be able to handle 16 bit addresses. I made a [ticket](https://opentrons.atlassian.net/browse/RET-1124) to look into it.
Regardless, changing the simulator back to 8 bit addressing at least has the firmware integration tests passing. Other things were failing because the eeprom tests ended up breaking the simulator and caused it to go into the bootloader for both gripper and pipettes. This is because the addressing size didn't match the type in the backing array.
=> refactor(eeprom): temporarily reset eeprom simulation to handle 8 bit address

include/sensors/core/mmr920C04.hpp, include/sensors/core/tasks/pressure_driver.hpp, include/sensors/core/tasks/pressure_sensor_task.hpp, sensors/tests/test_pressure_driver.cpp, sensors/tests/test_pressure_sensor.cpp
This branch implements some support for polling on the firmware side:
- calls driver functions when the `pressure_sensor_task` receives a `BaselineSensorRequest` or `BindSensorOutputRequest`
- sets the sync pin active when the pressure driver receives a measurement above a threshold value
- makes sending a `RESET` command during the pressure driver's interrupt conditional on the pressure driver performing a single read, so polling doesn't get cut short after the first measurement
=> Pressure Sensor Polling Support

gripper/core/can_tasks.cpp
Make sure the gripper node ID filter work correctly
=> fix(gripper):  node id filter

pipettes/firmware/hardware_config.c, pipettes/firmware/motor_hardware.c
The motor was not engaging on the G4 boards because the chip select pin was using the wrong gpio
mode.
=> fix(pipettes): spi chip select gpio mode should be push-pull

include/can/core/messages.hpp, include/sensors/core/tasks/capacitive_sensor_task.hpp, include/sensors/core/tasks/pressure_driver.hpp, include/sensors/core/tasks/pressure_sensor_task.hpp, sensors/tests/test_pressure_driver.cpp, sensors/tests/test_pressure_sensor.cpp
Implemented polling and limited polling for the pressure sensor:
- Sending a `BindSensorOutputRequest` with any value that isn't `none` will tell the sensor to poll continuously and indefinitely 
- the `report` binding will determine whether or not the sensor sends its readings back to the CAN bus
- the `sync` binding determines whether or not it will set the sync pin to active and subsequently stop the pipette motors upon detecting a liquid threshold.
- sending a binding value of 0, or `none`, will stop the polling.
- Sending a `BaselineSensorRequest` will start a limited poll, which will prompt sensor responses to the CAN bus with no delay, reading as many times as specified in the `sample_rate` field
Updated the tests to reflect this stuff, and also changed the data type of the …
=> polling for pressure sensor

gripper/firmware/i2c_setup.c, pipettes/firmware/i2c_setup.c
The ultimate i2c issue on the g4 pipette boards turned out to be a cabling problem, but Joe also
recommended that we change the speed of the i2c gpios to low.
=> refactor(i2c): make GPIO frequencies low

gripper/firmware/interfaces_z_motor.cpp, include/motor-control/core/stepper_motor/tmc2130.hpp, include/motor-control/core/stepper_motor/tmc2130_driver.hpp
Enables passive motor braking using StealthChop. 
Passive braking is enabled by setting the standstill current IHOLD to zero and choosing the desired option using the FREEWHEEL setting (%10 - Coil shorted using LS drivers).
=> feat(motor-control): add stealth chop config for TMC2130

ot3_state_manager/ot3_state_manager/hardware.py, ot3_state_manager/ot3_state_manager/measurable_states.py, ot3_state_manager/ot3_state_manager/messages.py, ot3_state_manager/ot3_state_manager/ot3_state.py, ot3_state_manager/ot3_state_manager/ot3_state_manager.py, ot3_state_manager/ot3_state_manager/pipette_model.py, ot3_state_manager/ot3_state_manager/util.py, ot3_state_manager/poetry.lock, ot3_state_manager/pyproject.toml, ot3_state_manager/tests/conftest.py, ot3_state_manager/tests/test_messages.py, ot3_state_manager/tests/test_ot3_state.py, ot3_state_manager/tests/test_ot3_state_manager.py, ot3_state_manager/tests/udp_client.py
Added asyncio socket communication layer to OT-3 State Manager
See requirements doc [here](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/3322773722/OT3+Emulation+State+Manager#Phase-2%3A-Connect-to-Emulation-(In-Progress))
- Rename `OT3StateManager` to `OT3State` and have it be the only thing that handles update to the overall state view of OT-3
- Create `OT3StateManager` which is responsible for communicating over socket and parsing received messages into update commands for the `OT3State` class to make.
- Add SyncPin` class which represents the OT-3 Sync Pin
- Refactor all classes in `hardware.py` to normal Python classes instead of dataclasses
- What do you think about the format of the messages? 
- In `hardware.py` I had to refactor all the dataclasses to normal python …
=> feat: OT-3 state manager communication (RET-1104)

gripper/firmware/interfaces_grip_motor.cpp, gripper/firmware/motor_encoder_hardware.c, gripper/firmware/motor_encoder_hardware.h, gripper/firmware/motor_hardware.h, gripper/firmware/motor_timer_hardware.c, gripper/firmware/stm32g4xx_it.c, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, include/motor-control/tests/mock_brushed_motor_components.hpp, motor-control/tests/CMakeLists.txt, motor-control/tests/test_brushed_motor_interrupt_handler.cpp
Configures TIM4 to be a tracker for the encoder pulse speed. 
TIM4 counts at 1 MHz and by capturing the counter value between two consecutive encoder pulse edges (4 edges make up one full encoder pulse), we can estimate the speed of the encoder/brushed motor. When the timer overflows (timer period is set to 3 ms), we can assume that the encoder is pulsing at most 8.33 Hz (1 MHz / (30000 x 4 count)). This is slow enough that we can assume the encoder has pretty much stopped. 
We can then use this info to report back to the host that the gripper jaw has stopped moving, instead of relying on an arbitrary duration.
Here's some result I got from testing:
The compare/capture (CCR1) register reading of the TIM4 was 0x2FF, which is 767 us.
=> feat(gripper): track brushed motor encoder speed and use it to complete brushed motor move

ot3_state_manager/ot3_state_manager/messages.py, ot3_state_manager/ot3_state_manager/ot3_state.py, ot3_state_manager/ot3_state_manager/ot3_state_manager.py, ot3_state_manager/ot3_state_manager/pipette_model.py, ot3_state_manager/ot3_state_manager/util.py, ot3_state_manager/tests/conftest.py, ot3_state_manager/tests/test_messages.py, ot3_state_manager/tests/test_ot3_state.py, ot3_state_manager/tests/test_ot3_state_manager.py, ot3_state_manager/tests/udp_client.py
Each message is now mapped to an int value instead using arbitrary string parsing
[Related Docs](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/3322773722/OT3+Emulation+State+Manager#Phase-2%3A-Connect-to-Emulation-(In-Progress))
- Remove `to_message` method from all `Message` classes
- Changed format of messages. All message are now 4 bytes long and have the following format: `<message-id><message-content>` where the length of `message-id` is a single byte and the length of `message-content` is 3 bytes.
- Replace `to_message` method and `parse_message` function with `Message` ABC.
- Each concrete concrete class of Message is required to implement a `build` and `to_bytes` message
- The `_parse_message` method looks at the `message-id` byte and based off of the value passes …
=> refactor(ot3_state_manager): Rework messages

gantry/firmware/interfaces_rev1.cpp
Sets 32 microstep instead of 16 for both gantry x & y.
=> fix(gantry): update mres value to set correct microstep value

head/firmware/main_rev1.cpp, head/firmware/motor_hardware_common.c, head/firmware/motor_hardware_rev1.c
Makes the following changes to the Rev1 board:
1. Reverts the ihold irun value to match the proto board to solve motor movement issues
2. Flips the encoder timer (correct config: left -> tim3, right -> tim2)
3. Adds encoder config so we can actually get encoder position from Ack messages
=> fix(head): motor driver & encoder config

pipettes/firmware/main.cpp, pipettes/firmware/system_stm32g4xx.c, pipettes/firmware/system_stm32g4xx.h
The right mount has a much higher goal tool id voltage than the left mount. When the pipette is hot-plugged into the robot, it takes close to 400ms for the tool id line to settle into the expected voltage.
To get around this, we should delay when we actually sample the tool id line on the pipette to determine what mount it's connected to.
=> refactor(pipettes): add delay on boot to detect the correct id

bootloader/firmware/stm32G4/node_id_stm32g4xx.c, pipettes/firmware/mount_detect_hardware.c
EVT pipettes use pin B0/adc channel 15 for their tool detect lines.
Closes RLIQ-96
=> fix(pipettes): correct adc channel usage for evt

common/core/tool_detection.cpp, common/tests/test_tool_detection.cpp, head/tests/test_presence_sensing_driver.cpp, include/bootloader/core/ids.h, include/can/core/ids.hpp, include/common/core/tool_detection.hpp, include/head/core/attached_tools.hpp, include/head/core/presence_sensing_driver.hpp, pipettes/tests/test_mount_detection.cpp
Awhile ago, we no longer wanted to try and determine the instrument type based on the ADC because it
was too variable. Now, we are cutting down what values are valid and also changing the ranges
provided in [this confluence doc](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/940834928/OT-3+Tool+ID+Implementation).
=> refactor(head): change the instrument values reported by the ADC

i2c/firmware/i2c.c, include/i2c/core/messages.hpp, include/i2c/core/tasks/i2c_task.hpp, pipettes/firmware/main.cpp
The rev1 pipettes use an M24128 eeprom. We added code to handle this ahead of time, but it had a few issues that this PR fixes.
- rev1 pipettes use M24128 eeprom, not the older kind. Explicitly set them to do so.
- M24128 eeproms have a time period after they start a write during which they won't respond on I2C. We can fix this by retrying I2C messages when we get NAKs
- An I2C NAK indicates that a device won't respond to a message. This can
be for basically any reason, including that it doesn't recognize it, but
one reason is that the device isn't ready yet. For instance, the M24128
eeprom will NAK all incoming messages during its write delay. That means
that the NAK can be a good way to get low-latency estimations of when a
device is ready to transmit. By altering the i2c hardware …
=> fix(pipettes): rev1: bring up M24128 eeprom

can/simlib/transport.cpp, include/eeprom/simulation/eeprom.hpp
The options specified through environment variables need to have the
same names as the command line options. You then define what variables
you support in the name transformation lambdas.
With this change we should now properly support environment variable
specification of options.
=> fix(simulators): parse environment properly

pipettes/core/configs.cpp
Previously, the steps per mm we were using for pipettes was actually 2112.21 steps per mm. I
confirmed with hardware that the steps per mm we actually want to be using for the single and eight
channel pipettes is actually 2133.33 steps per mm.
=> refactor(pipettes): modify the steps per mm to 2133.33 steps per mm

gripper/firmware/motor_encoder_hardware_proto.c
https://opentrons.atlassian.net/browse/RLAB-98
Found a bug that when the motor is driven at high speed, the number of encoder pulses that get sent to reset the slave speed timer is too great. While everything works fine in release mode, in debug mode this overruns the mcu and causes a crash.
Solution is to prescale the slave timer to 4, this reduces the reset from 4x per encoder tick (1 per each rising/falling edge) to 1 per complete encoder tick
=> Fix(gripper): reconfigure configure encoder inputs to solve MCU crash

include/motor-control/core/stepper_motor/tmc2160.hpp
This PR allows us to configure stealth chop for the TMC2160 driver. 
We don't currently use it but I figured we might need it after some more testing with the EEs & testing team.
=> feat(motor-control): add stealthchop config to tmc2160

gantry/firmware/interfaces_rev1.cpp
The X motor has been switched to the opposite side of the gantry/pulley and needs to have its direction switched.
=> refactor(gantry): change the direction of the X motor

include/eeprom/simulation/eeprom.hpp, pipettes/simulator/main.cpp
Closes RQA-288.
For now, the simulated pipette should start with a valid serial number. Eventually, the emulator should be able to set the serial number for the pipettes on boot.
=> feat(pipettes): begin simulator with a valid pipette serial number

gantry/firmware/interfaces_rev1.cpp, head/firmware/main_rev1.cpp, include/motor-control/core/stepper_motor/tmc2160_driver.hpp, include/motor-control/core/tasks/tmc2160_motor_driver_task.hpp, motor-control/tests/test_motor_driver.cpp, pipettes/firmware/motor_configurations.cpp, pipettes/firmware_l5/motor_configurations.cpp, pipettes/simulator/motor_configurations.cpp
Erroneously, we thought that you needed to set the global scaler rather than the ihold/irun registers directly on the tmc2160. In actuality, you only adjust the global scaler to find a good default value. The EEs have calculated that ~167 is an acceptable value to get us to a max current of 1.5amps when irun is 31.
RET#1261
=> refactor(tmc2160): use the correct method of setting current

pipettes/firmware/hardware_config.c, pipettes/firmware/main.cpp, pipettes/firmware/stm32g4xx_it.c, pipettes/firmware/utility_gpio.c
Since the transition to the STM32G4 for the EVT pipettes, we need to make a couple of changes to our interrupt service routine:
- change the EXTI input line from `EXTI9_5_IRQn` to `EXTI3_IRQn`, to correspond with the change in the pressure sensor's data ready pin from `GPIO_PIN_9` to `GPIO_PIN_3`
- change the HAL function that gets implemented in our firmware from `HAL_GPIO_EXTI_Falling_Callback` to `HAL_GPIO_EXTI_Callback`, since the source code is slightly different between the STM32L5 and the STM32G4
This pr just allows the interrupt code in `pipettes/firmware/main.cpp` to be called and executed as expected.
=> fix(pipettes): update pressure sensor interrupt for stm32g4

gantry/core/utils.cpp, gantry/firmware/interfaces_proto.cpp, gantry/firmware/interfaces_rev1.cpp, gantry/firmware/motor_hardware.c, gantry/simulator/interfaces.cpp, gantry/tests/test_linear_motion_config.cpp, gripper/firmware/interfaces_z_motor.cpp, gripper/firmware/motor_timer_hardware.c, head/firmware/main_proto.cpp, head/firmware/main_rev1.cpp, head/firmware/motor_hardware_common.c, head/simulator/main.cpp, include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, pipettes/core/configs.cpp, pipettes/firmware/motor_configurations.cpp, pipettes/firmware/motor_timer_hardware.c
We'd like to increase the microstep ratios for all the stepper-controlled axes to make motion smoother and quieter. However, this doubles the steps/mm value for each axis, and therefore lowers the maximum speed we can command - we can only issue a step once each interrupt. So, double the interrupt frequency to 200khz to keep the same maximum speed.
This must be tested alongside https://github.com/Opentrons/opentrons/pull/11598 . If that PR isn't being used, the motors will move half as fast as they should.
=> refactor: increase motor interrupt freqs and usteps

include/pipettes/core/gear_motor_tasks.hpp, include/pipettes/core/motor_configurations.hpp, pipettes/core/gear_motor_tasks.cpp, pipettes/firmware/motor_configurations.cpp, pipettes/firmware_l5/main.cpp, pipettes/firmware_l5/motor_configurations.cpp, pipettes/simulator/motor_configurations.cpp
All of the motors are now using the tmc2160 motor driver. I made an executive decision to no longer support the gear motors on the L5 boards for the 96 channel because it was getting to be gross to try and support both configurations.
We will only be using the old L5 proto board for plunger testing on the 96 channel.
=> refactor(pipettes): make all motors on the EVT 96 chan use the tmc2160

cmake/FindPoetry.cmake
Pulls latest changes from cmake-utils to enable host configuration on macOS. May require wiping out the `build-host` folder to reconfigure and build correctly.
=> chore(cmake): update for poetry fixes

head/tests/test_presence_sensing_driver.cpp, include/head/core/presence_sensing_driver.hpp, include/head/core/tasks/presence_sensing_driver_task.hpp
On [main](https://github.com/Opentrons/ot3-firmware) currently, a `tools_detected_notification` will appear when you attach an instrument. After taking off that instrument and sending an `attached_tools_request`, you'll still see the instrument that was previously attached.
This pr allows the detected tools to change following the removal of an instrument without sending an unnecessary `tools_detected_notification`.
=> change tools detected if nothing attached

gripper/firmware/interfaces_z_motor.cpp
The tmc2130 has a config register that enables an extra emergency_stop pin on the driver. for the gripper we re-worked the mcu board so that the e-stop line coming from the SoM board is routed to this pin instead of the motor-enable pin.
This has the effect of leaving the motor enabled when the e-stop is triggered but the motor driver no longer accepts any steps that are sent to it.
this means that during estop the gripper z motor won't fall straight into the deck and hold steady wherever it is.
The re-work also holds the motor enable pin to ground so the motor driver is always enabled
=> fix(gripper-motor): use the tmc2130 emergency stop pin to reflect new board change

common/simulation/CMakeLists.txt, common/tests/CMakeLists.txt, gripper/simulator/main.cpp, head/tests/CMakeLists.txt, i2c/tests/CMakeLists.txt, include/i2c/simulation/device.hpp, include/sensors/simulation/mmr920C04.hpp, include/sensors/simulation/mock_hardware.hpp, include/sensors/tests/mock_hardware.hpp, motor-control/tests/CMakeLists.txt, pipettes/simulator/main.cpp, pipettes/tests/CMakeLists.txt, sensors/tests/CMakeLists.txt, sensors/tests/test_capacitive_sensor.cpp, sensors/tests/test_environment_driver.cpp, sensors/tests/test_pressure_driver.cpp, sensors/tests/test_pressure_sensor.cpp, spi/simulation/spi.cpp, spi/tests/CMakeLists.txt, state_manager/CMakeLists.txt
There was a bit of shared code and dependencies between test and simulation targets that was causing trouble in another branch, primarily due to header generation from the state manager. This PR refactors the tests and simulation targets to try to separate some of those inter-dependencies.
This PR also adds a dependency in common-simulation to ensure the headers are always generated from state manager, and that the state-manager environment is always initialized before header generation.
=> refactor(tests): remove intedependencies between tests and simulations

common/simulation/CMakeLists.txt, gantry/simulator/interfaces.cpp, gripper/simulator/interfaces.cpp, gripper/simulator/main.cpp, head/simulator/main.cpp, include/common/simulation/state_manager.hpp, include/gripper/simulation/sim_interfaces.hpp, include/motor-control/simulation/sim_motor_hardware_iface.hpp, include/sensors/simulation/mock_hardware.hpp, pipettes/simulator/interfaces.cpp, pipettes/simulator/main.cpp
Adds support for the OT-3 firmware simulators to send messages to the state manager:
- When the motors are stepped (with the direction inferred from the last time the direction was set)
- When the sync pin is set 
- When reading the sync pin status
For now, every message sent to the state manager comes with a response, so the firmware must wait for that response in order to remain synchronized. This slows things down but will be modified in the future.
Was able to test this functionality through the following:
- Set up an OT3 emulator pulling the firmware from the latest commit on this branch
- Open a can-comm, set up a move group for an axis that will trigger a nonzero number of steps, and then start it
- Using a simple UDP python script, request the position of the aforementioned axis …
=> feat(simulators): add state manager messaging

pipettes/firmware/motor_configurations.cpp
For some reason I completely forgot to change the SPI GPIOs in the motor configurations file.... 🙃
=> fix(pipettes): fix SPI gpios for the 96 channel

include/motor-control/core/utils.hpp, include/sensors/core/fdc1004.hpp, include/sensors/core/mmr920C04.hpp, include/sensors/core/tasks/capacitive_sensor_callbacks.hpp, include/sensors/core/tasks/capacitive_sensor_task.hpp, include/sensors/core/tasks/environment_driver.hpp, sensors/tests/CMakeLists.txt, sensors/tests/test_capacitive_driver.cpp, sensors/tests/test_capacitive_sensor.cpp
There was a mismatch on how we were converting values in the capacitive sensor to fixed point. I
decided to match everything to a radix of 16, which is what the python is currently doing.
=> fix(sensors): fix a halving error in the capacitive sensor

include/sensors/core/fdc1004.hpp
There was a bug in the capacitive sensor driver related to masking the offset capacitance value. An offset of high enough pF would overflow into the CHB configuration field, effectively changing the channel being read to an invalid value and causing all future readings to be exactly the same. 
Before this fix, touching a capacitive sensor (or otherwise driving the capacitance high enough) would cause the sensor to latch onto a value indefinitely. After this fix, the sensor behaves properly.
=> fix(sensors): correctly mask capdac value

pipettes/firmware/stm32g4xx_it.c, pipettes/firmware/stm32g4xx_it.h, pipettes/firmware/utility_gpio.c
Had some incorrect interrupt names for the G4 board + 96 channel data ready line. The GPIO pin for one of the limit switches was also incorrect
=> refactor(pipettes): correct a few more bugs in the 96 channel firmware

include/sensors/core/fdc1004.hpp, include/sensors/core/tasks/capacitive_sensor_callbacks.hpp
Another fix for the capacitive sensor to prevent the IC from latching.
The threshold in firmware for rezeroing the capacitive sensor was far lower than it had to be given the range of the base readings. This seemed to be causing the capacitive sensor IC to crash when the capacitance changed too quickly, and the capacitance would get stuck at a negative value.
This was causing issues in a testing script to verify deck-finding. After this fix, the script can run fine and the data never latches up.
=> fix(sensors): increase capdac rezero threshold

include/sensors/core/hdc3020.hpp, include/sensors/core/tasks/environment_driver.hpp, include/sensors/core/tasks/environmental_sensor_task.hpp, include/sensors/simulation/hdc3020.hpp, sensors/tests/test_environment_driver.cpp, sensors/tests/test_environment_sensor.cpp
This PR adds a few fixes necessary to bring up the environmental sensor
* To read from the sensor, you first need to write the command for the autoread mode you want; then you read the data by writing to `AUTO_MEASURE_STATUS`, not the autoread mode setting register
* The polling frequency was 10Hz, which the datasheet claims can lead to internal heat buildup. 1Hz prevents this.
* The polling flags were not being read correctly, so if the host set the flags to sync _and_ report no data would be sent back
* When the host requested a single read, nothing was being sent back because data is only reported if the `report` flag is set
* The data coming back was being read in reverse order. The sensor sends back temperature and then humidity, but the firmware was reading in reverse order.
Tested …
=> fix(sensors): environmental sensor bringup

include/sensors/core/mmr920C04.hpp, include/sensors/core/tasks/pressure_driver.hpp, sensors/tests/test_pressure_driver.cpp
This PR fixes some issues with how the pressure sensor data was being read:
* Pressure data value of 0 is perfectly reasonable
* Pressure data was being read as an `int32_t` and then right shifted. This ends up not working correctly because it is a signed 24-bit value. Instead, we want to right shift it _as a uint32_t_ to preserve the signedness 
* The pressure was being converted to a float and then stored into a `uint32_t` which 1) clobbered the accuracy 2) prevented negative values from being stored.
=> fix(sensors): convert pressure data correctly

include/sensors/core/tasks/capacitive_sensor_callbacks.hpp
The capacitive sensor on the pipettes worked fine with recent changes, but the gripper sensors would lock up from time to time. We theorized that the issue was that our poller doesn't check the ready flag for the measurements, but I set up a branch to test that and it didn't help at all - one of the sensors still locked up from time to time.
The code for the capacitive sensors originally wrote to the FDC register _every_ time the offset changed. This is necessary on startup (to configure the sample rate and measurement channel), but it is unnecessary after initial startup. Modifying the code so that the FDC register does _not_ get written after initialization fixed the issue - running the code on a gripper and touching the sensors quickly used to cause them to lock up eventually, but now …
=> fix(sensors): only set FDC register once on startup

include/pipettes/core/sensor_tasks.hpp, pipettes/core/sensor_tasks.cpp, pipettes/core/sensor_tasks_g4.cpp, pipettes/firmware/main.cpp, pipettes/firmware_l5/main.cpp, pipettes/simulator/main.cpp
Closes RET-1280
The firmware was not set up to configure the right I2C bus for the pressure sensor on multichannel boards. This PR just adds that configuration. There is another pressure sensor on the other I2C bus, but it does not currently have the Data Ready line connected so it isn't usable until a sensor board revision.
Tested on a single-channel pipette:
* Flashed single-rev1 firmware and polled every sensor on the single-sensor board -> data came back fine
* Flashed multi-rev1 firmware and polled every sensor with a multi-sensor board attached -> data came back fine
=> fix(pipettes): use correct i2c bus for multichannel pressure sensor

include/sensors/simulation/hdc3020.hpp
Integration tests are failing (partly) due to the environment sensor register values being wrong. This corrects the values of the temperature and humidity registers. Requires a corresponding PR in the monorepo to pass integration tests.
=> fix(simulator): use correct register width for environment sensor

include/gripper/core/gripper_info.hpp
This allows us to parse the gripper id on the Python side so we can save the gripper offset during calibration.
=> fix(gripper): use a simpler serial

eeprom/tests/test_dev_data.cpp, eeprom/tests/test_eeprom_task.cpp, eeprom/tests/test_hardware_iface.cpp, gripper/firmware/main_rev1.cpp, include/eeprom/core/hardware_iface.hpp, include/eeprom/core/task.hpp, include/eeprom/core/types.hpp, include/eeprom/simulation/eeprom.hpp, pipettes/core/sensor_tasks_g4.cpp, pipettes/firmware/main.cpp
Both the gripper and 96 channel require a different eeprom chip due to i2c address collisions. See #RET-1284.
=> feat(all): support new eeprom chip for gripper and 96 channel

bootloader/firmware/stm32G4/stm32g4xx_hal_conf.h, bootloader/firmware/stm32G4/system_stm32g4xx.c, gantry/firmware/stm32g4xx_hal_conf.h, gantry/firmware/system_stm32g4xx.c, gripper/firmware/stm32g4xx_hal_conf.h, gripper/firmware/system_stm32g4xx.c, head/firmware/stm32g4xx_hal_conf.h, head/firmware/system_stm32g4xx.c, pipettes/firmware/stm32g4xx_hal_conf.h, pipettes/firmware/system_stm32g4xx.c
Since the external oscilator is the same frequency as the internal oscilator, we should be able to use the same clock divisors.
=> refactor(all): use the external oscillator for the system clock

pipettes/firmware/motor_configurations.cpp
The active setting of the direction pin is flipped for the 96 channel
=> refactor(pipettes): modify direction pin for 96 channel plunger

bootloader/tests/test_message_handler.cpp, bootloader/tests/test_messages.cpp, include/bootloader/core/messages.h
the HAl code skips sizes from 48 to 64. and defaults to size=64 when its not one of the defined values in length_from_hal in bootloader/core/utils.c
so this sets the size back to 64 and adjusts the tests accordingly
=> fix(bootloader) account for the fact that the bootloader is unable to read messages of size 60

pipettes/firmware/i2c_setup.c
Missed a place to change the enable write pin. Tested on a 96 channel prototype.
=> fix(pipettes): 96 channel enable write pin was using the wrong gpio

pipettes/firmware/motor_timer_hardware.c
The 96 channel has two timer interrupts to control the 3 stepper motors in the system. The plunger motor timer frequency was bumped up to match the motor frequencies in the rest of the robot system, but the gear motor wasn't changed to accomodate this. As a result, the firmware application was getting overloaded and crashing when both timers were enabled. Hopefully in January we'll be able to do a full study of the system (including freertos tasks/interrupts etc) to figure out where we can better optimize our system.
=> fix(pipettes): make pick up motor timer half the time of the plunger motor

include/motor-control/core/stall_check.hpp, motor-control/core/CMakeLists.txt, motor-control/core/stall_check.cpp, motor-control/tests/CMakeLists.txt, motor-control/tests/test_stall_check.cpp
This PR adds a class for checking the stall status of a stepper motor. The class is not integrated into the motor interrupt in this PR, it is just tested with CI.
Given the ratio of steps : µm for both the encoder and the stepper (using any microstepping ratio), the class keeps a running count of the position of the stepper motor vs the expected position of the encoder. The functions that are expected to be called from interrupts specifically avoid using any floating-point math or any multiplication in an effort to keep their overhead low.
The StallCheck object is set to be able to work with axes without encoders by just never indicating a bad status.
=> feat(motor-control): add StallCheck class

generate_header.py, include/bootloader/core/ids.h, include/can/core/ids.hpp, include/can/core/messages.hpp, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, include/motor-control/core/tasks/messages.hpp, include/motor-control/core/tasks/move_status_reporter_task.hpp, motor-control/tests/test_brushed_motor_interrupt_handler.cpp, motor-control/tests/test_limit_switch.cpp, motor-control/tests/test_motor_pulse.cpp, motor-control/tests/test_sync_handling.cpp
[RET-1250](https://opentrons.atlassian.net/browse/RET-1250) firmware side work
Allows the motor controller to respond to moves with an error message in addition to the ack
=> feature(motor-control): add error message to move response varient

.github/workflows/eeprom.yaml, .github/workflows/gantry.yaml, .github/workflows/gripper.yaml, .github/workflows/head.yaml, .github/workflows/pipettes.yaml
the Debug builds are too big for some proto boards so build as RelWithDebInfo instead
=> chore(.github): change cross compile builds to RelWithDebInfo

can/tests/test_messages.cpp, include/can/core/messages.hpp
When #507 added the message index to the MotorPositionResponse message, the serialization was not updated correctly and therefore the hardware controller can never get the response.
Tested that this change lets the can_comm and can_mon scripts receive the MotorPositionResponse
=> fix(can): fix motor-position-response serialization

gantry/firmware/interfaces_proto.cpp, gantry/firmware/interfaces_rev1.cpp, gantry/simulator/interfaces.cpp, gripper/firmware/interfaces_z_motor.cpp, gripper/simulator/interfaces.cpp, head/firmware/main_proto.cpp, head/firmware/main_rev1.cpp, head/simulator/main.cpp, include/gantry/core/utils.hpp, include/head/core/utils.hpp, include/motor-control/core/stall_check.hpp, include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, include/pipettes/core/configs.hpp, include/pipettes/firmware/interfaces.hpp, include/pipettes/firmware/interfaces_g4.hpp, include/pipettes/simulator/interfaces.hpp, motor-control/core/stall_check.cpp, motor-control/tests/test_limit_switch.cpp, motor-control/tests/test_motor_interrupt_queue.cpp, motor-control/tests/test_motor_pulse.cpp, motor-control/tests/test_sync_handling.cpp, pipettes/firmware/interfaces.cpp, pipettes/firmware/main.cpp, pipettes/firmware_l5/interfaces.cpp, pipettes/firmware_l5/main.cpp, pipettes/simulator/interfaces.cpp, pipettes/simulator/main.cpp
This PR adds support for stall detection in the ISR for stepper motors. The stall threshold is set to 500µm on every axis for now, which seems to work from basic testing. The stall check is only run when the stepper motor travels the distance of the stall threshold (i.e. 500µm on any encoder-enabled axes), and is never executed for an axis with no encoder.
Tested on the X, Y, and Z-L axes of an OT-3 by verifying that, if an axis stalls out at its end of travel, the flag for `stepper_position_ok` gets cleared. It is only reenabled if the axis is homed.
=> feat(motor-control): stall detection in stepper ISR

include/bootloader/core/ids.h, include/can/core/ids.hpp, include/can/core/message_handlers/motor.hpp, include/can/core/messages.hpp, include/gripper/core/can_task.hpp, include/motor-control/core/brushed_motor/driver_interface.hpp, include/motor-control/core/tasks/brushed_motor_driver_task.hpp, include/motor-control/core/tasks/messages.hpp, include/motor-control/firmware/brushed_motor/driver_hardware.hpp, include/motor-control/simulation/sim_motor_driver_hardware_iface.hpp, include/motor-control/tests/mock_brushed_motor_components.hpp
This PR allows us to read the current duty cycle and the vref of the brushed motor via CAN.
=> feat(motor-control): read brushed motor driver config

pipettes/firmware/main.cpp, pipettes/firmware/motor_configurations.cpp
Previously the `sync_in` pin assignment was under `SensorHardwareConfiguration`. Moving it to `HardwareConfig` lets the firmware read the correct pin and therefore move with the sync line as a stop condition.
=> fix(pipettes): add sync_in to pipette motor configs

can/tests/test_messages.cpp, include/can/core/messages.hpp, include/pipettes/core/tasks/gear_move_status_reporter_task.hpp
The TipActionResponse was missing a few attributes in the message which caused it to fail unpacking the response on the python side.
=> fix(pipettes): add position flags and action type to TipActionResponse

gripper/firmware/interfaces_z_motor.cpp
We've added a brake to the z-motor, so we don't need to engage the motor at boot anymore.
=> fix(gripper): do not engage z-motor at boot

state_manager/pyproject.toml
There are certain files the state manager accesses which is now dependent on shared-data so it needs to be added to the toml file.
=> fix(state-manager): add shared data to the state manager

.github/workflows/codecov.yaml
Coverage wasn't being generated on the main branch because the codecov action was configured to run on pushes to `edge`, but this repository uses `main`.
=> fix(coverage): run coverage on pushes to main

include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, motor-control/tests/test_motor_interrupt_handler.cpp, motor-control/tests/test_motor_interrupt_queue.cpp
When an `UpdateMotorPositionEstimationRequest` command is handled, it approximates the _unsigned_ stepper motor position from the _signed_ encoder position. This means a negative encoder value will result in an underflow of the motor position, which is Very Incorrect. This PR just adds handling to reset the encoder value back to 0 if such a situation arises.
In all of the testing I've done, the encoder value never goes very significantly below 0 - usually 1 or 2 steps. Since the motor controller will never explicitly try to go below the 0 point (as defined by the home switch), in practice the encoder does not go significantly under 0. Therefore, the approach in this PR is just to reset the encoder to 0 if it's below that level, and then estimate the stepper from there (in effect setting …
=> fix(motor-control): motor position estimation when encoder is below zero

include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, include/motor-control/simulation/motor_interrupt_driver.hpp, include/pipettes/firmware/interfaces.hpp, include/pipettes/firmware/interfaces_g4.hpp, include/pipettes/simulator/interfaces.hpp, motor-control/tests/test_limit_switch.cpp, motor-control/tests/test_motor_interrupt_handler.cpp, motor-control/tests/test_motor_pulse.cpp, motor-control/tests/test_sync_handling.cpp
In our ongoing quest to reduce the overhead of the motor interrupts, virtual calls seems like a good target. By adding a template parameter for the type used for the motor hardware in the stepper interrupt, the compiler is now able to optimize out some virtual hardware calls.
I tested that this at least doesn't slow down the interrupts by running it on a Head unit, but I didn't quantify the difference. However, I checked the disassembly with `objdump` and gcc is definitely calling the hardware functions directly (and was using virtual calls before), so I'm 99% confident that this is an improvement (even if it's only marginal).
There are other places we could do the same thing with a bit more work, but this was pretty low-hanging fruit.
=> refactor(motor-control): parameterize motor hardware in stepper interrupt

gantry/firmware/interfaces_proto.cpp, gantry/firmware/interfaces_rev1.cpp, gantry/simulator/interfaces.cpp, head/firmware/main_proto.cpp, head/firmware/main_rev1.cpp, head/simulator/main.cpp, include/gantry/core/utils.hpp, include/head/core/utils.hpp, include/pipettes/core/configs.hpp, pipettes/firmware/main.cpp, pipettes/firmware_l5/main.cpp, pipettes/simulator/main.cpp
Per discussions with hardware, we want the default stall threshold for the motors to always be 0.5mm. This has the nice side effect of making the initialization code look really clean and simple.
=> feat(motor-control): update all stall thresholds to 0.5mm

include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp
When updating the position estimation, we weren't updating the stall checker. This was fine if the position of the encoder and motor accumulator were already within the stall threshold, but if an actual stall happened then the next movement would immediately cause a stall. Oops!
=> fix(motor-control): update stall checker when updating position estimation

gantry/firmware/utility_gpio.c
=> fix(gantry): initialize estop GPIO pin correctly

gripper/firmware/interfaces_grip_motor.cpp
Update gripper jaw motor reference voltage and max duty cycle based on [gripper tuning results](https://docs.google.com/presentation/d/1Kuc0oXqTgO0FE_G5YqW_9KY8MkJ1SdFq3aVmZUNStyQ/edit#slide=id.g1c51a215cf4_0_133).
=> fix(gripper): update vref & cap max PWM to 60

head/firmware/utility_hardware.c, pipettes/firmware/utility_gpio.c, pipettes/firmware_l5/utility_gpio.c
Missed changing the clock when I corrected the Pins for some boards in the other PR
=> fix(head, pipettes): use the correct gpio clock for estop pin

head/firmware/main_rev1.cpp
The 96 channel is extremely heavy. We have the ebrake to prevent the pipette from falling when the robot is off, however immediately on boot of the system the pipette starts falling. This means that we will need to enable the Z motor on boot. I decided to just enable both motors to make the behavior the same, but I am fine with only doing the mount that matters as well.
=> refactor(head): enable motors on boot

can/tests/test_messages.cpp, generate_header.py, include/bootloader/core/ids.h, include/can/core/ids.hpp, include/can/core/messages.hpp, include/motor-control/core/motor_messages.hpp, include/motor-control/core/stepper_motor/motion_controller.hpp, include/pipettes/core/dispatch_builder.hpp, include/pipettes/core/tasks/gear_move_status_reporter_task.hpp, include/pipettes/core/tasks/message_handlers/motion.hpp, include/pipettes/core/tasks/messages.hpp, pipettes/core/gear_motor_tasks.cpp, pipettes/firmware/interfaces.cpp, pipettes/firmware_l5/interfaces.cpp, pipettes/simulator/interfaces.cpp, pipettes/tests/CMakeLists.txt, pipettes/tests/test_gear_move_status_handling.cpp
Previously, the gear move and motion tasks were both looking for TipActionRequests on the CAN dispatcher. This meant that any time you sent a tip action request, it would send back four responses rather than two responses.
In addition, I added a "GearMotorId" to help determine which motor is sending back the response. Required changes on the python side can be found [here](https://github.com/Opentrons/opentrons/pull/12018).
See RLIQ-295 for more information.
=> refactor(pipettes): Only monitor for a TipActionRequest in the move motor task and add a motor id

gantry/firmware/interfaces_proto.cpp, gantry/firmware/interfaces_rev1.cpp, gantry/simulator/interfaces.cpp, gantry/tests/test_linear_motion_config.cpp, gripper/firmware/interfaces_grip_motor.cpp, gripper/firmware/interfaces_z_motor.cpp, gripper/simulator/interfaces.cpp, gripper/tests/test_linear_motion_config.cpp, head/firmware/main_proto.cpp, head/firmware/main_rev1.cpp, head/simulator/main.cpp, include/motor-control/core/linear_motion_system.hpp, include/motor-control/core/stepper_motor/motion_controller.hpp, motor-control/tests/test_brushed_motor_interrupt_handler.cpp, motor-control/tests/test_linear_motion_config.cpp, motor-control/tests/test_move_status_handling.cpp, pipettes/core/configs.cpp, pipettes/firmware/interfaces.cpp, pipettes/firmware/main.cpp, pipettes/firmware/motor_configurations.cpp, pipettes/firmware_l5/main.cpp, pipettes/simulator/main.cpp
The steps per mm calculation was slightly off for the tip motors. This is because we have been using two different types of gear ratios -- the gear reduction ratio and the regular gear ratio. The regular gear ratio is `driving gear teeth / driven gear teeth` whereas the reduction ratio is `larger teeth / smaller teeth`.
The current way we do the calculations worked out OK for the gripper motor because the reduction ratio is the inverse of the regular gear ratio (since the larger gear motor is the driven gear). However, logically, it makes a bit more sense to multiple these gear ratios by the leadscrew pitch (which represents mm per rev) because gear trains affect the mm per rev. 
In addition, when we changed the motor drivers for the tip motors to use tmc2160s, we did not change the …
=> refactor(all): Modify calculation for usteps per mm and update microstepping to 1/16th for tip motors

can/tests/test_messages.cpp, include/bootloader/core/ids.h, include/can/core/ids.hpp, pipettes/tests/test_gear_move_status_handling.cpp
I had a slight misunderstanding with how the clamp motors + adapters were supposed to interact with each other. Decided to rename the tip actions to be more in line with the actions that will actually happen on the robot.
=> refactor(pipettes): rename tip actions to align with their purposes

include/can/core/ids.hpp, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, motor-control/tests/test_sync_handling.cpp
Before this, the moves created in the liquid sensing code used `MoveStopCondition.cap_sensor` to check the sync line during motion. Since there's no reason to differentiate between the two sensors for the purpose of the `MoveStopCondition` enum, both sensors will use the same condition, which will now be called `sync_line`.
- changed `MoveStopCondition.cap_sensor` to `MoveStopCondition.sync_line`
- combined `sync_triggered()` and `calibration_stopped()` to make naming a little less redundant
- moved sync line check out of nested `if` to appease the linter
=> refactor(motor-control): rename cap_sensor stop condition to sync_line

head/firmware/main_rev1.cpp
On DVT, there are only three gears, and the net reduction ratio is now 3.2 instead of 4.
Closes RET-1315
=> refactor(head): set dvt gearing

pipettes/firmware/main.cpp
We will not have a fix for the noise on the data ready line of the 96 channel until DVT. To make testing easier, we should just disable this in main until then.
=> refactor(pipettes): disable the pressure sensor interrupt for the 96 channel

CMakeLists.txt
Added a cmake policy set that is only valid on >=3.24, so gate it on >= 3.24.
=> fix(build): version-gate cmake policy

CMakePresets.json, scripts/subsystem_versions.py
Now that we have the capability to build all the electrical revisions, we need to deliver them to the built system images. This PR does that and a couple other little refactors:
- Alter `subsystem_versions.py` to look for hex files in the `dist/applications` directory that `cmake --install` will populate, which means we don't have to worry about image.hex files getting in there; also dynamically pick up subsystems
- Make some changes to make OE's job a little easier, such as: bump the minimum required version, to bump the preset version, to allow configure presets without binary dirs, to let OE specify a build directory in _OE's_ build directory, and do some other nice little changes
=> refactor: deliver all firmware revisions to OE

state_manager/CMakeLists.txt
Poetry is dying in CI because of [this issue](https://github.com/python-poetry/poetry/issues/7184). Workaround is to add `--no-ansi` flag. 
Dumb. But it works.
=> chore: Add --no-ansi flag when running poetry

CMakeLists.txt, CMakePresets.json, README.md, scripts/subsystem_versions.py
This builds a manifest.json locally in the script instead of relying on openembedded to do it. It also builds it into cmake --install, so instead of having to run the script separately it will just get run when you run that.
We should merge https://github.com/Opentrons/oe-core/pull/55 before/around when we merge this
=> refactor: build manifest and hook in install

include/rear-panel/core/bin_msg_ids.hpp, include/rear-panel/core/binary_parse.hpp, include/rear-panel/core/messages.hpp, include/rear-panel/core/queues.hpp, include/rear-panel/core/tasks.hpp, include/rear-panel/core/tasks/host_comms_task.hpp, include/rear-panel/core/tasks/system_task.hpp, include/rear-panel/firmware/system_hardware.h, rear-panel/core/CMakeLists.txt, rear-panel/core/queues.cpp, rear-panel/core/tasks.cpp, rear-panel/firmware/CMakeLists.txt, rear-panel/firmware/host_comms_task/freertos_comms_task.cpp, rear-panel/firmware/system_hardware.c, rear-panel/test/test_messages.cpp
create a freertos task to handle system tasks and add a c file that disables peripherals and jumps to the bootloader
`
>>> import subprocess
>>> import time
>>> try:
...     ser = serial.Serial("/dev/ttyACM0",115200)
...     ser.write(bytes.fromhex("00050000"))
...     data = ser.read(size=5)
...     print(data)
...     ser.close() 
... except Exception as e:
...     print(e)
... 
4
[58096.797118] usb 1-1.1: USB disconnect, device number 22
read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
>>> time.sleep(0.5)
[58097.047217] usb 1-1.1: new full-speed USB device number 23 using ci_hdrc
>>> 
>>> output = subprocess.run(["lsusb"], capture_output=True)
>>> success =(output.stdout.find(b"DFU")) > 0 
>>> print("Device in dfu mode …
=> feat(rear-panel):  add an enter bootloader message to the rear panel mcu

include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, motor-control/tests/test_motor_interrupt_queue.cpp
During stall repeatability testing, we noticed that motor axes would sometimes continue to drive into the endstop after stalling. The culprit appears to be that, when the Stop message was removed in #542, there was no replacement for clearing out the interrupt's queue.
This PR adds functionality to the interrupt handler to clear out its queue when a stall occurs. We've previously had trouble using the actual `clear` function for FreeRTOS queues in interrupts, so instead we set a flag to "drain" the queue (one message per interrupt) until it's empty.
Tested by:
* Move an axis very close to its endstop
* Command the axis to move through the endstop with the `_check_stalls` flag enabled. Make the distance at least twice that of the distance to the endstop, to ensure it will collide during …
=> fix(motor-control): clear move group after stall

include/bootloader/core/ids.h, include/can/core/ids.hpp
Changes are created by the header generator — seems like we forgot to edit the enum in bootloader after updating the `can/core/ids.hpp`.
=> fix(bootloader): update move stop condition enum name

include/bootloader/core/ids.h, include/can/core/ids.hpp, include/can/core/messages.hpp
This pr just adds a `BaselineSensorRespone` message. This is intended to replace the stream of `ReadFromSensorResponse` messages in the case of auto-zeroing. However, we do want to keep limited polling available for testing and dev purposes, so some additional firmware to differentiate between that and production auto-zeroing may be in order for the sensors.
=> feat(pipettes): add baseline sensor response

gripper/firmware/main_proto.cpp, gripper/firmware/main_rev1.cpp, include/sensors/core/sensor_hardware_interface.hpp, include/sensors/firmware/sensor_hardware.hpp, include/sensors/simulation/mock_hardware.hpp, include/sensors/tests/mock_hardware.hpp, pipettes/firmware/main.cpp, pipettes/firmware/motor_configurations.cpp, pipettes/firmware_l5/main.cpp, pipettes/firmware_l5/motor_configurations.cpp
Tip sensing falls more under the category of general sensor hardware. The pin configurations are also more conducive to having "multiples" of the tip sense. The next bit of work will involve setting up a task that can fire off tip presence data once a state change has been detected.
Some notes for next steps. For single/eight channel the ejector stage flag is active when in 'resting' position. For ninety-six the ejector stage flag is inactive when in 'resting' position.
The ninety six channel tip presence routine will be much more involved than the single/eight because it involves moving the pick up motors slightly 😞
=> feat(pipettes): add tip sense check to the sensor hardware class

.github/workflows/start-ot3-build.yaml
This workflow should hook into the same mechanics that do builds for the monorepo and cause ot3 builds on pushes to main and pull requests that are labeled with 'ot3-build'.
=> build: add workflow for ot3 builds

gripper/firmware/interfaces_grip_motor.cpp, gripper/simulator/interfaces.cpp, include/bootloader/core/ids.h, include/can/core/ids.hpp, include/can/core/message_handlers/motion.hpp, include/can/core/messages.hpp, include/gripper/core/can_task.hpp, include/motor-control/core/brushed_motor/brushed_motion_controller.hpp, include/motor-control/core/brushed_motor/brushed_motor.hpp, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, include/motor-control/core/brushed_motor/error_tolerance_config.hpp, include/motor-control/core/tasks/brushed_motion_controller_task.hpp, include/motor-control/core/tasks/messages.hpp, include/motor-control/tests/mock_brushed_motor_components.hpp, motor-control/tests/CMakeLists.txt, motor-control/tests/test_brushed_motor_error_tolerance_handling.cpp, motor-control/tests/test_brushed_motor_interrupt_handler.cpp
**Changes:**
* New CAN message to change the gripper jaw error tolerance. 
* Added a new class `BrushedMotorErrorTolerance` to keep the tolerance values.
* The message is handled by the motion controller task which modifies the tolerance values in `BrushedMotorErrorTolerance`.
=> feat(gripper): make gripper jaw error tolerance adjustable

include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, motor-control/tests/test_motor_interrupt_handler.cpp
The motor controller would send an error if it was executing a move and an estop happened; but if it estop was asserted and it got new moves, it just wouldn't ever execute them. That means that anything that was waiting on those moves would have to wait for some timeout, which in the problematic case of the robot server starting while estop is asserted would be forever for home moves.
This commit extends the behavior of "nak the first move and blackhole the rest" to moves that come in while estop is asserted, which should raise an error in the host side. The host side will have to be fixed to handle such errors and still start up instead of exploding.
Ideally this would happen on the execute command, but then it wouldn't be the same as how it works for moves during estop assertion and …
=> motor-control: errors for moves during estop

gripper/firmware/interfaces_grip_motor.cpp, gripper/firmware/interfaces_z_motor.cpp, gripper/firmware/main_rev1.cpp, gripper/firmware/motor_hardware.h, gripper/firmware/motor_hardware_g.c, gripper/firmware/motor_hardware_shared.c, gripper/firmware/motor_hardware_z.c, gripper/firmware/utility_gpio.c, include/gripper/firmware/utility_gpio.h
Was testing on the bench setup and found a few issues with the C1 version of the firmware,
- motor driver setting flag we don't need anymore needed to be cleared so the motor could move
* old flag was a hack to get the z motor not to fall down when motor disabled
- add a common gpio pin define since they didn't match in different parts of the code
* there was a mismatch since we used the GPIO_PIN_* in differed places
- remove an IRQ setup since we don't have downstream timers for the Z motor encoder
*caused a crash when encoder was conencted
Bench setup was tested with the following
all z motor hardware connected and talking via can
called home via ot3repl and saw z motor moving
used limit switch to complete home
moved it relative in ot3repl
=> fix(gripper): collection of fixes found during bringup

include/can/core/messages.hpp, include/sensors/core/tasks/capacitive_sensor_task.hpp, include/sensors/core/tasks/environmental_sensor_task.hpp, include/sensors/core/tasks/pressure_driver.hpp, include/sensors/core/tasks/pressure_sensor_task.hpp, sensors/tests/test_pressure_driver.cpp
Unlike the capacitive sensor, the pressure sensor does not have built-in auto-zeroing functionality. This pr allows `pressure_driver.hpp` to take a baseline reading of the ambient pressure by averaging together a number of samples specified in a `BaselineSensorRequest`. 
The threshold value will still act as an absolute threshold, but will now be compared to the difference between a given pressure reading and the averaged baseline pressure. 
In addition, after finishing calculating a baseline pressure, the pressure driver will send a `BaselineSensorResponse` with the average offset it's found.
=> feat(pipettes): add auto-zeroing for pressure sensor

.github/workflows/rear_panel.yaml, rear-panel/CMakeLists.txt, rear-panel/test/CMakeLists.txt
Adding a CI workflow and some other little changes
* Added a github workflow configuration to build + test the rear panel on pushes/PR's
* Fixed the format target (was not working)
* Changed name of the `build-and-test` target to prefix with `rear-panel` instead of `rear_panel`
=> chore(rear-panel): add CI workflow

include/can/core/messages.hpp, include/pipettes/core/sensor_tasks.hpp, include/sensors/core/tasks/tip_presence_notification_task.hpp, include/sensors/core/utils.hpp, pipettes/core/sensor_tasks_g4.cpp, pipettes/firmware/hardware_config.c, pipettes/firmware/hardware_config.h, pipettes/firmware/main.cpp, pipettes/firmware/stm32g4xx_it.c, pipettes/firmware/stm32g4xx_it.h, pipettes/firmware/utility_gpio.c
Now that we have a hardware interrupt available for the tip ejector photointerrupter, we should use
that information to notify freertos to send a CAN notification that the status has changed.
Currently, I am only handling one sensor right now but I will support the 96 channel in a follow-up.
=> feat(pipettes): support tip ejector notification messages

include/can/core/messages.hpp, include/pipettes/core/sensor_tasks.hpp, include/sensors/core/tasks/tip_presence_notification_task.hpp, include/sensors/core/utils.hpp, pipettes/core/sensor_tasks_g4.cpp, pipettes/firmware/hardware_config.c, pipettes/firmware/hardware_config.h, pipettes/firmware/main.cpp, pipettes/firmware/stm32g4xx_it.c, pipettes/firmware/stm32g4xx_it.h, pipettes/firmware/utility_gpio.c
We want to decide that a tip has been detected based on an EXTI interrupt. This PR adds the piping in HAL to support an EXTI interrupt. While making these changes, I also edited the code on the pressure sensor to support two data ready lines for the 96 channel. We'll also want to do this for DVT 8 channel pipettes since there are now two separate data ready lines.
=> feat(pipettes): add GPIO EXTI interrupt support for the tip sense GPIOs

CMakeLists.txt, generate_header.py, header_generation_utils/header_generation_utils/utils.py, include/rear-panel/core/bin_msg_ids.hpp, include/rear-panel/core/binary_parse.hpp, include/rear-panel/core/messages.hpp, rear-panel/firmware/host_comms_task/freertos_comms_task.cpp, rear-panel/test/test_messages.cpp
Adds the rear-panel binary message protocol to the `generate_headers.py` script and integrates it with cmake workflows. Also generated the header and fixed references to it in code.
Also fixed a little issue where the autogen script was adding an extra newline that the formatter doesn't like.
=> build(rear-panel): autogenerate comm protocol constants

.github/workflows/release_bundle.yaml, .github/workflows/start-ot3-build.yaml
It will add artifacts to the releases and autogenerate some changelogs also.
Here's an example of a release created by this workflow: https://github.com/Opentrons/ot3-firmware/releases/tag/untagged-3121c9b9dc94a5ac5aee
It will stay as a draft until somebody clicks release, but will automatically get the release artifacts uploaded to it.
=> build: add a workflow to make gh releases from tags

pipettes/firmware/main.cpp
We do not have filtering on the data ready line and thus the pressure sensor can be noisy. This causes issues with auto-calibration and so for now we should disable the pressure sensor.
=> chore(pipettes): disable the primary pressure sensor for C2 pipette revisions

gripper/firmware/motor_hardware_shared.c, gripper/firmware/motor_hardware_z.c, gripper/firmware/stm32g4xx_it.c, gripper/firmware/stm32g4xx_it.h
During initial DVT gripper testing, @ryanthecoder and I saw that the z encoder wasn't behaving correctly.
We found out that (1) encoder timer interrupt was not added, and the (2) encoder direction was flipped. This PR fixes the issues we saw on the Z motor.
=> fix(gripper): add encoder timer interrupt handler & fix encoder dir

generate_header.py, include/rear-panel/core/bin_msg_ids.hpp, include/rear-panel/core/lights/animation_handler.hpp, include/rear-panel/core/lights/animation_math.hpp, include/rear-panel/core/lights/animation_queue.hpp, rear-panel/core/CMakeLists.txt, rear-panel/core/lights/animation_math.cpp, rear-panel/test/CMakeLists.txt, rear-panel/test/test_light_animation.cpp
This PR adds in an AnimationHandler class that is responsible for handling rear panel light animations. The AnimationHandler is backed by an AnimationBuffer (a double-buffered array) which stores a series of individual "actions". Each action contains:
- A color to transition to
- A transition type
- Instant will instantly change the color and then hold at it for the remainder of the step
- Linear will just change the color linearly over time from the previous setting to the new setting
- Sinusoid will transition in a smoother, pulse-like fashion between the previous color and the new color
- A transition time, which is the amount of time in milliseconds that this step should take
The double buffer is utilized to provide an "active" queue, for the animation that is currently running; and a …
=> feat(rear-panel): light action handler

.github/workflows/release_bundle.yaml
The previous file only installed .hex files but we also want the rear panel's .bin file and the manifest .json file.
with this new workflow you can download the application artifact and unzip it into your ot3firmware repo and push it onto the bot with <code>./push [IP] --no-build</code>
=> chore: add rear panel and manifest to application artifact

include/rear-panel/core/bin_msg_ids.hpp, include/rear-panel/core/lights/animation_handler.hpp, include/rear-panel/core/lights/animation_queue.hpp, include/rear-panel/core/messages.hpp, include/rear-panel/core/tasks/host_comms_task.hpp, include/rear-panel/core/tasks/light_control_task.hpp, rear-panel/core/queues.cpp, rear-panel/core/tasks.cpp, rear-panel/firmware/freertos_idle_timer_task.cpp, rear-panel/test/test_messages.cpp
This PR adds three commands for interacting with the light strip on the rear panel:
- A command to add a step to the animation in the staging queue
- A command to clear the staging queue
- A command to start running the animation in the staging queue
An `AnimationHandler` is added to the light control task's message handler, and it is used as the source of the color values when the periodic update message is parsed. 
Tested on an OT-3 with https://github.com/Opentrons/opentrons/pull/12350 using the `usb_comm` script. Uploading a series of actions and then running an animation will, in fact, run that animation.
Other misc stuff
- Bumped up the stack size of the idle task and the timer task; I was getting overflows from them and this fixed it.
- Added a handler to enable using the FreeRTOS …
=> feat(rear-panel): add light strip commands

include/rear-panel/core/bin_msg_ids.hpp, include/rear-panel/core/messages.hpp, include/rear-panel/core/tasks/host_comms_task.hpp, include/rear-panel/core/tasks/light_control_task.hpp, rear-panel/firmware/host_comms_task/freertos_comms_task.cpp, rear-panel/test/test_messages.cpp
Adds messages to control the deck lights, and adds handling in the host & light tasks to process them.
Also moved `rear_panel_parser` to be statically defined in a source file & updated tests to match.
Tested with [monorepo PR](https://github.com/Opentrons/opentrons/pull/12359) and was able to set the deck lights on & off, and get the status correctly.
=> feat(rear-panel): add deck light messages

pipettes/core/sensor_tasks_g4.cpp, pipettes/firmware/hardware_config.c, pipettes/firmware/utility_configurations.cpp, pipettes/firmware/utility_gpio.c
We are using the convention of "primary" and "secondary" to refer to multiple sensors of the same type. The primary channel should generally refer to the "A1" version of the pipette. The eight channel has a flipped "primary" bus for the pressure sensor.
=> fix(pipettes): switch the i2c bus of the pressure sensor to match primary and secondary conventions

pipettes/firmware/main.cpp
I previously thought calling `.value()` on an optional parameter meant that it would either return a nullptr or the object it was supposed to store. Mais **non**, I was wrong and therefore we have to do this gross check to make sure we don't brick pipette firmware. If anyone has any elegant solutions, definitely let me know.
We should be OK to not include this in the internal release b/c the breaking change was merged in after we cut the v4 tag.
=> fix(pipettes): ensure that secondary hardware exists before trying to access the value

bootloader/core/CMakeLists.txt, bootloader/core/message_handler.c, bootloader/core/pipette_node_id.c, bootloader/firmware/stm32G4/CMakeLists.txt, bootloader/firmware/stm32G4/node_id_stm32g4xx.c, bootloader/firmware/stm32G4/pipette_handle_messages.c, bootloader/tests/test_message_handler.cpp, can/tests/test_messages.cpp, common/core/revision.c.in, generate_header.py, include/bootloader/core/ids.h, include/bootloader/core/message_handler.h, include/bootloader/core/node_id.h, include/bootloader/core/system_specific_message_handlers.h, include/can/core/ids.hpp, include/can/core/message_handlers/system.hpp, include/can/core/messages.hpp, include/common/core/version.h, include/rear-panel/core/messages.hpp, pipettes/core/can_task_high_throughput.cpp, pipettes/core/can_task_low_throughput.cpp, rear-panel/test/test_messages.cpp
The bootlaoder has no way to indicate what kind of pipette it is. This means that if a pipette is stuck in its bootloader, it cannot be automatically and safely updated.
To fix this, let's add a new byte to the device info and put the pipette type in it (for a pipette, anyway). The byte will be interpreted differently depending on the canbus node id that the device info response comes from, so there's no need for a ton of space here.
This is implemented in the bootloader with another attribute-weak hook that will only get compiled for the pipette itself. While I was here, I refactored the way we do node IDs to make things a little better.
Closes RQA-584
This is a bootloader change! We need to test it on lots of kinds of devices.
We also need to add handling for this byte to the python …
=> fix(bootloader): present pipette information

bootloader/firmware/stm32G4/pipette_handle_messages.c
On the pipettes, we don't reliably detect that we're on the right mount when we go from bootloader to application. This is because it's too fast. So let's slow it down. By reconfiguring the mount detect pin to tristate and adding a delay after that before going to the app, we make it reliable again.
=> fix(bootloader): delay before app start on pipette

include/rear-panel/core/messages.hpp, rear-panel/test/test_messages.cpp
Missed a test failure that had a real bug! The raw iterator manipulation does not correctly handle the case where we're out of space in our write buffer.
=> fix(rear-panel): incorrect limiting of msg size

bootloader/firmware/stm32G4/node_id_stm32g4xx.c, bootloader/firmware/stm32G4/pipette_handle_messages.c, pipettes/firmware/main.cpp, pipettes/firmware/utility_gpio.c
The mount ID for the right mount wasn't working properly in all electrical cases:
- Booting the robot while pipette plugged in
- Bootloader->application
This fixes the issue by moving to a 100ms startup delay between configuring the mount ID as an input, and reading/writing it. That's in both the application and the bootloader, and works under EE testing.
=> fix(pipettes): mount id and bootloader

include/rear-panel/core/tasks/light_control_task.hpp
Enables the deck light on startup, as requested by the hardware team.
=> feat(rear-panel): enable deck light on startup

gripper/core/tasks.cpp
We've switched the cap sensor IDs for the gripper but we forgot to also update the sensor id on the sensor task, so it's reporting the wrong sensor id.
=> fix(gripper): update sensor id for sensor tasks

eeprom/tests/test_dev_data.cpp, include/eeprom/core/dev_data.hpp, include/eeprom/core/hardware_iface.hpp, include/eeprom/core/messages.hpp, include/eeprom/core/task.hpp
We haven't used the general  filesystem handler yet for anything so this PR fixes a few bugs that cropped up during testing.
We needed to add another config value to the hw_iface for what the default value of eeprom memory was, and fetch that config value before doing anything else
added in some more test converge, and added lots of comments
also fixes a bug where integer promotion resulted in the wrong address being written to the lookup table.
=> fix(eeprom): general filesystem accessor bug fixes

gripper/core/tasks.cpp, include/bootloader/core/ids.h, include/can/core/ids.hpp, include/can/core/messages.hpp, include/gripper/core/can_task.hpp, include/gripper/core/tasks.hpp, include/pipettes/core/dispatch_builder.hpp, include/pipettes/core/sensor_tasks.hpp, include/sensors/core/message_handlers/sensors.hpp, include/sensors/core/tasks/tip_presence_notification_task.hpp, include/sensors/core/utils.hpp, pipettes/core/sensor_tasks_g4.cpp
Hardware team has requested a tip presence query message to manually request tip state. This will
help with some tests they are running internally. [Python PR.](https://github.com/Opentrons/opentrons/pull/12439)
Closes RLIQ-359
=> feat(pipettes): add tip presence query request

pipettes/firmware/utility_gpio.c
Due to the noise on the data ready lines, the 96 channel firmware gets overwhelmed with the addition of the secondary sensor and crashes. For now, we should completely disable the initialization of the data ready interrupt. The real fix is to use a software timer rather use EXTI on the data ready line.
=> perf(pipettes): remove interrupt initialization for the data ready line on the 96 channel

include/bootloader/core/ids.h, include/can/core/ids.hpp, include/motor-control/core/brushed_motor/brushed_motion_controller.hpp, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, include/motor-control/core/motor_hardware_interface.hpp, include/motor-control/core/stepper_motor/motion_controller.hpp, include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, include/motor-control/firmware/brushed_motor/brushed_motor_hardware.hpp, include/motor-control/firmware/motor_control_hardware.h, include/motor-control/firmware/stepper_motor/motor_hardware.hpp, include/motor-control/simulation/sim_motor_hardware_iface.hpp, include/motor-control/tests/mock_brushed_motor_components.hpp, include/motor-control/tests/mock_motor_hardware.hpp, motor-control/firmware/brushed_motor/brushed_motor_hardware.cpp, motor-control/firmware/motor_control_hardware.c, motor-control/firmware/stepper_motor/motor_hardware.cpp, motor-control/tests/test_brushed_motor_interrupt_handler.cpp, motor-control/tests/test_motor_interrupt_handler.cpp, motor-control/tests/test_motor_interrupt_queue.cpp
When we implemented StopRequest, we were really doing it as a way to make sure everything got the message about an estop activation. 
We now need to use it to clean up after cancelling protocols, and send it from the host outside an estop situation... and that didn't really work.
This PR decouples the logic of
- estop handling
- canceling and clearing the interrupt handler move queue
- getting StopRequests
It's now safe to get an arbitrary stop request during a move or not during a move which will halt motion and clean up all the move state and clear out the queues. This also simplifies some of the interrupt handler state logic.
- logic look good
- Tests
=> fix(motor-control): allow StopRequests outside estop

pipettes/core/configs.cpp, pipettes/firmware/motor_configurations.cpp
When the plunger motors on the 96 channel pipette would stall with a microstep value of 64, the firmware would shut down. Decreasing the resolution to 16 seems to fix that problem and allow the pipette to keep operating after a stall.
=> refactor(pipettes): change pipette microstep to 16

pipettes/firmware/motor_configurations.cpp
It turns out that the sense resistors for all the motors on the 96
pipette are .15ohm instead of .1ohm and we never noticed. Yes, that
includes older revisions.
We're going to rework the sense resistor specifically on the plunger
back to 0.1Ohm, so we can keep that value, but that's to have a larger
possible current so we bump the global scaler there. Meanwhile, the tip
motors will keep their 0.15Ohm resistors, so we should get the right
number written down.
=> fix(pipettes): correct sense resistor values

include/motor-control/core/tasks/usage_storage_task.hpp
didn't catch this before because it didn't throw an error on CI or my system, but clang host builds were failing
=> fix(motor-control): make _hardware_delay a template function

include/sensors/core/tasks/capacitive_driver.hpp
We never actually disabled continuous polls when the sync and echo flags were cleared. We should explicitly disable the poller when these flags have changed.
I'm not sure if this will fix some of the reliability issues we were seeing, but I guess we can give it a go tomorrow.
=> fix(include): stop continuous polls when sync and echo flags are cleared

include/sensors/core/tasks/capacitive_driver.hpp, sensors/tests/test_capacitive_sensor.cpp
I was overzealous in when we should reset the CAPDAC register. We should only reset the capdac register if we're switching sensors.
Also, I broke some tests previously 😬
=> fix(include): do not reset CAPDAC after every request to stop polling

gripper/firmware/eeprom_keys.cpp, gripper/firmware/interfaces_grip_motor.cpp, gripper/firmware/motor_hardware.h, gripper/firmware/motor_hardware_g.c, gripper/firmware/motor_hardware_shared.c, gripper/firmware/stm32g4xx_it.c, gripper/simulator/eeprom_keys.cpp, include/bootloader/core/ids.h, include/can/core/ids.hpp, include/gripper/firmware/eeprom_keys.hpp, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, include/motor-control/core/motor_hardware_interface.hpp, include/motor-control/core/tasks/messages.hpp, include/motor-control/core/tasks/move_status_reporter_task.hpp, include/motor-control/core/tasks/usage_storage_task.hpp, include/motor-control/core/usage_messages.hpp, include/motor-control/firmware/brushed_motor/brushed_motor_hardware.hpp, include/motor-control/firmware/motor_control_hardware.h, include/motor-control/simulation/sim_motor_hardware_iface.hpp, include/motor-control/tests/mock_brushed_motor_components.hpp, motor-control/firmware/brushed_motor/brushed_motor_hardware.cpp, motor-control/firmware/motor_control_hardware.c
This adds another timer to the gripper that counts up when movement on the gripper stops,
if the gripper is in force application mode when the counter overflows it increments its usage in eeprom
if the gripper starts a new move while in force application mode it fetches the current timer count and stores that data
also expands the GetUsageDataResponse to include the force application time
<s>depends on #635 </s>
and https://github.com/Opentrons/opentrons/pull/12499
=> feat(gripper) use eeprom to store Jaw force mode time

gantry/firmware/eeprom_keys.cpp, gantry/firmware/interfaces_proto.cpp, gantry/firmware/interfaces_rev1.cpp, gripper/firmware/eeprom_keys.cpp, gripper/firmware/interfaces_grip_motor.cpp, gripper/firmware/interfaces_z_motor.cpp, head/firmware/eeprom_keys.cpp, head/firmware/main_proto.cpp, head/firmware/main_rev1.cpp, include/can/core/ids.hpp, include/gantry/firmware/eeprom_keys.hpp, include/gripper/firmware/eeprom_keys.hpp, include/head/firmware/eeprom_keys.hpp, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, include/motor-control/core/motor_hardware_interface.hpp, include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, include/motor-control/core/tasks/messages.hpp, include/motor-control/core/tasks/move_status_reporter_task.hpp, include/motor-control/core/tasks/usage_storage_task.hpp, include/motor-control/core/usage_messages.hpp, include/pipettes/core/tasks/gear_move_status_reporter_task.hpp, include/pipettes/core/tasks/messages.hpp, include/pipettes/firmware/eeprom_keys.hpp, motor-control/tests/test_brushed_motor_interrupt_handler.cpp, motor-control/tests/test_motor_interrupt_handler.cpp, pipettes/firmware/eeprom_keys.cpp, pipettes/firmware/interfaces.cpp
Uses the eeprom to store a count of the number of errors thrown by each board
=> feat(motor-control): use eeprom to track total error events

include/pipettes/core/dispatch_builder.hpp, include/pipettes/core/tasks/gear_move_status_reporter_task.hpp, include/pipettes/core/tasks/message_handlers/motion.hpp, include/pipettes/core/tasks/messages.hpp, include/pipettes/core/tasks/motion_controller_task.hpp
We don't care about encoder info for the tip motors because they do not have encoders. Since there aren't two separate node ids on the 96 channel pipettes, it's just easier to disable the update position estimation request for gear motors.
=> refactor(pipettes): do not accept update position estimation messages for the gear motors

state_manager/CMakeLists.txt
Need to only build the wheel because when it builds both I get dependency resolution errors when doing pip install /ot3-firmware/state-manager/dist/*
Better to just not build it at all instead of filtering it out in the install.
=> chore: Only build state manager wheel

gantry/simulator/interfaces.cpp
The way I added the the eeprom to the gantry simulators accidently called the backing creation twice which ended up making it point to the wrong file
=> fix(gantry): Fix the gantry emulators crashing

push
It can take a while for the robot-server to start after pushing the firmware if the subsystems need to be updated, this means that the update can fail if the ssh session gets dropped for any reason, leaving devices in bootloader mode. So to prevent these types of issues let's background the restart robot-server command.
=> fix(build): background the process when restarting the server in the push script

gantry/firmware/interfaces_rev1.cpp
One of the ABR units was having a repeatable issue where the motor would seemingly skip a few steps (between 0.5 and 1 mm worth at a time) during a movement, causing the gantry to be severely unaligned. Tip pickups would fail and the pipettes would be visibly off-center from their LPC'd positions. The Gantry Y controller is able to detect this "skipping", and the `motor_position_ok` flag would be cleared after the event. There was also an audible noise during the acceleration phase of the movements, and in slow-motion videos the Y axis belt was bouncing severely at the time of the noise, as if it had been plucked.
Looking at the current to one of the motor windings showed a smooth sine wave at the start of a movement, and a relatively clean square wave during the full-stepping high …
=> fix(gantry): disable passive fast decay on Y axis

include/sensors/core/tasks/capacitive_driver.hpp
I'm not sure how this worked previously for the cap sensor, but we were having issues with the pressure sensor because we were using the incorrect token to stop the poll.
=> fix(include): use correct id to stop continuous polling

include/sensors/core/mmr920C04.hpp, include/sensors/core/sensor_hardware_interface.hpp, include/sensors/core/tasks/capacitive_sensor_task.hpp, include/sensors/core/tasks/pressure_driver.hpp, include/sensors/core/tasks/pressure_sensor_task.hpp, include/sensors/firmware/sensor_hardware.hpp, include/sensors/simulation/mmr920C04.hpp, include/sensors/simulation/mock_hardware.hpp, include/sensors/tests/mock_hardware.hpp, pipettes/firmware/main.cpp, pipettes/firmware/stm32g4xx_it.c, pipettes/firmware/utility_gpio.c, pipettes/simulator/main.cpp, sensors/tests/test_pressure_driver.cpp, sensors/tests/test_pressure_sensor.cpp
We cannot rely on the data ready interrupt to tell us when data is ready for the pressure sensor. Instead, we will now use a software timer to poll the data from the pressure sensor. Thankfully all of the infrastructure was there to easily make this change, however, I also took the opportunity to refactor the pressure driver a little bit to (hopefully) make it a little cleaner/more clear.
It was also requested from EEs that we switch over to using the low pass filter built in on the sensor, so I made that change here as well.
=> refactor(include): convert pressure driver to use a software timer rather than hardware interrupts

pipettes/firmware/interfaces.cpp
Found a small lil typo whilst trying to figure out the 96 channel crashing stuff
=> fix(pipettes): use correct id for tip motor eeprom tracking

include/motor-control/core/motor_hardware_interface.hpp, include/motor-control/core/stepper_motor/motion_controller.hpp, include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, include/motor-control/firmware/brushed_motor/brushed_motor_hardware.hpp, include/motor-control/firmware/motor_control_hardware.h, include/motor-control/firmware/stepper_motor/motor_hardware.hpp, include/motor-control/simulation/sim_motor_hardware_iface.hpp, include/motor-control/tests/mock_brushed_motor_components.hpp, include/motor-control/tests/mock_motor_hardware.hpp, motor-control/firmware/motor_control_hardware.c, motor-control/firmware/stepper_motor/motor_hardware.cpp
On several boards we noticed an issue where the encoder would be -2^16 off directly after a home and during the course of the investigation we found that the overflow interrupt is running multiple times in rapid succession when the encoder value is reset to 0. 
this solution turns it off when it finishes a home, and before any move makes sure that it is enabled again.
=> fix(motor-control): Fix encoder underflow errors that happen directly after homes

include/sensors/core/tasks/pressure_driver.hpp, include/sensors/core/tasks/pressure_sensor_task.hpp, sensors/tests/test_pressure_driver.cpp, sensors/tests/test_pressure_sensor.cpp
The data sheet doesn't appear to specify what happens if you set the active mode and reset the sensor in quick succession, but reducing the amount of active modes seems to reduce the frequency of the sensor borking.
=> refactor(include): reduce the amount the active mode command is sent to the pressure driver

.github/workflows/release_bundle.yaml
Request from hardware to make it easier to distribute images to the factory. Now we'll get names like gantry-x-c2-v13.hex.
=> chore: make firmware images contain refname

can/tests/test_messages.cpp, include/can/core/messages.hpp, include/pipettes/core/tasks/gear_move_status_reporter_task.hpp
Unfortunately the ordering of the tip action response got messed up somewhere along the way. This caused the ack id to never return anyting other than the default state of 1 for the tip/gear motors.
=> fix(can): modify TipActionResponse message order to match the expected order on python-side

include/bootloader/core/ids.h, include/can/core/ids.hpp, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, include/motor-control/core/motor_messages.hpp, include/motor-control/core/stepper_motor/motion_controller.hpp, include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, include/motor-control/simulation/motor_interrupt_driver.hpp, motor-control/tests/CMakeLists.txt, motor-control/tests/test_limit_switch.cpp, motor-control/tests/test_motor_interrupt_handler.cpp, motor-control/tests/test_motor_pulse.cpp, motor-control/tests/test_motor_stall_handling.cpp, motor-control/tests/test_sync_handling.cpp
This PR adds a new MoveStopCondition called `ignore_stalls`. This can be used together with other conditions and the firmware will ignore and not raise an error if the motor stalls during movement. 
There are 3 different scenarios where a stall is handled:
1. **MoveStopCondition::none**
This is a regular linear move where we're not expecting to see a stall. Therefore an unrecoverable error will be raised and a stop message will be broadcasted. 
3. **MoveStopCondition::stall**
This is a move where a stall is expected and will be handled differently (not implemented yet). A recoverable error will be raised and we do not need to send a stop message.
4. **MoveStopCondition::ignore_stalls** 
This move type should only be used during hardware testing. When a stall occurs, it doesn't raise any …
=> refactor(motor-control): re-enable stall detection

include/bootloader/core/ids.h, include/can/core/ids.hpp, include/sensors/core/tasks/pressure_driver.hpp
We should throw an error message for the use-case of an overpressure spike being detected. Potentially we'll want to do some filtering at some point, but I think the chances of us getting into this value range is very low and thus it's OK to not do any type of signal processing.
=> feat(include): add error code for overpressure trigger

include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, motor-control/tests/test_motor_interrupt_queue.cpp
We didn't actually set the encoder start position for stepper motor move message (except when we home) – this fixes it so we can track the distance traveled.
=> fix(motor-control): set encoder start position in motor ISR

motor-control/firmware/stepper_motor/motor_hardware.cpp, pipettes/firmware/interfaces.cpp
remove the encoder handle from the gear motor hardware interfaces. they were resetting the plunger encoder when they did tip actions
=> fix(pipettes): remove encoder handle from gear motor hardware

common/firmware/STM32G491RETx/STM32G491RETx_FLASH.ld, common/firmware/STM32G491RETx/startup_stm32g491xx.s, common/firmware/gpio.c, common/firmware/gpio.cpp, head/firmware/stm32g4xx_it.c, motor-control/core/types.cpp
The motor interrupts are kind of slow. This PR is an attempt to speed them up, especially for the head controller.
* We add a section in the linker script to store function in the STM32 CCMRAM. 
* This section is configured to grab every function in the `motor_handler` and `motor_hardware` namespaces
* We manually mark a few select functions to go in ccmram along with the specific motor controller stuff
* We add a section in the startup file to copy the ccmram functions from flash to ccmram, because the ccmram is volatile
* We also cut out the STM32 timer interrupt handler for the Head unit's motor control interrupt because it was taking up a lot of time with no real benefit
This seems to speed up the motors enough to let the head move both axes at the same time without crashing, which it …
=> chore(motor-control): put motor-control functions in ccmram

include/bootloader/core/ids.h, include/can/core/ids.hpp, include/sensors/core/fdc1004.hpp, include/sensors/core/mmr920C04.hpp, include/sensors/core/tasks/capacitive_driver.hpp, include/sensors/core/tasks/capacitive_sensor_task.hpp, include/sensors/core/tasks/pressure_driver.hpp, include/sensors/core/tasks/pressure_sensor_task.hpp
This is only really relevant to the pressure sensor, but I decided to add support for the cap sensor as well. We want to make sure that the sensor does not ever exceed its max output to ensure that the sensor itself doesn't break.
There will be a python-side PR to add the new sensor output binding as well as the context manager to allow for continuous sensor monitoring.
=> feat(include): add checks for exceeding max sensor readings for the pressure and cap sensor

pipettes/firmware/motor_configurations.cpp
Disable stealthchop, driver runs in spread cycle mode
```.en_pwm_mode = 0```
Set speed driver changes to constant toff chopper mode to ~60mm/s so we operate in spread cycle at all used velocities
```.thigh threshold = 0x7```
Decrease the off time in slow decay phase, increases effective chopper frequency to ~30khz-40khz which can help high speed performance
```.toff = 0x2```
Reduce chopper hysteresis, found to help high speed performance in testing
```.hstrt = 0x0```
Reduce blanking time to minimum setting 1.3us, improves high speed performance
```.tbl = 0```
Add 21us of passive fast decay, dampens resonance
```.tpfd = 0x2```
Enable 256 microstep interpolation, dampens resonance
```.interpol = 1```
=> fix(pipettes): 96ch motor-driver settings tuned for faster speeds

scripts/subsystem_versions.py
The regex for matching the version tag when generating the manifest was only matching the first digit. This PR lets it match multiple digits.
=> fix(scripts): accept multi-digit version tags

common/firmware/STM32G491RETx/STM32G491RETx_FLASH.ld, pipettes/core/can_task_high_throughput.cpp, pipettes/core/can_task_low_throughput.cpp, pipettes/core/gear_motor_tasks.cpp, pipettes/core/linear_motor_tasks.cpp, pipettes/core/peripheral_tasks.cpp, pipettes/core/sensor_tasks.cpp
The linker file provided by STM is correct to say that the microcontroller has 112K RAM, but it _also_ separately defines the last 16K of that as the `CCMRAM` region. This means that, if the entire RAM is used by the program, variables will overlap into anything defined in ccmram and chaos will ensue.
The pipette firmware was all overflowing into ccmram, which the linker didn't complain about because it is unaware that the ccmram is aliased at the end of the normal SRAM address region.
The pipettes _also_ have a lot of tasks, and each of those tasks has a minimum stack size of 512 words (so 2048 bytes). This PR cuts all of the stack allocations in half.
Tested on a multichannel and a 96-channel. Able to calibrate, aspirate, dispense, pick up tips... seems good to go.
=> fix(pipettes): don't use more RAM than allowed

CMakeLists.txt, common/firmware/gpio.c, common/firmware/gpio.cpp, head/firmware/stm32g4xx_it.c, motor-control/core/types.cpp
If your host compiler is GCC, the .ccmram section attributes won't do anything because GCC silently ignores missing sections (whether that's good or bad is up for debate). If your host compiler is _not_ GCC, you might get compiler errors. This PR should eliminate those errors.
=> fix(host): comment out .ccmram section for host builds

include/bootloader/core/ids.h, include/can/core/ids.hpp, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, motor-control/tests/CMakeLists.txt, motor-control/tests/test_limit_switch.cpp, motor-control/tests/test_limit_switch_backoff.cpp, motor-control/tests/test_motor_pulse.cpp, motor-control/tests/test_motor_stall_handling.cpp
Ideally, the origin point of each axis should be the exact same point each time we command the axis to home. With level switches, there's a range of operating distance where the contacts are tripped. To improve precision, every time we home an axis and trigger a limit switch, we can slowly back away from the switch until the first instance the contacts are released. This way we can ensure the position of the axis origin to be roughly the same every time. 
Main changes:
1. Add a new move stop condition `MoveStopCondition::limit_switch_backoff`
2. Instead of resetting the stepper and encoder tracker after a HomeRequest, we're going to reset everything after the subsequent `limit_switch_backoff` move instead
Changes to the home & backoff behavior from last review:
1. Still setting stepper …
=> feat(motor-control): limit switch backoff move for stepper motors

pipettes/simulator/main.cpp
`MOUNT` in the environment variables needed to be lowercase `mount` to map correctly to the command line variables.
Before this PR, the simulator would crash if you defined an environment variable `MOUNT`. Now it will work correctly + pick up the option.
=> fix(pipettes): simulator environment var did not match command line variable

include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, motor-control/tests/test_motor_stall_handling.cpp
Send a MoveComplete message, on top of the error message, to report current stepper & encoder position when a stall happens during an active move.
=> feat(motor-control): report stepper & encoder position when stall occurs

gripper/firmware/motor_hardware_shared.c, gripper/firmware/stm32g4xx_it.c, include/motor-control/core/brushed_motor/brushed_motion_controller.hpp, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp
So before putting the gripper interrupts in ccram we were getting encoder overflow timing errors on the gripper jaw pretty frequently (~10 min of constant use) after doing the ccram stuff we drastically reduced the errors but it was still happening on avg every ~1.5 hours of constant use. So this throws the interrupts into ccram, and it also drops the priority of the motor usage timer to prevent it squashing over the interrupts.
As a final kind of guard against the encoder being -0xFFFF occasionally I threw in a check that the encoder is >=0 before reporting a stall
=> feat(gripper): Use ccram for gripper

include/sensors/core/mmr920C04.hpp
This PR sets the pressure sensor's max value to 8.2kPa, which is the highest value possibly returned by the pressure sensor. Anything higher cannot be measured and will return as 8.2kPa.
=> fix(include): pressure-sensor max-value

pipettes/firmware/stm32g4xx_it.c
So, very confused and not sure if we also need to make this change for the 96 channel, BUT switching back only the clear flag to the EXTI value seems to fix the async notifications for tip sensing.
=> fix(pipettes): Convert back to EXTI for single and multi

pipettes/core/sensor_tasks.cpp, pipettes/firmware/freertos_idle_timer_task.cpp
I got a little too trigger happy with #682 with the sensor tasks. Some pipettes have been crashing when using the environmental or pressure sensors, and running one with a debugger + overflow detection enabled showed that the stack for the sensor task will overflow sometimes. The sensor tasks use their stack to maintain a parallel map of the register map of their respective sensor, so it kind of makes sense. We could (and maybe should) refactor the handlers to be statically allocated somehow to avoid throwing too much data on the stack, but for now we can just bump the stacks back up.
=> fix(pipettes): increase sensor stack sizes

gantry/firmware/i2c_setup.c, gripper/firmware/i2c_setup.c, head/firmware/i2c_setup.c, i2c/firmware/i2c.c, i2c/firmware/i2c_comms.cpp, include/i2c/firmware/i2c.h, pipettes/firmware/i2c_setup.c, rear-panel/firmware/i2c_setup.c
This PR changes the firmware's use of the HAL I2C API to be interrupt-based. The i2c task kicks off a read/write transmission and then releases the CPU until the I2C callback is called. This should release the CPU to run other FreeRTOS tasks during I2C transmissions, instead of spinning for the duration of the transmission. 
- When starting a new read/write, a handle associated with the HAL struct is loaded with a task-to-notify
- When the Tx/Rx complete callback is called, the task-to-notify is looked up via the HAL struct and, if it exists, that task is unblocked
This is the same implementation used on the Heater-Shaker and Thermocycler Gen2. 
Tested on FLEXY MCFLEXFACE by uploading firmware to the whole robot with a gripper, a 96 channel, and (after removing the 96) a single channel. …
=> feat(i2c): interrupt-based I2C communication

include/motor-control/firmware/stepper_motor/motor_hardware.hpp, motor-control/firmware/stepper_motor/motor_hardware.cpp
During liquid sensor repeatability testing, the z axis was occasionally crashing a tip into the bottom of a well and ignoring the top of the water. This seemed to be an issue with the head board not recognizing the change of state on the `sync` line because:
- The pipette would end its movement and send a move completion as soon as it hit the top of the water, as expected
- The head's move completion would indicate that it ended due to reading the sync line, but would come up to 4 seconds later than the pipette's
Getting rid of the debouncing for this pin seems to pose little-to-no risk because 
- It is driven digitally, rather than by a real switch
- There is no consequence if it experiences transient noise due to e.g. plugging in a pipette, so long as there isn't a movement going on …
=> feat(motor-control): do not debounce sync line

gantry/firmware/interfaces_proto.cpp, gantry/firmware/interfaces_rev1.cpp, gantry/firmware/motor_hardware.c, gripper/firmware/interfaces_z_motor.cpp, gripper/firmware/motor_hardware_g.c, gripper/firmware/motor_hardware_shared.c, gripper/firmware/motor_hardware_z.c, head/firmware/main_proto.cpp, head/firmware/main_rev1.cpp, head/firmware/motor_hardware_common.c, include/motor-control/core/stepper_motor/motor_encoder_background_timer.hpp, include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, include/motor-control/firmware/motor_control_hardware.h, include/motor-control/firmware/stepper_motor/motor_hardware.hpp, include/motor-control/simulation/motor_interrupt_driver.hpp, motor-control/firmware/brushed_motor/brushed_motor_hardware.cpp, motor-control/firmware/motor_control_hardware.c, motor-control/firmware/stepper_motor/motor_hardware.cpp, motor-control/tests/test_limit_switch.cpp, motor-control/tests/test_limit_switch_backoff.cpp, motor-control/tests/test_motor_pulse.cpp, pipettes/firmware/main.cpp, pipettes/firmware/motor_timer_hardware.c
When one of the motor axes overflows its encoder, there's a not-uncommon race condition between the encoder timer's raw counter value and the variable capturing the number of timer overflows. If the motor interrupt controller tries to read the position between when the counter is updated but the overflows aren't updated, the encoder position will appear to be off by a considerable amount.
This PR enables the `UIFREMAP` bit for all of the encoders on the motor control boards. This bit effectively results in the MSb of the CNT register containing a flag for whether the encoder has a pending overflow. Instead of using the interrupt vector to determine when an overflow has occurred, we just check the UIFCPY bit in the CNT register. If an overflow has happened, the function getting the encoder …
=> fix(motor-control): atomically account for encoder overflows

include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, motor-control/tests/test_limit_switch.cpp, motor-control/tests/test_motor_pulse.cpp
If the limit switch is not triggered within a `HomeRequest`, this means that we can no longer trust the encoder value and we should just clear the flag. This will force the axis to do a proper home when it receives a `HomeRequest` again.
=> fix(motor-control): clear encoder status flag when home fails

CMakeLists.txt, include/sensors/core/fdc1004.hpp, include/sensors/core/tasks/capacitive_driver.hpp, include/sensors/core/tasks/capacitive_sensor_task.hpp, include/sensors/core/utils.hpp, include/sensors/simulation/fdc1004.hpp, sensors/tests/test_capacitive_sensor.cpp
The capacitive sensor seems to be having issues that stem from the initial register configuration. One issue seems to be that we are enabling a single channel at a time, but doing it twice in a row on startup. We may also be losing I2C messages in the flurry of bus traffic on startup, which may be exacerbated by the I2C tasks now releasing the CPU during transactions and therefore allowing other tasks to try to write more messages.
This PR does a couple of things which, in conjunction, seem to fix the issue of bad capacitive sensor data:
- Instead of directly polling the data registers, check the Reading Ready flags in the FDC register first.
- Always enable readings from both Reading 1 and Reading 2, and let them just run continuously forever
- Only configure one channel's readings at a …
=> fix(sensors): mitigate cap sensor configuration issues

include/motor-control/core/stepper_motor/motor_encoder_background_timer.hpp, include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp
We should update the position flag whenever the encoder value is off from where we expect the motor to be, not just during an active move. We can do this in the encoder background timer so that we are re-evaluating the position flag every time we read the encoder pulses.
=> fix(motor-control): update position flag inside encoder background timer

include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp
The stall checker sometimes falsely reported that a stall has been detected even though the stepper and encoder values are within the acceptable threshold. 
This is because the `check_stall_itr()` function we use to check for stall is optimized for high-speed interrupts – we store a cache for the ideal encoder count and update it _only_ after the motor position has surpassed the current threshold. Now that we're checking for stall in the background timer, we're always comparing the current encoder value against the ideal count that was set from a previous move.
Instead, we should refresh the ideal count based on the current stepper count whenever the motor interrupt handler finishes the last move in a sequence (only when no new moves are in the queue).
=> fix(motor-control): refresh the stall thresholds after finish the last move in the queue

bootloader/firmware/stm32G4/CMakeLists.txt, gantry/firmware/CMakeLists.txt, gripper/firmware/CMakeLists.txt, pipettes/firmware/CMakeLists.txt, rear-panel/firmware/CMakeLists.txt
Add revision handling for the variants:
- Gantry C2
- Rear-panel C1 (B2 did not actually exist, keeping it just in case)
- LT pipette D1
- Gripper C2
Head got a bump from C2.0 to C2.1, which we don't track; SOM got a bump but we don't track that; 96 hasn't gotten its bump yet.
These changes are to enter PVT.
Medium I guess. These are going to be flashed to real boards and used in real ways, but there's no code changes before and after this, so I don't know.
=> chore: add revisions for PVT boards

include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp
The way we refreshed the stall threshold in #705 actually only fixes moves when they complete without meeting any condition. If the move has a stop condition such as sync_line or limit switch, etc, we don't reach that piece of code.
Moving the reset to the end of `finish_current_move` should fix this problem. 
Fixes this ticket: https://opentrons.atlassian.net/browse/RQA-1135
=> fix(motor-control): reset itr count after finish move 

include/motor-control/core/stepper_motor/motion_controller.hpp
We should just let the DisengageMotorRequest handle that instead.
=> fix(motor-control): do not disengage motor when a StopRequest is received

include/can/core/messages.hpp, include/motor-control/core/brushed_motor/brushed_motion_controller.hpp, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, include/motor-control/core/motor_messages.hpp, motor-control/tests/test_brushed_motor_interrupt_handler.cpp
We want to be able to differentiate between an actual labware grip and a grip that closes the jaw to minimize the footprint of the gripper during gantry movement (we call this the idle position from the api). 
This will inform the firmware whether or not the jaw motor needs to stay engaged when we receive a stop request and prevent unexpected dropping of labware. And if the gripper was in the idle position, the jaw can simply disengage since it does not matter because it is not gripping anything.
The next step is to get gripper to report the real-time jaw state to the hardware controller API (so we don't have to rely soely on the gripper handler instance variable to keep track of the jaw state, which gets lost when the robot server stops).
=> feat(gripper): add stay engaged param to grip message

gripper/core/tasks.cpp, include/can/core/messages.hpp, include/gripper/core/tasks.hpp, include/pipettes/core/sensor_tasks.hpp, include/sensors/core/message_handlers/sensors.hpp, include/sensors/core/tasks/tip_presence_notification_task.hpp, pipettes/core/sensor_tasks.cpp, pipettes/firmware/main.cpp, pipettes/firmware/utility_configurations.cpp
This code enables both tip presence sensors to be read on the 8 and 96 channel pipettes, making each sensor individually addressable via CAN message.
- replace single tip notification task with two tasks: front and rear
- add sensor id parameter to tip notification task and related CAN messages 
- switch pin configurations for front and rear sensors to match MCU schematic
=> modify tip presence sensor task

include/bootloader/core/ids.h, include/can/core/ids.hpp, include/can/core/messages.hpp, include/motor-control/core/brushed_motor/brushed_motion_controller.hpp, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, include/motor-control/core/motor_hardware_interface.hpp, include/motor-control/core/motor_messages.hpp, include/motor-control/core/tasks/brushed_motion_controller_task.hpp, include/motor-control/core/tasks/messages.hpp, include/motor-control/core/types.hpp, include/motor-control/firmware/brushed_motor/brushed_motor_hardware.hpp, include/motor-control/tests/mock_brushed_motor_components.hpp, motor-control/tests/test_brushed_motor_interrupt_handler.cpp
This PR:
1. adds CAN messages to request and report gripper jaw state from the brushed motor hardware interface
2. simplifies the gripper jaw states to `unhomed`, `force controlling home`, `force controlling` and `position controlling`
3. includes a small refactor to the brushed motor interrupt handler
=> feat(motor-control): report brushed motor state (jaw state)

include/common/core/freertos_synchronization.hpp, include/motor-control/core/stepper_motor/motor_encoder_background_timer.hpp
When we do the encoder polling timer we really want the motor interrupt to not be able to start in the middle of the timer code, so let's wrap it in a critical section.
We saw this in a protocol that was moving the z up and down by 5mm over and over so let's run a protocol that just does that and see if it happens I guess? This is a bug that seems to have occurred once in hundreds or thousands of machine hours of testing so it's going to be tough to say for certain.
It did pass though.
=> fix(motor-control): critical section for encoders

include/motor-control/core/tasks/brushed_move_group_task.hpp, include/motor-control/core/tasks/move_group_task.hpp, include/pipettes/core/tasks/move_group_task.hpp
In https://github.com/Opentrons/opentrons/pull/13451, we increase the maximum number of steps that may be generated in a move group. We need to be able to accept all of those steps on the firmware side.
The only real downside here is RAM usage. I was able to build everything locally, but we obviously need to make sure CI is able to link everything as well. If there are any problems I think the best thing to do is cut down on the total move groups, since in practice we only use a few of the allotted 6.
=> feat(all): allow for up to 12 steps in each move group

include/can/core/message_handlers/motion.hpp, include/gripper/core/can_task.hpp, include/motor-control/core/brushed_motor/brushed_motion_controller.hpp
Forgot to add this to the can task so we weren't getting any response back from the gripper. 
Testing is importante!
=> fix(gripper): add GripperJawStateRequest to gripper can task & do not disable brushed motor if it was set to stay engaged

include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, motor-control/tests/test_brushed_motor_interrupt_handler.cpp
We're using the UpdatePositionEstimation message to report the jaw encoder position right when the move fails, this message will be ignored by the host but we can observe it on the can bus and will make debugging easier.
=> feat(gripper): report jaw encoder pulses when something goes wrong

include/sensors/core/tasks/pressure_driver.hpp
The intent of the overpressure warning is to avoid damage to the pressure sensor. The sensor will only give us a reading up to ~8kPa, but the actual pressure it can withstand is far higher. In an effort to avoid overeager protocol-ending errors, we are adding a requirement that the pressure remains over the threshold for at least 500MS before throwing an error.
This PR also adds reporting of any readings over the threshold.
Tested on Flexy by blocking the pipette nozzle while aspirating/dispensing. You can see in the can logs that you get a bunch of Pressure Reading responses before they start including error messages. Short aspiration/dispense distances don't have enough time to trigger the error.
=> feat(pipettes): require overpressure for 500ms before error

common/tests/test_debounce.cpp, include/common/core/debounce.hpp, include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, motor-control/tests/test_brushed_motor_interrupt_handler.cpp
There's potential noise on the gripper jaw encoder line that causes the gripper to falsely report a move has failed. We're now confirming the encoder value has deviated from the expected val twice consecutively when executing an idle move before reporting it has failed.
=> feat(gripper): allow the encoder value to debounce if deviated from expected val

include/sensors/core/tasks/pressure_driver.hpp
This is a little safer on the 1000ul which is otherwise capable of driving enough pressure changes to cause a problem.
=> fix(sensors): Reduce overpressure time to 200ms

include/sensors/core/tasks/pressure_driver.hpp, pipettes/firmware/utility_gpio.c
The GPIO ports were wrong unfortunately.
=> fix(pipettes): changes to enable the correct sync line ports for the 96-channel

pipettes/firmware/main.cpp, pipettes/firmware/utility_configurations.cpp, pipettes/firmware/utility_gpio.c
On the 96 channel pipette, readings of the tip presence sensor are only meaningful when the gear motors are moved down far enough to drop the shroud below the optical sensor. If tips are accidentally dropped during a protocol, we wouldn't actually know until we check by commanding the gear motors to move. Therefore, we don't need an interrupt for changes in the 96 channel's sensor status.
- Initialize the tip presence sensor for the 96 channel as a regular gpio input, and keep interrupt initialization for the single and 8 channel pipettes
- Remove the check in the interrupt's callback for whether the gpio pin is the `primary` or `secondary` sensor, as this only applies to the 96 channel
- Invert the active setting of the gpio pin only for the 96 channel, so the 96 channel's response logic …
=> only autmomatically notify about low throughput tip changes

include/motor-control/core/stepper_motor/motor_encoder_background_timer.hpp, include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp
RQA-1812, and possibly some other ABR failures, seems like it may be a result of an axis encoder overflowing multiple times during an empty move. We have an encoder background timer that runs when the interrupt handler doesn't have an active move, but that doesn't account for the fact that we often set up motor axes with empty moves (no acceleration & no velocity) matching the duration of the move groups for active axes. 
To fix this edge case, we should also check the velocity of the buffered move when the encoder timer is determining whether it should read the encoder. This PR adds a new function in the interrupt handler to return whether 1) there is a buffered move 2) the buffered move's velocity is not 0.
We only access the function in a critical section so I don't think it matters …
=> fix(motor-control): monitor encoder during empty moves

include/motor-control/firmware/motor_control_hardware.h, motor-control/firmware/motor_control_hardware.c, motor-control/firmware/stepper_motor/motor_hardware.cpp
This worked somehow? Need way more testing to verify this fix
=> fix(motor-control): z stage falls after being disengaged

head/firmware/motor_hardware_rev1.c, include/motor-control/firmware/motor_control_hardware.h, motor-control/firmware/motor_control_hardware.c, motor-control/firmware/stepper_motor/motor_hardware.cpp
We shouldn't have added the delay if the ebrake doesn't exist. 
Also fixing an old commit message to actually show what it does.
=> fix(motor-control): only add a delay before disengaging motor if ebrake exists

.github/workflows/release_bundle.yaml
by not posting releases for them
=> chore: handle internal-release tags

scripts/subsystem_versions.py
This is required to add the hepa-uv entry to the `opentrons-firmware.json` manifest file used by the Flex to perform firmware updates.
=> fix(hepa-uv): add hepa-uv to firmware manifest json file.

hepa-uv/core/tasks.cpp, hepa-uv/firmware/main_rev1.cpp, include/hepa-uv/core/hepa_task.hpp, include/hepa-uv/core/tasks.hpp, include/hepa-uv/core/uv_task.hpp
The HEPA/UV has a UV Ballast that needs to turn on/off based on external input, this pr adds a a task that actuates the UV ballast based on these external inputs. It also adds a timer that turns off the UV ballast after 15m.
Closes: [RET-1402](https://opentrons.atlassian.net/browse/RET-1402)
- Add a UVTask that listens for irq interrupts and turns on/off the UV Ballast accordingly
- Turn off the HEPA fan and UV Ballast on startup
- Does this approach make sense?
- I'll have to go back in at some point to add a better interface instead of using gpio::set/reset directly
- Feedback is appreciated!
[RET-1402]: https://opentrons.atlassian.net/browse/RET-1402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(hepa-uv): Add a task to handle the UV Ballast state based on external input

.github/workflows/build-simulators.yaml, CMakePresets.json, include/can/core/messages.hpp
The functionality for the HEPA/UV module is not complete yet, so let's remove the simulator build so it does not stop other simulators from building. This will be re-added in a future PR.
=> fix(hepa-uv): remove hepa-uv simulators so they don't block CI.

include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp
Currently we only check for encoder overflow when the motor is actively stepping. And if the motor velocity is very slow, we could potentially miss an overflow or two because of the encoder jitters. The fix here is to check for it more often. This will now allow our axes to move much more slowly.
=> fix(motor-control): check for encoder overflow more often

cpp-utils/include/ot_utils/freertos/freertos_timer.hpp, hepa-uv/core/can_tasks.cpp, hepa-uv/core/tasks.cpp, hepa-uv/firmware/main_rev1.cpp, include/bootloader/core/ids.h, include/can/core/ids.hpp, include/can/core/messages.hpp, include/hepa-uv/core/can_task.hpp, include/hepa-uv/core/hepa_task.hpp, include/hepa-uv/core/hepauv_info.hpp, include/hepa-uv/core/interfaces.hpp, include/hepa-uv/core/message_handler.hpp, include/hepa-uv/core/messages.hpp, include/hepa-uv/core/uv_task.hpp, include/hepa-uv/firmware/hepa_control_hardware.hpp
We need to control the Hepa/UV filter from the Flex for testing and eventual system integration, this PR implements the CAN messages required to make this happen. It also adds a new method to query the time remaining before a software timer expires. This PR coincides with [Opentrons/opentrons#14452](https://github.com/Opentrons/opentrons/pull/14452) PR.
Closes: [RET-1422](https://opentrons.atlassian.net/browse/RET-1422) [RET-1423](https://opentrons.atlassian.net/browse/RET-1423)
- Added implementation for CAN messages to set/get Hepa fan state/duty cycle
- Added implementation for CAN messages to set/get UV Light state/timeout in seconds
- Added a get_remaining_time method to the FreeRTOSTimer class to know the time in ms before the timer expires.
- Integrated the new CAN messages into …
=> feat(hepa-uv): Add CAN messages to control the Hepa/UV filter.

include/motor-control/core/stepper_motor/tmc2160_driver.hpp
This corrects the 2160 motor driver register we use with the `update_glob_scaler` method.
=> fix 2160 motor driver register usage

gripper/firmware/utility_gpio.c, include/motor-control/core/stepper_motor/motion_controller.hpp, include/motor-control/core/tasks/motion_controller_task.hpp
We've been mistakenly engaging the z motors during start up (this supposedly disables the ebrake and uses the start the motor interrupt handler, which is the exact opposite of what we did in hardware gpio init).
This PR makes sure the z motors stay disengaged until the host tells it to move later on.
Closes RQA-2301, RQA-2429
=> fix(z-motors): should disegange Z motors at boot when motor controller task first starts

head/core/can_task.cpp, include/bootloader/core/ids.h, include/can/core/ids.hpp, include/can/core/message_handlers/motion.hpp, include/can/core/messages.hpp, include/gantry/core/can_task.hpp, include/gripper/core/can_task.hpp, include/motor-control/core/brushed_motor/brushed_motion_controller.hpp, include/motor-control/core/stepper_motor/motion_controller.hpp, include/motor-control/core/tasks/brushed_motion_controller_task.hpp, include/motor-control/core/tasks/messages.hpp, include/motor-control/core/tasks/motion_controller_task.hpp, include/pipettes/core/dispatch_builder.hpp, include/pipettes/core/tasks/message_handlers/motion.hpp, include/pipettes/core/tasks/messages.hpp, include/pipettes/core/tasks/motion_controller_task.hpp
Make use of our CAN message `get_status_request` to get whether or not the motor is enabled.
=> feat(motor-control): use motor status message to get motor enabled

.github/workflows/build_sensor_fw.yaml, .github/workflows/cross-compile-special-sensors.yaml, .gitignore, CMakePresets.json
This PR adds a new configure preset and build preset that builds the firmware with the "USE_PRESSURE_MOVE" define
This enables the special firmware that allows the system to buffer sensor data on the pipettes, and sync sensor tasks with movements.
The workflow file builds and uploads just the applications so that internal users can just pull the .zip file of them from CI instead of building them
=> chore(cmake): Add sensor variant firmware ci

motor-control/firmware/stepper_motor/motor_hardware.cpp
We did not give enough time after enabling the motor and disabling the ebrake, this would cause a move complete without condition being met. So lets add a 20ms delay after engaging/disengaging the the ebrake so it can settle before attempting to perform a move.
Closes: [RQA-2565](https://opentrons.atlassian.net/browse/RQA-2565)
- Add 20ms delay after engaging/disengaging the ebrake
Med, this affects homing,
Needs to be tested under typical homing conditions
[RQA-2565]: https://opentrons.atlassian.net/browse/RQA-2565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(motor-control): add delay to give enough time for ebrake to physically disengage.

pipettes/core/sensor_tasks.cpp
In `sensor_tasks`, both the front and rear capacitive sensor task builders were assigned to sensor id S0. This fixes it so the rear one will be s0, and the front s1.
=> fix(pipettes): Assign front capacitive sensor task to s1

pipettes/firmware/motor_configurations.cpp
Fixes (motor driver false positive) error seen with 96-channel pipette. To test, successfully calibrated 96-channel pipette as well as gripper and then homed.
=> fix(motion-control): motor driver error surfacing

include/sensors/core/tasks/pressure_driver.hpp
When we send a bunch of errors because the queue is full it can cause the can bus to choke up with stop requests which are annoying and make the logs hard to read.
The new LLD script that uses this custom firmware now limits motion based on factors that include the buffer size of the pipettes so we can just get rid of this.
=> fix(sensors): don't send errors when queue is full

include/sensors/core/tasks/pressure_driver.hpp
we increased the measure mode rate change for the LLD testing but it seems to cause false overpressure errors so this PR gates using the different rates behind the compile time flag that we use to build the LLD variant firmware
=> fix(sensors): revert measure mode rate change

push
These changes to push allow us to specify targets in the form of presets, and only those targets will be built and copied onto the robot. To allow this, a new `update_shortsha` function grabs the existing manifest file from the robot, and updates the sha of the specified targets.
You can specify just one or multiple targets, for example:
`./push 10.10.10.10 --targets pipettes-single pipettes-multi gantry-x`.
`./push 10.10.10.10 --targets pipettes-single`
If this argument isn't used, the script will run the same as it did before, meaning it will build and update all firmware presets.
Logically, it behaves independently of the `sensors` argument, meaning you can use the `firmware-g4-sensors` build preset, and either send the full build or just the hex files for whichever nodes.
- add …
=> feat(push): add an option to specify targets

include/motor-control/core/stepper_motor/motion_controller.hpp
Recently we had to add a longer delay so that the brake had long enough to disable before the function returns. however the motor interrupt timer starts before we call enable motor. This swaps the order so that we know the motor is all the way enabled before we start the interrupt timer and try to move.
=> fix(motor-control): enable motor before turning on the motor interrupt timer

motor-control/firmware/motor_control_hardware.c
We recently started adding a delay between engaging a head motor and starting the execution of a move. We were using a HAL delay to do this, and it turns out that this blocks FreeRTOS's task handling, and in certain edge cases causes a firmware crash. 
We should instead use FreeRTOS's built-in `vTaskDelay`
=> fix(motor control): Use FreeRTOS delay instead of hardware delay

include/sensors/core/tasks/pressure_driver.hpp
Right now we send the raw sensor value instead of the corrected one, it will be better for lld development and just in general to get the corrected pressure data instead
=> fix(sensors): send the pressure sensor response with the baseline applied

include/sensors/core/tasks/capacitive_driver.hpp
There's a class variable for the capacitive sensor driver called `shared_sensor`, that is used to keep track of when both of the sensors are in use on an 8 or 96 channel pipette. I don't think the name alone communicates what it's for, so here's my suggestion for renaming it.
=> refactor(sensors): rename shared-sensor to using-both-sensors

include/bootloader/core/ids.h, include/can/core/ids.hpp, include/common/core/hardware_delay.hpp, include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, include/sensors/core/tasks/capacitive_driver.hpp, include/sensors/core/tasks/pressure_driver.hpp, include/sensors/core/tasks/pressure_sensor_task.hpp
We baseline the sensor reading during moves so that we can compensate better for different tips having a different baseline pressure differential when the plunger is moving
=> feat(sensors): Self baselining during sensor moves

include/can/core/ids.hpp, include/motor-control/core/motor_messages.hpp, include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, include/sensors/core/sensor_hardware_interface.hpp, include/sensors/core/tasks/capacitive_driver.hpp, include/sensors/core/tasks/pressure_driver.hpp, include/sensors/core/tasks/pressure_sensor_task.hpp, include/sensors/firmware/sensor_hardware.hpp, include/sensors/tests/mock_hardware.hpp, sensors/tests/CMakeLists.txt, sensors/tests/test_sensor_hardware.cpp
Hardware testing wants the ability to do all of the following logic commands for LLD on the 8/96:
A only
B only
A or B
A and B
This lets the python side decide which of these to use.
=> feat(sensors): Enable dual sensor logic for 8/96 channel

include/can/core/messages.hpp, include/motor-control/core/stepper_motor/motion_controller.hpp
We added it on the python side without doing all the parsing correctly in the c++ code
=> fix(can): parse the binding flag and pass to sensor move message

.github/workflows/start-ot3-build.yaml, README.md
> The README.md changes describe the behavior of the changes
> <https://opentrons.atlassian.net/browse/RDEVOPS-132>
- Do we want pushes to main to still trigger Flex builds?
=> fix(CI): tags do not trigger Flex builds

include/sensors/core/tasks/capacitive_driver.hpp
The S1 sensor has been falsely using the wrong ID while responding to CAN messages. 
This is because the sensor ID for the driver is defaulted to S0, and we rely on `set_sensor_id()` to update the sensor. We've made these changes for the pipettes (https://github.com/Opentrons/ot3-firmware/pull/630). And since `shared_sensor` is always false for the gripper, we've never set the sensor ID for S1.
=> fix(gripper): capacitive sensor task should use correct sensor ID

gripper/firmware/main_proto.cpp, gripper/firmware/main_rev1.cpp, gripper/simulator/main.cpp, include/pipettes/firmware/utility_configurations.hpp, include/sensors/core/sensor_hardware_interface.hpp, include/sensors/firmware/sensor_hardware.hpp, include/sensors/simulation/mock_hardware.hpp, include/sensors/tests/mock_hardware.hpp, pipettes/firmware/main.cpp, pipettes/firmware/utility_configurations.cpp, pipettes/simulator/main.cpp, sensors/tests/test_capacitive_sensor.cpp, sensors/tests/test_pressure_driver.cpp, sensors/tests/test_pressure_sensor.cpp, sensors/tests/test_sensor_hardware.cpp
I had been mistaken about the sensor hardware being shared instances but I see now that they were not, so I broke out the bitmask communication between sensor tasks into another singleton that the sensor hardware tasks can share.  
I also updated the tests so that when we test with multiple sensors they actually use two different hardware instances.
=> fix(sensors): Share sync line control bitmasks

include/hepa-uv/core/uv_task.hpp
When the door is closed, the reed switch is set, and the UV push button is pressed, the UV light turns on as expected.
However, if you then lift the back of the Hepa/UV and unset the reed switch, then set it back down setting the reed switch again. When you press the UV push button the safety relay pin will NOT be active even though the door is closed, and reed is set. The only way to activate the safety relay pin again is to open, and close the Flex door, and THEN press the UV push button again. This is by design per the hardware team as a way to make sure the user understands the intention when turning ON the UV light again.
Closes: [RQA-2872](https://opentrons.atlassian.net/browse/RQA-2872)
- Check safety relay is not set before attempting to change the UV light state.
[RQA-2872]: …
=> fix(hepa-uv): fix issue when turning on UV after re-seating the hepa/uv on the flex.

include/hepa-uv/core/uv_task.hpp
>  Note this does not affect 8.1.0. v55 is the tag for 8.0.0 and 8.1.0.
My first v55 merge back from release to main was not using release and/or main in the correct state.  Obviously I thought I was in the correct state.  The change looked correct in terms of content but it was not. I did not notice until Friday 10/4/2024 when I saw that v55 tag was not in main.
The change in this is identical to #806 and #802
We need to actually merge release to main correctly,  otherwise we will have an issue next release cycle (from `main` create `chore_release-8.2.0` merge --ff-only to `release` merge back to  `main` .)
=> chore(release): v55 release to main correction

motor-control/firmware/stepper_motor/motor_hardware.cpp
In an attempt to fix the z stage free-falling issue (see https://github.com/Opentrons/ot3-firmware/pull/804), I had moved the delay before the ebrake so that the motor current has a chance to ramp up. As a result, the ebrake now doesn't have enough time to disengage before the motor is commanded to move so now the z stage would stall occasionally. So I'm adding more delay - so now it delays after enabling the motor, and delays again after the brake is disengaged.
=> fix(motor-control): adding back the removed delay to allow ebrake to fully disegnage

include/hepa-uv/core/uv_task.hpp
This fixes an issue affecting only DVT Hepa/UV units, where the UV light won't turn on in certain cases
Closes: [RABR-638](https://opentrons.atlassian.net/browse/RABR-638)
[RABR-638]: https://opentrons.atlassian.net/browse/RABR-638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(hepa-uv): assume safety relay pin is true for rev b boards without a safety relay.

include/can/core/ids.hpp, include/can/core/message_writer.hpp, include/can/core/messages.hpp, include/common/tests/mock_message_writer.hpp, include/sensors/core/tasks/capacitive_driver.hpp, include/sensors/core/tasks/pressure_driver.hpp, sensors/tests/CMakeLists.txt, sensors/tests/test_capacitive_sensor.cpp, sensors/tests/test_pressure_driver.cpp, sensors/tests/test_pressure_sensor.cpp
In a first step to streamline tool_sensors.py we want to batch read sensor data, this will speed up the process and let us stream a lot better
This PR removes much of the complexity from tool sensors and puts creates a new log specifically for sensor data.
=> feat(sensors): add a new can message to batch read sensor data

include/motor-control/core/stepper_motor/motion_controller.hpp, include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp, motor-control/tests/test_motor_stall_handling.cpp
So from the various logs I have found 2 different cases where the 96 channel can fall down to the deck
1. During the first home after a boot up, the 96 sometimes falls, it's a little unclear on why this happens, there could be some static friction condition that happens when things are powered off.
2. If there is a Stop Request sent while the 96 is moving faster than the discontinuity speed in the downward direction, the steps immediately stop without acceleration and the momentum of the 96 overcomes the head motor, creates a resonate condition and falls.
This PR makes it a bit better by "catching" the pipette when this happens. First of all when a "stop request" is sent we will automatically call disable motor from the motion controller. This will activate the brake if there is one on …
=> fix(motor-control): catch falling 96 channel 

include/motor-control/core/stepper_motor/motion_controller.hpp
We added the disable motor in the stop request because that was the cause of some falling pipettes and we needed to turn the brake on. however disable clears the stepper ok flag and this isn't needed in this case.
So the new behavior is that it calls hardware disable_motor to turn the brake on, then it calls activate motor after to turn it back off and leaves the motor controller's 'enabled' flag true so the motion controller task has the option to call motor position update request.
=> fix(motion-control): Don't clear stepper-ok in stop request

include/motor-control/core/stepper_motor/motion_controller.hpp
* We don't need to clear the stepper ok field when we get a stop message.
* Ok i was wrong about how this worked. We don't want to leave the motor enable false we just want to turn the brake on for a bit then turn it back off to leave the motor enabled.
=> fix(motion-control): Don't clear stepper-ok in stop request (#813)

include/can/core/messages.hpp
Forgot to serialize "data_length" and then the python side was complaining when the end of the message wasn't padded because it was expecting to have a static length
=> fix how the batch message is seralized on the firmware

include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp, include/motor-control/core/types.hpp, motor-control/tests/test_brushed_motor_interrupt_handler.cpp
This fixes an error that happens during error recovery where the gripper needs to re-home because the error flow sends a stop request. 
This fixes that by adding a new state called stop, and if the firmware responds with STOPPED instead of UNHOMED then we know we can just continue on without re-homing.
The gripper will still go into a UNHOMED state during the following:
Labware droped
Collision
Estop
=> fix(gripper): add stopped state

include/motor-control/core/tasks/brushed_move_group_task.hpp, include/motor-control/core/tasks/move_group_task.hpp, include/pipettes/core/tasks/move_group_task.hpp
So when a stop request is broadcast it was previously sending out 2-3 responses per motor axis. 1 from the move group controller, 1 from the motor controller and 1 from the motor interrupt handler if the motor has been previously enabled (which is always true except right after a firmware update or power cycle.)
This PR removes the response from the move group controller, since this message always responded with a message index 0 which is unhelpful and will reduce the number of messages by 1/3 and prevents many of the "Error 1008 CAN_BUS_ERROR: error frame encountered" instances
=> fix(motor-control): improve stop request handling

.github/workflows/codecov.yaml, .github/workflows/release_bundle.yaml, state_manager/poetry.lock, state_manager/pyproject.toml
V3 artifact actions were depreciated 1/30/25 and need to be on v4 now
We needed to update the state-machine python dependencies to match the python 3.10 and pydantic 2 update on the monoreop side
Update codecov to v5 so we don't encounter the rate-limit issue that v3 has (from being depreciated) and now is the most up to date version
=> fix(.github): Fix the broken build-test and codecov workflows

motor-control/firmware/motor_control_hardware.c, motor-control/firmware/stepper_motor/motor_hardware.cpp
So we haven't seen much problems with our old 20ms delay, however the spec on the brakes is 50ms.
Recently there have been some bad batches from the supplier that take longer to engage/disengage so we are going to delay 100ms now to make sure we can accommodate any brake that's in-spec to slightly over spec,
=> fix(motor-control): improve brake delay time

include/bootloader/core/ids.h, include/can/core/ids.hpp, include/pipettes/core/sensor_tasks.hpp, include/pipettes/firmware/eeprom_keys.hpp, include/sensors/core/tasks/pressure_driver.hpp, include/sensors/core/tasks/pressure_sensor_task.hpp, pipettes/core/sensor_tasks.cpp, pipettes/firmware/eeprom_keys.cpp, pipettes/firmware/interfaces.cpp, pipettes/firmware/main.cpp, pipettes/simulator/main.cpp, sensors/tests/test_pressure_driver.cpp, sensors/tests/test_pressure_sensor.cpp
Store lifetime overpressures in the eeprom, this will now report out when a GetMotorUsageRequest is sent to the plunger node.
=> feat(eeprom): Store overpressure count

head/core/can_task.cpp, include/bootloader/core/ids.h, include/can/core/ids.hpp, include/can/core/message_handlers/motion.hpp, include/can/core/messages.hpp, include/gantry/core/can_task.hpp, include/gripper/core/can_task.hpp, include/motor-control/core/tasks/messages.hpp, include/motor-control/core/tasks/motion_controller_task.hpp, include/pipettes/core/dispatch_builder.hpp, include/pipettes/firmware/eeprom_keys.hpp, pipettes/core/linear_motor_tasks.cpp, pipettes/firmware/eeprom_keys.cpp, pipettes/firmware/interfaces.cpp
Adds a new can message that the pipette uses to increment it's resin tip dispensing tracker in eeprom.
The new value is can be retrieved with a standard usage request.
=> feat(eeprom): Add resin-tip dispense tracking

rear-panel/firmware/CMakeLists.txt
The rear panel D1 revision only has electrical/hardware changes that don't require firmware changes. However, we need new binaries to flash at the factory so we can tell which board is which.
=> chore(rear-panel): add revision D1 for stacker support

motor-control/firmware/stepper_motor/motor_hardware.cpp
The gripper z motor needs a longer delay than the carriage z motors to get its brake engaged.
=> fix: set brake delay to 120 to handle gripper z

head/firmware/can.c, include/motor-control/core/tasks/move_status_reporter_task.hpp, motor-control/tests/test_move_status_handling.cpp, pipettes/tests/test_gear_move_status_handling.cpp
A couple passes on improving (very) occasional missed move-complete messages:
- Set the can tx delay flag system wide to avoid thundering-herd message problems
- Propagate queue backpressure up to the move status reporter
=> fix: move-complete message retries
