Opentrons/ot3-firmware

include/common/core/motor.hpp
include/motor-control/core/motion_controller.hpp
include/motor-control/core/motor.hpp
include/motor-control/core/motor_driver.hpp
include/motor-control/core/spi.hpp
include/pipettes/core/uart_message_handler.hpp
include/pipettes/tests/test_motor_control.hpp
include/pipettes/tests/test_spi_comms.hpp
pipettes/firmware/uart_task.cpp
pipettes/tests/test_message_handler.cpp

This PR separates the current motor control library into two components: (1) motion controller, and (2) motor driver.

refactor(motor-control): create motion controller and motor driver components

---

common/firmware/motor_driver/motor.c
include/common/firmware/motor.h
include/motor-control/core/motion_controller.hpp
pipettes/firmware/stm32g4xx_hal_conf.h
pipettes/firmware/system_stm32g4xx.c

We thought sending pulses to the motor required a higher clock speed, but I think that was a red herring? Also adding back in a delay so the motor can actually step properly.
In other news, anyone have resources for figuring out the correct clock speed for different applications? 😢

fix(motor): clocking part2

---

.github/workflows/can.yaml
.github/workflows/common.yaml
.github/workflows/gantry.yaml
.github/workflows/pipettes.yaml
cmake/FindClang.cmake

Pull changes from https://github.com/Opentrons/cmake-utils/pull/14

chore(cmake): Cmake changes

---

can/README.md
can/simulator/rtos_main.cpp
include/can/core/freertos_can_dispatch.hpp
include/can/firmware/hal_can_message_buffer.hpp
include/common/core/freertos_message_buffer.hpp

Fix a spelling mistake and add a readme.

chore(docs): minor CANlib changes

---

.github/workflows/run_emulation.yaml

Fix what was happening here https://github.com/Opentrons/ot3-firmware/runs/3621271921?check_suite_focus=true
Is this right ?

fix(ci): run emulator action

---

common/firmware/motor_driver/motor.c
gantry/firmware/clocking.c
include/can/core/ids.hpp

feat(can): add broadcast node id

---

.github/workflows/can.yaml
.github/workflows/common.yaml
.github/workflows/gantry.yaml
.github/workflows/pipettes.yaml
can/tests/test_messages.cpp
include/pipettes/core/eeprom.hpp
pipettes/tests/test_eeprom.cpp

Unit tests weren't running in CI.
Had to fix some unit tests

fix(ci): CI runs unit tests.

---

common/firmware/can/can.c
common/firmware/errors/errors.c
common/firmware/uart/uart.c
gantry/firmware/stm32g4xx_it.c
include/motor-control/core/motion_controller.hpp
include/motor-control/core/motor.hpp
include/motor-control/core/motor_driver.hpp
pipettes/firmware/stm32g4xx_it.c

This PR removes unnecessary comments and simplifies some template code in motion_control

refactor(repo): code cleanup

---

gantry/firmware/CMakeLists.txt
pipettes/firmware/CMakeLists.txt

chore(flash): add pipettes-flash and gantry-flash targets.

---

can/simulator/CMakeLists.txt
can/simulator/main.cpp
can/tests/test_messages.cpp
include/can/core/ids.hpp
include/can/core/messages.hpp
include/pipettes/core/message_handlers/motor.hpp
pipettes/firmware/can_task.cpp

Add add distance and speed to MoveRequest.

refactor(can): remove SetSpeedRequest. change MoveRequest.

---

can/simulator/main.cpp
gantry/firmware/can_task.cpp
include/can/core/can_bus.hpp
include/can/core/device_info.hpp
include/can/core/message_writer.hpp
include/can/firmware/hal_can_bus.hpp
include/can/simulator/sim_canbus.hpp
include/common/core/freertos_task.hpp
include/pipettes/core/message_handlers/eeprom.hpp
include/pipettes/core/message_handlers/motor.hpp
pipettes/firmware/can_task.cpp

Replace CanBusWriter concept with CanBusWriter abstract base class.

refactor(can): use Inheritance for can interface.

---

can/firmware/hal_can_message_buffer.cpp
include/common/core/freertos_synchronization.hpp

Fixes a race condition between for accessing the `RxHeader`. 
I'm not sure if using a lock is better than allocating the `RxHeader` on the stack.

fix(can): race condition

---

can/firmware/hal_can_bus.cpp
common/firmware/can/can.c

Use FD Can instead of classic.
The Python side is reflected here https://github.com/Opentrons/opentrons/pull/8597

feat(can): use CAN fd

---

include/can/core/message_handlers/move_group_executor.hpp
include/can/core/messages.hpp
include/motor-control/core/motor_interrupt_handler.hpp
include/motor-control/core/motor_messages.hpp
pipettes/tests/test_motor_pulse.cpp

Adds current position to the ack message.

refactor(can): update ack message

---

include/common/firmware/utility_gpio.h
pipettes/firmware/CMakeLists.txt
pipettes/firmware/utility_gpio.c

Bring up the endstop for the pipettes subproject.

feat(pipettes): add limit switch and LED gpios

---

pipettes/firmware/motor_hardware.c
pipettes/firmware/motor_hardware.h

For now, we should set the clock pin of the motor driver to low in the pipettes subproject.

feat(pipettes): add a function to handle the motor driver clock pin in pipettes

---

can/simulator/main.cpp
can/tests/test_messages.cpp
gantry/firmware/can_task.cpp
head/firmware/can_task.cpp
include/can/core/message_handlers/motor.hpp
include/can/core/messages.hpp
include/motor-control/core/motion_controller.hpp
include/motor-control/core/motor_driver.hpp
pipettes/firmware/can_task.cpp

Removing GetStatusRequest and MoveRequest from CAN

refactor(can): remove unnecessary CAN messages

---

head/firmware/can_task.cpp

This is the correct screw pitch per mechanical

fix(head): update screw pitch

---

can/tests/test_arbitration_id.cpp
include/can/core/arbitration_id.hpp

was or'ing in new bits without clearing out old ones.

fix(CAN): bug in arbitration id

---

include/can/core/messages.hpp
python/opentrons_ot3_firmware/messages/payloads.py

id was wrong in c++
payload was wrong in python

fix(can): fix get motion constraints message.

---

can/tests/test_arbitration_id.cpp
can/tests/test_messages.cpp
gantry/simulator/CMakeLists.txt
include/can/core/arbitration_id.hpp
include/can/core/message_core.hpp
include/can/core/message_writer.hpp
include/can/core/messages.hpp
python/opentrons_ot3_firmware/arbitration_id.py
python/opentrons_ot3_firmware/constants.py
python/opentrons_ot3_firmware/messages/message_definitions.py
python/opentrons_ot3_firmware/messages/payloads.py
python/tests/opentrons_ot3_firmware/test_arbitration_id.py

Moving originating node id into arbitration id:
Haven't tested on hardware.

refactor(can): CAN arbitration id refactor

---

include/can/core/can_message_buffer.hpp
include/common/core/freertos_message_buffer.hpp
include/common/core/freertos_message_queue.hpp

template-ize freertos timeout arg as it's a different type in FW and the posix port.

refactor(sim): remove an annoying build warning

---

gantry/core/utils.cpp
gantry/firmware/interfaces.cpp
head/firmware/can_task.cpp
head/firmware/motor_hardware.c

Change to chopconf configuration actually didn't get saved properly after rebasing changes in the
gantry firmware.

fix(gantry): change the microstepping to 16

---

common/firmware/i2c/i2c.c
common/firmware/i2c/i2c_comms.cpp
include/common/firmware/i2c.h
pipettes/firmware/i2c.c
pipettes/firmware/main.cpp
pipettes/firmware/utility_gpio.c

Initial work to bring-up all of the sensors available on the pipette sensor board. Additional work is needed for bringing up a sensor task and sending/receiving messages through CAN Bus. Those tickets will be added to Jira shortly.
Closes RET-46 RET-47 and RET-48

feat(pipettes): initial pipette sensor board bringup

---

head/core/can_task.cpp

device info handler is instantiated once for HEAD and not one for L and one for R.
This PR targets the `presense-sensing` branch as that branch has prereqs for this fix.

fix(head): Device Info's response is from HEAD. Not HEAD_L or HEAD_R

---

bootloader/core/CMakeLists.txt
bootloader/core/messages.c
bootloader/tests/CMakeLists.txt
bootloader/tests/test_messages.cpp
include/bootloader/core/messages.h
python/opentrons_ot3_firmware/constants.py

Bootloader project can interpret update data and update data complete CAN message payloads.

feat(bootloader): CAN message parsing

---

python/opentrons_ot3_firmware/constants.py
python/opentrons_ot3_firmware/messages/payloads.py
python/opentrons_ot3_firmware/utils/binary_serializable.py
python/tests/opentrons_ot3_firmware/test_messages/test_payloads.py

Add FirmwareUpdateData.create method that computes checksum and makes a FirmwareUpdateData instance.

feat(python): FirmwareUpdateData payload helper

---

cmake/FindCatch2.cmake
cmake/FindSTM32G4xx.cmake

Grabbing cmake util changes from previous pr:
https://github.com/Opentrons/cmake-utils/pull/21

Changes from cmake utils

---

bootloader/simulator/main.cpp
can/simlib/transport.cpp
include/can/simlib/sim_canbus.hpp
include/can/simlib/socket_transport.hpp
include/can/simlib/socketcan_transport.hpp
include/can/simlib/transport.hpp

A little bit of a user devx upgrade. Handle disconnects and try to reconnect.
Could limit the number of retries in the future. But this is (way) better than it was.

feat(sim): simulators can handle disconnects. they retry connecting.

---

include/can/core/messages.hpp
python/opentrons_ot3_firmware/constants.py
python/opentrons_ot3_firmware/messages/message_definitions.py
python/opentrons_ot3_firmware/messages/payloads.py
python/opentrons_ot3_firmware/scripts/generate_header.py

Add generic sensor can message request and responses

feat(common): add sensor messages for all sensor reading requests

---

bootloader/core/update_state.c
bootloader/firmware/updater.c
bootloader/simulator/updater.cpp
can/core/types.cpp
can/firmware/hal_can.c
can/firmware/utils.c
common/firmware/system/app_update.c
include/bootloader/core/update_state.h
include/can/core/types.h
include/can/firmware/hal_can.h
include/can/firmware/utils.h

Small refactor to typedef enums.

refactor(can): Use enum typedefs

---

.github/workflows/gantry.yaml
.github/workflows/head.yaml
.github/workflows/pipettes.yaml
include/motor-control/core/tasks/motion_controller_task.hpp

Let's make sure simulators build before merging PRs

chore(sim): build the simulators in CI

---

common/firmware/i2c/i2c_comms.cpp
common/simulation/i2c_sim.cpp
include/common/core/i2c.hpp
include/common/firmware/i2c_comms.hpp
include/common/simulation/i2c_sim.hpp
include/pipettes/core/i2c_writer.hpp
include/pipettes/core/messages.hpp
include/pipettes/core/tasks/i2c_task.hpp
pipettes/tests/test_i2c_task.cpp

Add the ability to poll the i2c bus, which is used by both the capacitive sensor and pressure sensor.

feat(i2c): add polling capabilities to the I2C task

---

bootloader/core/message_handler.c
bootloader/core/update_state.c
bootloader/firmware/updater.c
bootloader/simulator/updater.cpp
bootloader/tests/test_message_handler.cpp
include/bootloader/core/ids.h
include/bootloader/core/update_state.h
include/bootloader/core/updater.h
include/can/core/ids.hpp

Rather than erasing the flash on the first data message, we will explicitly erase flash in response to a message.

feat(bootloader): erase flash message

---

README.md
bootloader/simulator/main.cpp
gantry/simulator/main.cpp
gripper/simulator/main.cpp
head/simulator/main.cpp
include/motor-control/core/tasks/move_group_task.hpp
pipettes/simulator/main.cpp
run_simulators.sh

This is a dev convenience PR.
Adding a script to run all the simulators.
Add signal handlers to simulators to catch SIGINT and exit.

chore: Simulator script

---

pipettes/firmware/i2c_setup.c
pipettes/firmware/main.cpp

The main sensors were actually on i2c3 bus which would explain why nothing was responding on bus 1.
The schematic labels were incorrect 😭

fix(pipettes): use correct i2c bus

---

.github/workflows/run_emulation.yaml

Update refs to 2.3.1.
The branch name is wrong. It should be `update-refs-to-v2.3.1`

emulation: Update version to 2.3.1 for run_emulation.yaml

---

include/common/firmware/utility_gpio.h
include/pipettes/firmware/i2c_setup.h
pipettes/firmware/hardware_config.c
pipettes/firmware/hardware_config.h
pipettes/firmware/i2c_setup.c
pipettes/firmware/motor_hardware.c
pipettes/firmware/utility_gpio.c

Thorough pass of GPIO pins for the low and high throughput pipettes.

refactor(pipettes): move pin configurations around for 96 channel

---

gripper/firmware/i2c_setup.c
gripper/firmware/main.cpp
i2c/firmware/i2c.c
pipettes/firmware/i2c_setup.c
pipettes/firmware/main.cpp

- fix i2c3 pin definitions for gripper
- fix eeprom wp pin definition
- Move the eeprom write disable to i2c_setup

fix(eeprom): gripper eeprom interaction.

---

gripper/core/tasks_z.cpp
include/motor-control/core/tasks/brushed_motor_driver_task.hpp
motor-control/firmware/brushed_motor/brushed_motor_driver_hardware.cpp
motor-control/firmware/brushed_motor/brushed_motor_hardware.cpp

fix(gripper): SPI overflow issue

---

include/motor-control/core/motor_hardware_interface.hpp
include/motor-control/firmware/stepper_motor/pipette_motor_hardware.hpp
include/pipettes/core/interfaces.hpp
include/pipettes/firmware/motor_hardware.hpp
motor-control/firmware/CMakeLists.txt
motor-control/firmware/stepper_motor/pipette_motor_hardware.cpp
pipettes/firmware/interfaces.cpp
pipettes/firmware/main.cpp
pipettes/firmware/utility_gpio.c

Related to RET-916 and RET-918. Adding in tip sense support for the pipette motor hardware.

feat(pipettes): add tip sense support in motor hardware 

---

include/bootloader/core/ids.h
include/can/core/ids.hpp
include/can/core/messages.hpp
include/gripper/core/can_task.hpp
include/gripper/core/gripper_info.hpp
include/pipettes/core/dispatch_builder.hpp
include/pipettes/core/pipette_info.hpp

- Implement `SetSerialNumber` message. 
- Handle this message in the Gripper and Pippettes

feat(gripper, pipettes): store serial number

---

can/README.md

docs(can): readme clean up.

---

gripper/core/can_tasks.cpp
gripper/core/tasks.cpp
gripper/firmware/clocking.c
gripper/firmware/i2c_setup.c
gripper/firmware/main.cpp
gripper/firmware/utility_gpio.c
gripper/simulator/FreeRTOSConfig.h
gripper/simulator/freertos_idle_timer_task.cpp
gripper/simulator/main.cpp
include/gripper/core/can_task.hpp
include/gripper/core/tasks.hpp
include/gripper/firmware/i2c_setup.h
include/sensors/core/utils.hpp
pipettes/core/peripheral_tasks.cpp

Adding capacitive sensor task to the gripper subproject.

feat(gripper): add capacitive sensor task

---

ot3_state_manager/Makefile
ot3_state_manager/README.md
ot3_state_manager/poetry.lock
ot3_state_manager/pyproject.toml

Added a README
Add README linting to make targets and CI

docs: OT-3 State Manager README Init

---

can/tests/test_messages.cpp
eeprom/tests/CMakeLists.txt
eeprom/tests/test_data_rev.cpp
eeprom/tests/test_dev_data.cpp
eeprom/tests/test_eeprom_task.cpp
eeprom/tests/test_revision.cpp
eeprom/tests/test_serial_number.cpp
include/can/core/messages.hpp
include/eeprom/core/accessor.hpp
include/eeprom/core/addresses.hpp
include/eeprom/core/data_rev.hpp
include/eeprom/core/dev_data.hpp
include/eeprom/core/hardware_iface.hpp
include/eeprom/core/messages.hpp
include/eeprom/core/revision.hpp
include/eeprom/core/serial_number.hpp
include/eeprom/core/task.hpp
include/eeprom/core/types.hpp
include/eeprom/simulation/eeprom.hpp
include/eeprom/tests/mock_eeprom_listener.hpp
include/eeprom/tests/mock_eeprom_task_client.hpp
include/gripper/core/gripper_info.hpp
include/pipettes/core/pipette_info.hpp
pipettes/core/pipette_type_384.cpp
pipettes/core/pipette_type_96.cpp
pipettes/core/pipette_type_multi.cpp
pipettes/core/pipette_type_single.cpp

This PR is paired with this PR https://github.com/Opentrons/opentrons/pull/11260

feat(eeprom):  implement eeprom filesystem

---

pipettes/firmware/motor_configurations.cpp
pipettes/firmware/utility_gpio.c

Are different, and now are different in code.

fix(pipettes): evt switch and direction gpios

---

gripper/firmware/CMakeLists.txt

fix(gripper): hex image file missing revision value

---

.github/workflows/run_emulation.yaml

Need to update to latest version of opentrons-emulation

chore: Update refs to v3.0.0

---

gantry/firmware/interfaces_proto.cpp
gantry/firmware/interfaces_rev1.cpp
gantry/firmware/motor_hardware.c
gantry/firmware/motor_hardware.h
gantry/firmware/stm32g4xx_it.c

We didn't actually set up the encoders for XY.. Here it is!

fix(gantry): set up encoder for XY

---

gantry/simulator/interfaces.cpp
gripper/simulator/main.cpp
head/simulator/main.cpp
pipettes/simulator/main.cpp

State manager connection has some issues. Will be re-enabled in a future PR.

feat(simulators): disable state manager connection for now

---

.github/workflows/run_emulation.yaml

I was getting annoyed with the red flags

fix(emulation): use emulation v3.0.1 to let CI pass

---

include/motor-control/core/stepper_motor/motor_interrupt_handler.hpp

This PR reduces the overhead of the stepper motor interrupt on the OT-3 firmware boards. In particular, the head board was struggling with the overhead of the two stepper interrupts resource-starving all of the FreeRTOS tasks, including the highest-priority watchdog task. 
Tested cycling a head board's motors up and down repeatedly. Before this change, the status LED would not be blinking during movements and the watchdog would usually expire. After the change, the board functions as expected.

fix(motor-control): reduce GPIO write operations during stepper interrupts

---

include/motor-control/core/brushed_motor/brushed_motion_controller.hpp
include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp
include/motor-control/core/motor_hardware_interface.hpp
include/motor-control/firmware/brushed_motor/brushed_motor_hardware.hpp
include/motor-control/simulation/sim_motor_hardware_iface.hpp
include/motor-control/tests/mock_brushed_motor_components.hpp
motor-control/tests/test_brushed_motor_interrupt_handler.cpp

This PR watches the gripper g encoder during force control moves (when homed or gripping something) and if there is unexpected movement we report an error
https://opentrons.atlassian.net/browse/RLAB-74
https://opentrons.atlassian.net/browse/RLAB-150
https://opentrons.atlassian.net/browse/RLAB-151

feature(gripper): add detection for dropping labware or collision detection

---

head/firmware/main_rev1.cpp

There is one fewer gear and therefore the direction is now different.
Closes RET-1314

refactor(head): flip directions for dvt

---

include/rear-panel/core/bin_msg_ids.hpp
include/rear-panel/core/binary_parse.hpp
include/rear-panel/core/messages.hpp
include/rear-panel/core/tasks.hpp
include/rear-panel/core/tasks/host_comms_task.hpp
rear-panel/CMakeLists.txt
rear-panel/core/tasks.cpp
rear-panel/firmware/host_comms_task/freertos_comms_task.cpp
rear-panel/test/CMakeLists.txt
rear-panel/test/test_main.cpp
rear-panel/test/test_messages.cpp

Create a system for defining messages then lets the protocol automatically parse and create the message type
using the incoming binary message from the host. 
Also create the serialize to take messages and convert them to a binary blob to send to the host.
add tests to verify the serializing and parsing

feature(rear-panel):  add abinary messaging protocol to the rear panel

---

scripts/subsystem_versions.py

update the manifest version to 2
add a usb_subsystems category after subsystems
add rear panel to the usb_subsystems

chore(scripts): add the firmware to the oe builds

---

bootloader/firmware/stm32G4/CMakeLists.txt
bootloader/firmware/stm32G4/node_id_stm32g4xx.c
include/bootloader/core/node_id.h
include/bootloader/core/pipette_type.h
pipettes/firmware/main.cpp
pipettes/firmware/pipette_utility_gpio.h
pipettes/firmware/utility_gpio.c

Correct the mount detect GPIO pins.

fix(pipettes): we did not update the mount detect GPIO for the 96 channel for DVT changes

---

common/core/revision.c.in
include/common/core/version.h
include/rear-panel/core/messages.hpp
rear-panel/firmware/CMakeLists.txt
rear-panel/startup/STM32G491/clear_wp_stm32g491.cfg
rear-panel/test/test_messages.cpp
scripts/subsystem_versions.py

minor discrepancy on a struct size, and the rear panel application needs to be a .bin and not a .hex for dfu to work properly

fix(rear-panel): some fixes that were needed during update testing

---

gripper/firmware/interfaces_z_motor.cpp
gripper/firmware/motor_hardware_z.c
gripper/firmware/utility_gpio.c

Initialize ebrake gpio for DVT gripper.

feat(gripper): add ebrake gpio

---

include/motor-control/core/brushed_motor/error_tolerance_config.hpp
motor-control/tests/test_brushed_motor_interrupt_handler.cpp

hardware said we should switch this to 2mm to make errors less spamy until further testing can find a better value

fix(gripper): reduce gripper error spam

---

pipettes/simulator/main.cpp

Fixes a few issues causing I2C on the pipette simulators to crash
- Set the EEPROM chip type differently for 96 channel target
- Allocate EEPROM to I2C1 or I2C3 based on whether this is a 96 channel
- Only include the front capsensor on 96 channel (shared on 8 channel)
- Add a second pressure sensor, with different hardware based on which target this is
Tested by running an ot3 emulator and watching the pipette simulator not crash.

fix(pipettes): fix pipette simulators crashing

---

include/motor-control/core/brushed_motor/brushed_motor_interrupt_handler.hpp

Don't drop labware when a stop requested or estop detected while a labware is being held

fix(motor-control): Don't drop labware

---

head/firmware/utility_hardware.c

96 channel drops on boot if brakes aren't on

fix(head): enable the brake pins on boot

---

include/rear-panel/core/tasks.hpp
include/rear-panel/core/tasks/hardware_task.hpp
include/rear-panel/core/tasks/heartbeat_task.hpp
include/rear-panel/firmware/gpio_drive_hardware.hpp
include/rear-panel/firmware/utility_gpio.h
rear-panel/core/tasks.cpp
rear-panel/firmware/CMakeLists.txt
rear-panel/firmware/utility_gpio.c

Adds the new revision which enables:
heartbeat LED
PGOOD input pin

feat(rear-panel): add the revb2 in anticipation of the new boards

---

gripper/firmware/stm32g4xx_it.c

Tested this overnight and it's working well so I think we should do this to further improve the gripper performance.

feat(gripper): add ccram header to the rest of the interrupts in the gripper

---

i2c/firmware/i2c.c

When #696 switched from blocking to interrupt-based I2C, it did not change the handling of Nack conditions. Turns out that the old handling didn't work with the interrupt-based HAL functions, and instead we should catch those conditions based on whether the Complete Callback or the Error Callback gets invoked.
If the Error Callback gets called, simply retry the transmission.
Tested with a P50 Single Channel pipette. Before this PR, the pressure sensor always returned a pressure of -0.001. After the PR, it returns actual pressure data.

fix(i2c): handle NACK condition properly

---

state_manager/state_manager/hardware.py
state_manager/state_manager/measurable_states.py
state_manager/state_manager/messages.py
state_manager/state_manager/ot3_state.py
state_manager/state_manager/util.py
state_manager/tests/test_messages.py
state_manager/tests/test_ot3_state.py
state_manager/tests/test_ot3_state_manager.py

https://github.com/Opentrons/opentrons/pull/12834 merged OT3Axis and Axis (at long last) and we must adapt.

fix(state-manager): use Axis instead of OT3Axis

---

include/sensors/core/tasks/capacitive_driver.hpp

We were having some trouble with the 96 channel attach + calibration workflow. If the 96 channel is newly attached and then the robot server tries to calibrate it, sometimes it will not respond to any capacitive sensor requests. This does not seem to apply to when the pipette is restarted electronically (e.g. with a debugger without de-attaching it), or if it was attached since the robot turned on.
One recent change (#703) made it so that, once the cap sensor is initialized for the first time on startup, the measurement config register (FDC Conf) will never be updated again. Because the sensor task will only return data once the Ready flag is asserted for a channel, the reading register _needs_ to be configured. If the capacitive sensor IC somehow restarted without the MCU restarting, no …

fix(sensors): reconfigure cap sensor if necessary

---

bootloader/firmware/stm32G4/CMakeLists.txt
pipettes/firmware/CMakeLists.txt

Adds a new hardware revision for the 96 channel pipette.

chore: add pipette 96 revision d2

---

push

feat(push): add option to specify ssh key when pushing firmware to ot3

---

head/firmware/motor_hardware_rev1.c

The ebrakes shall be turned on at boot.

fix(head): engage ebrake at boot

---

include/hepa-uv/core/hepa_task.hpp

Spoke the hardware team and they have been testing the hepa fan at 75% duty cycle, so lets change set it to that.

fix(hepa-uv): set the hepa duty cycle to 75% per hw team.

---

include/hepa-uv/firmware/hepa_control_hardware.hpp

Noticed that my CI builds were failing from this, and I want those sweet sweet ✅

fix(hepa): fix a linter bug that makes CI complain

---

push

I broke the changes to the push script when I updated some of the things for the CI build variant

fix(push): fix the push script after breaking it with CI changes

---

include/sensors/core/tasks/pressure_driver.hpp

Silly mistake, was essentially doing nothing before

fix(sensors): correctly correct the past sensor readings

---

include/hepa-uv/core/uv_task.hpp

Make sure any isolated changes, history, and tags that happened in the chore_release-8.0.0 branch are in main.

fix(hepa-uv): fix issue when turning on UV after re-seating the hepa

---

head/core/can_task.cpp
include/bootloader/core/ids.h
include/can/core/ids.hpp
include/can/core/message_handlers/motion.hpp
include/can/core/messages.hpp
include/gantry/core/can_task.hpp
include/gripper/core/can_task.hpp
include/motor-control/core/tasks/messages.hpp
include/motor-control/core/tasks/motion_controller_task.hpp
include/pipettes/core/dispatch_builder.hpp
include/pipettes/firmware/eeprom_keys.hpp
pipettes/core/linear_motor_tasks.cpp
pipettes/firmware/eeprom_keys.cpp
pipettes/firmware/interfaces.cpp

> This path will have a merge commit along with the code change and that is OK 😊 
```shell
git checkout main && git pull
git checkout chore_release-8.4.0 && git pull
git checkout -b chore_release-8.4.0_to_main_for_8.4.0
git merge merge main
git push
```
```shell
git checkout main && git pull
git merge --ff-only chore_release-8.4.0_to_main_for_8.4.0
git push
```
This PR will then be merged.

chore(release): merge back chore_release-8.4.0 to main
